import { describe,expect,it } from "vitest";
import { createConstraintSet,createIntentSet } from "../../intent";
import { DeterministicCandidatePlanConstructionEngine,DeterministicCandidatePlanRegistry,productionCandidatePlanPolicies } from ".";

describe("Calendar-to-Candidate-Plan boundary",()=>{it("does not turn calendar content into a candidate without an explicit definition",()=>{
 const context={contextId:"calendar-context",snapshotId:"calendar-snapshot",assessmentSetId:"calendar-assessments",sections:[{sectionId:"calendar-commitments",entries:[{title:"A narrative meeting title",description:"Narrative content is not a plan"}],metadata:[]}],statistics:[],summary:{sectionCount:1,statisticCount:0,situationCount:0,assessmentCount:0,attentionRecordCount:0,observationCount:1},canonicalProvenance:{snapshotId:"calendar-snapshot",assessmentSetId:"calendar-assessments",situationSetId:"calendar-situations",policies:[]}} as const;
 const intentSet=createIntentSet({intentSetId:"intent-set:calendar-context:calendar-objective",contextId:"calendar-context",objectives:[{identifier:"calendar-objective",type:"operational",description:"Explicit objective",origin:"typed test configuration",activationStatus:"active",scope:{},metadata:{policyId:"explicit",policyVersion:"1"}}],summary:{objectiveCount:1,activeCount:1,inactiveCount:0,byType:{operational:1,strategic:0,standing:0,session:0,mission:0}},provenance:{contextId:"calendar-context",policies:[]}});
 const constraintSet=createConstraintSet({constraintSetId:"constraint-set:calendar-context:",contextId:"calendar-context",constraints:[],summary:{constraintCount:0,bindingCount:0,nonBindingCount:0,byType:{authority:0,temporal:0,resource:0,governance:0,behavioural:0,privacy:0,execution:0,approval:0}},provenance:{contextId:"calendar-context",policies:[]}});
 const engine=new DeterministicCandidatePlanConstructionEngine(new DeterministicCandidatePlanRegistry(productionCandidatePlanPolicies));const first=engine.construct({context,intentSet,constraintSet,definitions:[]});const replay=engine.construct({context,intentSet,constraintSet,definitions:[]});expect(first).toEqual(replay);expect(first.candidates).toEqual([]);
});});
