import type { CandidatePlan, CandidatePlanConstructionEngine, CandidatePlanConstructionInput, CandidatePlanSet } from "./types";
import { DeterministicCandidatePlanRegistry } from "./registry";
import { createConstraintSet, createIntentSet } from "../../intent";
import { clone, comparePlans, createCandidatePlanSet, evidenceKey, jsonCompatible, planIdentity, setIdentity, summary, validateDefinition } from "./validation";
export class DeterministicCandidatePlanConstructionEngine implements CandidatePlanConstructionEngine {
 constructor(private readonly registry:DeterministicCandidatePlanRegistry){if(!(registry instanceof DeterministicCandidatePlanRegistry))throw new Error("candidate plan registry is required");}
 construct(input:CandidatePlanConstructionInput):CandidatePlanSet {
  if(!input?.context||!input.intentSet||!input.constraintSet||!Array.isArray(input.definitions))throw new Error("candidate plan construction input is required");jsonCompatible(input,"candidate plan construction input");if(typeof input.context.contextId!=="string"||!input.context.contextId.trim())throw new Error("executive context identifier is required");createIntentSet(input.intentSet);createConstraintSet(input.constraintSet);
  if(input.intentSet.contextId!==input.context.contextId||input.constraintSet.contextId!==input.context.contextId)throw new Error("planning state context identities do not agree");
  input.definitions.forEach(validateDefinition);if(new Set(input.definitions.map(x=>x.identifier)).size!==input.definitions.length)throw new Error("duplicate candidate plan definition identifier");
  const objectives=new Set(input.intentSet.objectives.map(x=>x.identifier)),constraints=new Set(input.constraintSet.constraints.map(x=>x.identifier));input.definitions.forEach((d:import("./types").CandidatePlanDefinition)=>{d.objectiveReferences.forEach((x:string)=>{if(!objectives.has(x))throw new Error(`unresolved objective reference: ${x}`)});d.constraintReferences.forEach((x:string)=>{if(!constraints.has(x))throw new Error(`unresolved constraint reference: ${x}`)});d.approvalRequirements.forEach((a:import("./types").CandidatePlanApprovalRequirement)=>{if(a.constraintIdentifier&&!constraints.has(a.constraintIdentifier))throw new Error(`unresolved constraint reference: ${a.constraintIdentifier}`)});});
  const policies=this.registry.policies(),definitions=[...input.definitions].sort((a,b)=>a.identifier<b.identifier?-1:a.identifier>b.identifier?1:a.version<b.version?-1:a.version>b.version?1:0),plans:CandidatePlan[]=[];
  for(const p of policies)for(const d of definitions){if(!p.supportedCategories.includes(d.category))continue;const policyInput=clone(input),definition=clone(d),a=p.evaluate(policyInput,definition);jsonCompatible(a,"candidate plan applicability");if(typeof a.applicable!=="boolean"||!Array.isArray(a.evidenceReferences))throw new Error("malformed candidate plan applicability result");if(a.applicable){const plan=clone(p.construct(clone(input),clone(d),clone(a)));jsonCompatible(plan,"candidate plan");const {candidatePlanId: _identity,...identityInput}=plan;if(plan.candidatePlanId!==planIdentity(identityInput))throw new Error("invalid candidate plan identity");if(plan.definitionIdentifier!==d.identifier||plan.policyIdentifier!==p.identifier)throw new Error("candidate plan provenance is inconsistent");if(new Set(plan.steps.map(x=>x.identifier)).size!==plan.steps.length)throw new Error("duplicate candidate plan step identifier");if(plan.evidenceReferences.map(evidenceKey).some((x,i,a)=>a.indexOf(x)!==i))throw new Error("duplicate candidate evidence reference");plans.push(plan);}}
  plans.sort(comparePlans);if(new Set(plans.map(x=>x.candidatePlanId)).size!==plans.length)throw new Error("duplicate candidate plan identifier");const provenance={contextId:input.context.contextId,intentSetId:input.intentSet.intentSetId,constraintSetId:input.constraintSet.constraintSetId,policies:policies.map(x=>({identifier:x.identifier,version:x.version}))};const result={candidatePlanSetId:setIdentity(provenance.contextId,provenance.intentSetId,provenance.constraintSetId,provenance.policies,plans.map(x=>x.candidatePlanId)),...provenance,candidates:plans,summary:summary(definitions.length,policies,plans),provenance};return createCandidatePlanSet(result);
 }
}
