import type { CandidatePlan, CandidatePlanApplicability, CandidatePlanCategory, CandidatePlanConstructionInput, CandidatePlanConstructionPolicy, CandidatePlanDefinition, CandidatePlanEvidenceReference, CandidatePlanStep } from "./types";
import { clone, compareText, evidenceKey, planIdentity, stepIdentity } from "./validation";

function referencePresent(input:CandidatePlanConstructionInput,r:CandidatePlanEvidenceReference):boolean {
  if(r.type==="context")return input.context.contextId===r.identifier;
  if(r.type==="context-section")return input.context.sections.some(x=>x.sectionId===r.identifier);
  if(r.type==="context-statistic")return input.context.statistics.some(x=>x.statisticId===r.identifier);
  if(r.type==="assessment")return input.context.assessmentSetId===r.identifier||contains(input.context.sections,r.identifier);
  if(r.type==="situation")return input.context.canonicalProvenance.situationSetId===r.identifier||contains(input.context.sections,r.identifier);
  if(r.type==="observation")return input.context.snapshotId===r.identifier||contains(input.context.sections,r.identifier);
  return contains(input.context.sections,r.identifier);
}
function contains(v:unknown,target:string):boolean { if(v===target)return true;if(Array.isArray(v))return v.some(x=>contains(x,target));if(v&&typeof v==="object")return Object.values(v).some(x=>contains(x,target));return false; }
const applicable=(input:CandidatePlanConstructionInput,d:CandidatePlanDefinition):CandidatePlanApplicability=>({applicable:d.metadata.status==="active"&&d.objectiveReferences.every(id=>input.intentSet.objectives.some(x=>x.identifier===id&&x.activationStatus==="active"))&&d.constraintReferences.every(id=>input.constraintSet.constraints.some(x=>x.identifier===id))&&d.contextRequirements.every(r=>referencePresent(input,r)),evidenceReferences:[...d.contextRequirements].sort((a,b)=>compareText(evidenceKey(a),evidenceKey(b))) });
function construct(policy:CandidatePlanConstructionPolicy,input:CandidatePlanConstructionInput,d:CandidatePlanDefinition,a:CandidatePlanApplicability):CandidatePlan {
 const objectives=[...d.objectiveReferences].sort(compareText), constraints=[...d.constraintReferences].sort(compareText);
 const steps:CandidatePlanStep[]=[...d.steps].sort((x,y)=>x.ordinal-y.ordinal||compareText(x.identifier,y.identifier)).map(s=>{const refs=[...(s.objectiveReferences??objectives)].sort(compareText);return {identifier:stepIdentity(d.identifier,d.version,s.identifier,refs),type:s.type,ordinal:s.ordinal,description:s.description,objectiveReferences:refs,evidenceReferences:clone(s.evidenceReferences??[]),dependencyReferences:clone(s.dependencyReferences??[]),approvalRequirementReferences:clone(s.approvalRequirementReferences??[]),completionConditionReferences:clone(s.completionConditionReferences??[]),provenance:{definitionIdentifier:d.identifier,definitionVersion:d.version,configuredStepIdentifier:s.identifier,origin:d.origin}}});
 const base={category:d.category,definitionIdentifier:d.identifier,definitionVersion:d.version,policyIdentifier:policy.identifier,policyVersion:policy.version,objectiveReferences:objectives,constraintReferences:constraints,evidenceReferences:clone(a.evidenceReferences),steps,assumptions:clone(d.assumptions),dependencies:clone(d.dependencies),approvalRequirements:clone(d.approvalRequirements),completionConditions:clone(d.completionConditions),provenance:{contextId:input.context.contextId,intentSetId:input.intentSet.intentSetId,constraintSetId:input.constraintSet.constraintSetId,definitionIdentifier:d.identifier,definitionVersion:d.version,policyIdentifier:policy.identifier,policyVersion:policy.version,objectiveReferences:objectives,evidenceReferences:clone(a.evidenceReferences),origin:d.origin}};
 return {...base,candidatePlanId:planIdentity(base)};
}
function policy(identifier:string,displayName:string,categories:readonly CandidatePlanCategory[],extra:(i:CandidatePlanConstructionInput,d:CandidatePlanDefinition)=>boolean):CandidatePlanConstructionPolicy { const p:CandidatePlanConstructionPolicy={identifier,version:"1.0.0",metadata:{identifier,version:"1.0.0",displayName,description:`Deterministically constructs ${displayName.toLowerCase()} definitions.`,origin:"JARVIS Sprint 3.19",status:"active"},supportedCategories:categories,evaluate(i,d){const a=applicable(i,d);return {...a,applicable:a.applicable&&categories.includes(d.category)&&extra(i,d)}},construct(i,d,a){if(!a.applicable)throw new Error("cannot construct a non-applicable candidate plan");return construct(p,i,d,a)}};return p; }
export const explicitObjectivePlanPolicy=policy("explicit-objective-plan","Explicit Objective Plan",["operational-response","configured-workflow","commitment-adjustment-proposal","escalation-proposal"],(_i,d)=>d.objectiveReferences.length>0);
export const contextRequirementPlanPolicy=policy("context-requirement-plan","Context Requirement Plan",["information-gathering"],(_i,d)=>d.contextRequirements.length>0);
export const explicitApprovalSeekingPlanPolicy=policy("explicit-approval-seeking-plan","Explicit Approval-Seeking Plan",["approval-seeking"],(i,d)=>d.approvalRequirements.length>0&&d.approvalRequirements.every(a=>(!a.constraintIdentifier||i.constraintSet.constraints.some(c=>c.identifier===a.constraintIdentifier))&&Boolean(a.authorityReference||a.constraintIdentifier)));
export const explicitMonitoringPlanPolicy=policy("explicit-monitoring-plan","Explicit Monitoring Plan",["monitoring-continuation"],(_i,d)=>d.completionConditions.length>0);
export const explicitNoActionPlanPolicy=policy("explicit-no-action-plan","Explicit No-Action Plan",["no-action-observation"],(_i,d)=>d.completionConditions.length>0);
export const productionCandidatePlanPolicies=Object.freeze([explicitObjectivePlanPolicy,contextRequirementPlanPolicy,explicitApprovalSeekingPlanPolicy,explicitMonitoringPlanPolicy,explicitNoActionPlanPolicy]);
