import type { ExecutiveDeliberationContext } from "../../deliberation";
import type { ConstraintSet, IntentSet } from "../../intent";

export type CandidatePlanCategory = "operational-response" | "information-gathering" | "approval-seeking" | "commitment-adjustment-proposal" | "escalation-proposal" | "monitoring-continuation" | "no-action-observation" | "configured-workflow";
export type CandidateReferenceType = "context" | "context-section" | "context-statistic" | "situation" | "assessment" | "attention" | "observation";
export interface CandidatePlanEvidenceReference { readonly type: CandidateReferenceType; readonly identifier: string }
export interface CandidatePlanDefinitionMetadata { readonly identifier: string; readonly version: string; readonly displayName: string; readonly description: string; readonly origin: string; readonly status: "active" | "inactive" }
export interface CandidatePlanStepDefinition { readonly identifier: string; readonly type: string; readonly ordinal: number; readonly description: string; readonly objectiveReferences?: readonly string[]; readonly evidenceReferences?: readonly CandidatePlanEvidenceReference[]; readonly dependencyReferences?: readonly string[]; readonly approvalRequirementReferences?: readonly string[]; readonly completionConditionReferences?: readonly string[] }
export interface CandidatePlanAssumption { readonly identifier: string; readonly type: string; readonly statement: string; readonly origin: string; readonly evidenceReferences: readonly CandidatePlanEvidenceReference[] }
export interface CandidatePlanDependency { readonly identifier: string; readonly type: string; readonly referencedStepIdentifier?: string; readonly canonicalReference?: CandidatePlanEvidenceReference; readonly origin: string; readonly bindingStatus?: "binding" | "non-binding" }
export interface CandidatePlanApprovalRequirement { readonly identifier: string; readonly type: string; readonly authorityReference?: string; readonly constraintIdentifier?: string; readonly scope: Readonly<Record<string, import("../../intent").CanonicalValue>>; readonly origin: string }
export interface CandidatePlanCompletionCondition { readonly identifier: string; readonly type: string; readonly expectedState: import("../../intent").CanonicalValue; readonly canonicalReference?: CandidatePlanEvidenceReference; readonly origin: string }
export interface CandidatePlanDefinition { readonly identifier: string; readonly version: string; readonly metadata: CandidatePlanDefinitionMetadata; readonly category: CandidatePlanCategory; readonly supportedObjectiveCategories?: readonly import("../../intent").IntentType[]; readonly objectiveReferences: readonly string[]; readonly contextRequirements: readonly CandidatePlanEvidenceReference[]; readonly steps: readonly CandidatePlanStepDefinition[]; readonly assumptions: readonly CandidatePlanAssumption[]; readonly dependencies: readonly CandidatePlanDependency[]; readonly approvalRequirements: readonly CandidatePlanApprovalRequirement[]; readonly completionConditions: readonly CandidatePlanCompletionCondition[]; readonly constraintReferences: readonly string[]; readonly origin: string }
export interface CandidatePlanConstructionPolicyMetadata { readonly identifier: string; readonly version: string; readonly displayName: string; readonly description: string; readonly origin: string; readonly status: "active" | "inactive" }
export interface CandidatePlanConstructionInput { readonly context: ExecutiveDeliberationContext; readonly intentSet: IntentSet; readonly constraintSet: ConstraintSet; readonly definitions: readonly CandidatePlanDefinition[] }
export interface CandidatePlanApplicability { readonly applicable: boolean; readonly evidenceReferences: readonly CandidatePlanEvidenceReference[] }
export interface CandidatePlanConstructionPolicy { readonly identifier: string; readonly version: string; readonly metadata: CandidatePlanConstructionPolicyMetadata; readonly supportedCategories: readonly CandidatePlanCategory[]; evaluate(input: CandidatePlanConstructionInput, definition: CandidatePlanDefinition): CandidatePlanApplicability; construct(input: CandidatePlanConstructionInput, definition: CandidatePlanDefinition, applicability: CandidatePlanApplicability): CandidatePlan }
export interface CandidatePlanStep extends Omit<CandidatePlanStepDefinition, "objectiveReferences" | "evidenceReferences" | "dependencyReferences" | "approvalRequirementReferences" | "completionConditionReferences"> { readonly objectiveReferences: readonly string[]; readonly evidenceReferences: readonly CandidatePlanEvidenceReference[]; readonly dependencyReferences: readonly string[]; readonly approvalRequirementReferences: readonly string[]; readonly completionConditionReferences: readonly string[]; readonly provenance: Readonly<{ definitionIdentifier: string; definitionVersion: string; configuredStepIdentifier: string; origin: string }> }
export interface CandidatePlan { readonly candidatePlanId: string; readonly category: CandidatePlanCategory; readonly definitionIdentifier: string; readonly definitionVersion: string; readonly policyIdentifier: string; readonly policyVersion: string; readonly objectiveReferences: readonly string[]; readonly constraintReferences: readonly string[]; readonly evidenceReferences: readonly CandidatePlanEvidenceReference[]; readonly steps: readonly CandidatePlanStep[]; readonly assumptions: readonly CandidatePlanAssumption[]; readonly dependencies: readonly CandidatePlanDependency[]; readonly approvalRequirements: readonly CandidatePlanApprovalRequirement[]; readonly completionConditions: readonly CandidatePlanCompletionCondition[]; readonly provenance: Readonly<{ contextId: string; intentSetId: string; constraintSetId: string; definitionIdentifier: string; definitionVersion: string; policyIdentifier: string; policyVersion: string; objectiveReferences: readonly string[]; evidenceReferences: readonly CandidatePlanEvidenceReference[]; origin: string }> }
export interface CandidatePlanSummary { readonly definitionCount: number; readonly policyCount: number; readonly candidateCount: number; readonly objectiveCount: number; readonly constraintCount: number; readonly stepCount: number; readonly assumptionCount: number; readonly dependencyCount: number; readonly approvalRequirementCount: number; readonly completionConditionCount: number; readonly byCategory: Readonly<Record<CandidatePlanCategory, number>>; readonly byPolicy: Readonly<Record<string, number>> }
export interface CandidatePlanSet { readonly candidatePlanSetId: string; readonly contextId: string; readonly intentSetId: string; readonly constraintSetId: string; readonly candidates: readonly CandidatePlan[]; readonly summary: CandidatePlanSummary; readonly provenance: Readonly<{ contextId: string; intentSetId: string; constraintSetId: string; policies: readonly Readonly<{ identifier: string; version: string }>[] }> }
export interface CandidatePlanRegistry { register(policy: CandidatePlanConstructionPolicy): void; policies(): readonly CandidatePlanConstructionPolicy[] }
export interface CandidatePlanConstructionEngine { construct(input: CandidatePlanConstructionInput): CandidatePlanSet }
