import type { CandidatePlan, CandidatePlanConstructionPolicy, CandidatePlanDefinition, CandidatePlanSet, CandidatePlanSummary, CandidatePlanCategory, CandidatePlanEvidenceReference } from "./types";
export const compareText = (a: string, b: string) => a < b ? -1 : a > b ? 1 : 0;
export function required(v: unknown, p: string): asserts v is string { if (typeof v !== "string" || !v.trim()) throw new Error(`${p} must be a non-empty string`); }
export function clone<T>(v: T): T { if (Array.isArray(v)) return v.map(clone) as T; if (v && typeof v === "object") return Object.fromEntries(Object.entries(v).map(([k,x]) => [k,clone(x)])) as T; return v; }
export function deepFreeze<T>(v: T): T { if (v && typeof v === "object" && !Object.isFrozen(v)) { Object.values(v).forEach(deepFreeze); Object.freeze(v); } return v; }
export function jsonCompatible(v: unknown,p="value",seen=new Set<object>()): void { if(v===null||typeof v==="string"||typeof v==="boolean"||(typeof v==="number"&&Number.isFinite(v)))return; if(!v||typeof v!=="object"||seen.has(v as object)||(!Array.isArray(v)&&Object.getPrototypeOf(v)!==Object.prototype))throw new Error(`${p} must contain only JSON-compatible values`); seen.add(v as object); Object.entries(v).forEach(([k,x])=>jsonCompatible(x,`${p}.${k}`,seen)); seen.delete(v as object); }
const categories: readonly CandidatePlanCategory[]=["operational-response","information-gathering","approval-seeking","commitment-adjustment-proposal","escalation-proposal","monitoring-continuation","no-action-observation","configured-workflow"];
const unique=(xs:readonly string[],label:string)=>{xs.forEach((x,i)=>required(x,`${label} ${i}`));if(new Set(xs).size!==xs.length)throw new Error(`duplicate ${label}`)};
export function validateDefinition(d:CandidatePlanDefinition):void { jsonCompatible(d,"candidate plan definition"); required(d?.identifier,"definition identifier");required(d.version,"definition version"); if(d.metadata?.identifier!==d.identifier||d.metadata?.version!==d.version)throw new Error("definition metadata identity is inconsistent"); [d.metadata.displayName,d.metadata.description,d.metadata.origin,d.origin].forEach((x,i)=>required(x,`definition metadata field ${i}`));if(!["active","inactive"].includes(d.metadata.status))throw new Error("invalid definition status");if(!categories.includes(d.category))throw new Error("invalid candidate category"); [d.objectiveReferences,d.contextRequirements,d.steps,d.assumptions,d.dependencies,d.approvalRequirements,d.completionConditions,d.constraintReferences].forEach(x=>{if(!Array.isArray(x))throw new Error("definition collections are required")}); unique(d.objectiveReferences,"objective reference");unique(d.constraintReferences,"constraint reference"); unique(d.steps.map(x=>x.identifier),"step identifier"); const stepIds=new Set(d.steps.map(x=>x.identifier)); d.steps.forEach((s,i)=>{required(s.identifier,`step ${i} identifier`);required(s.type,`step ${i} type`);required(s.description,`step ${i} description`);if(!Number.isSafeInteger(s.ordinal)||s.ordinal<0)throw new Error("step ordinal must be a non-negative integer");(s.dependencyReferences??[]).forEach(x=>{if(!stepIds.has(x))throw new Error(`unresolved step dependency: ${x}`)});}); const visit=(id:string,path=new Set<string>())=>{if(path.has(id))throw new Error("cyclic step dependency");path.add(id);const s=d.steps.find(x=>x.identifier===id);(s?.dependencyReferences??[]).forEach(x=>visit(x,new Set(path)));};stepIds.forEach(x=>visit(x)); unique(d.assumptions.map(x=>x.identifier),"assumption identifier");unique(d.dependencies.map(x=>x.identifier),"dependency identifier");unique(d.approvalRequirements.map(x=>x.identifier),"approval requirement identifier");unique(d.completionConditions.map(x=>x.identifier),"completion condition identifier");if(d.category==="no-action-observation"&&!d.completionConditions.length)throw new Error("no-action definitions require a completion condition"); }
export function validatePolicy(p:CandidatePlanConstructionPolicy):void { if(!p||typeof p!=="object")throw new Error("candidate plan policy must be an object");required(p.identifier,"policy identifier");required(p.version,"policy version");if(p.metadata?.identifier!==p.identifier||p.metadata?.version!==p.version)throw new Error("policy metadata identity is inconsistent");required(p.metadata?.displayName,"policy display name");required(p.metadata?.description,"policy description");required(p.metadata?.origin,"policy origin");if(!Array.isArray(p.supportedCategories)||!p.supportedCategories.length)throw new Error("policy supported categories are required");if(typeof p.evaluate!=="function"||typeof p.construct!=="function")throw new Error("policy must implement evaluate() and construct()"); }
const enc=encodeURIComponent;
export const stepIdentity=(d:string,v:string,s:string,refs:readonly string[])=>`candidate-step:${[d,v,s,...[...refs].sort(compareText)].map(enc).join(":")}`;
export const planIdentity=(p:Omit<CandidatePlan,"candidatePlanId">)=>`candidate-plan:${[p.provenance.contextId,p.provenance.intentSetId,p.provenance.constraintSetId,p.definitionIdentifier,p.definitionVersion,p.policyIdentifier,p.policyVersion,...[...p.objectiveReferences].sort(compareText),...p.evidenceReferences.map(r=>`${r.type}:${r.identifier}`).sort(compareText),...p.steps.map(s=>s.identifier).sort(compareText)].map(enc).join(":")}`;
export const setIdentity=(c:string,i:string,k:string,pol:readonly {identifier:string;version:string}[],plans:readonly string[])=>`candidate-plan-set:${[c,i,k,...pol.map(x=>`${x.identifier}@${x.version}`).sort(compareText),...plans.slice().sort(compareText)].map(enc).join(":")}`;
export const evidenceKey=(r:CandidatePlanEvidenceReference)=>`${r.type}:${r.identifier}`;
export function summary(defs:number,policies:readonly {identifier:string}[],plans:readonly CandidatePlan[]):CandidatePlanSummary { const uniq=(x:string[])=>new Set(x).size;return {definitionCount:defs,policyCount:policies.length,candidateCount:plans.length,objectiveCount:uniq(plans.flatMap(x=>[...x.objectiveReferences])),constraintCount:uniq(plans.flatMap(x=>[...x.constraintReferences])),stepCount:plans.reduce((n,x)=>n+x.steps.length,0),assumptionCount:plans.reduce((n,x)=>n+x.assumptions.length,0),dependencyCount:plans.reduce((n,x)=>n+x.dependencies.length,0),approvalRequirementCount:plans.reduce((n,x)=>n+x.approvalRequirements.length,0),completionConditionCount:plans.reduce((n,x)=>n+x.completionConditions.length,0),byCategory:Object.fromEntries(categories.map(c=>[c,plans.filter(x=>x.category===c).length])) as Record<CandidatePlanCategory,number>,byPolicy:Object.fromEntries(policies.map(p=>[p.identifier,plans.filter(x=>x.policyIdentifier===p.identifier).length] as [string,number]).sort((a,b)=>compareText(a[0],b[0])))}; }
export function createCandidatePlanSet(s:CandidatePlanSet):CandidatePlanSet { jsonCompatible(s,"candidate plan set");if(s.candidatePlanSetId!==setIdentity(s.contextId,s.intentSetId,s.constraintSetId,s.provenance.policies,s.candidates.map(x=>x.candidatePlanId)))throw new Error("invalid candidate plan set identity");if(JSON.stringify(s.summary)!==JSON.stringify(summary(s.summary.definitionCount,s.provenance.policies,s.candidates)))throw new Error("candidate plan summary is inconsistent");if(s.candidates.some((x,i)=>i&&comparePlans(s.candidates[i-1],x)>=0))throw new Error("candidate plans must use deterministic structural order");return deepFreeze(clone(s)); }
export function comparePlans(a:CandidatePlan,b:CandidatePlan):number { const ak=[a.objectiveReferences[0]??"",a.objectiveReferences.join("\0"),a.definitionIdentifier,a.definitionVersion,a.policyIdentifier,a.policyVersion,a.candidatePlanId],bk=[b.objectiveReferences[0]??"",b.objectiveReferences.join("\0"),b.definitionIdentifier,b.definitionVersion,b.policyIdentifier,b.policyVersion,b.candidatePlanId];for(let i=0;i<ak.length;i++){const n=compareText(ak[i],bk[i]);if(n)return n}return 0; }
