import { describe, expect, it } from "vitest";
import type { SituationAssessmentSet } from "../assessment";
import { ExecutiveContextEngine, ExecutiveContextRegistry, INITIAL_CONTEXT_POLICIES } from ".";

const assessmentSet = (): SituationAssessmentSet => ({ currentSnapshotId: "snapshot:b", situationSetId: "assessment-set:snapshot%3Ab:situation%3Aone,situation%3Atwo", assessments: [{ assessmentId: "assessment:one", metadata: { situationId: "situation:one", currentSnapshotId: "snapshot:b", policySet: [{ id: "assessment.alpha", version: "1.0.0" }] }, observations: [{ observationId: "observation:one", policyId: "assessment.alpha", policyVersion: "1.0.0", observationType: "contains_relationship", supportingEvidence: { domains: ["commitments"], commitmentEntityIds: ["commitment:a"], parentIds: ["commitment:parent"] }, originatingAttentionRecordIds: ["attention:a", "attention:b"], originatingSituationId: "situation:one" }] }, { assessmentId: "assessment:two", metadata: { situationId: "situation:two", currentSnapshotId: "snapshot:b", policySet: [{ id: "assessment.alpha", version: "1.0.0" }] }, observations: [{ observationId: "observation:two", policyId: "assessment.alpha", policyVersion: "1.0.0", observationType: "contains_entity", supportingEvidence: { sourceEntityIds: ["source:a"] }, originatingAttentionRecordIds: ["attention:c"], originatingSituationId: "situation:two" }] }], summary: { situations: 2, assessments: 2, observationCount: 2, observationsByPolicy: { "assessment.alpha": 2 }, observationsByType: { contains_entity: 1, contains_relationship: 1 } } });
const engine = () => new ExecutiveContextEngine(new ExecutiveContextRegistry(INITIAL_CONTEXT_POLICIES));

describe("Executive Context", () => {
  it("constructs canonical sections, typed statistics, and a count-only summary", () => { const result = engine().construct(assessmentSet()); expect(result.sections.map(section => section.sectionId)).toEqual(["assessments", "attention", "canonical-provenance", "situations", "structural-statistics"]); expect(result.sections.find(section => section.sectionId === "attention")?.entries).toEqual([{ attentionId: "attention:a" }, { attentionId: "attention:b" }, { attentionId: "attention:c" }]); expect(result.statistics.find(item => item.statisticId === "observations.total")?.value).toBe(2); expect(result.summary).toEqual({ sectionCount: 5, statisticCount: 8, situationCount: 2, assessmentCount: 2, attentionRecordCount: 3, observationCount: 2 }); });
  it("is replay safe, identity stable, ordered, JSON compatible, and deeply frozen", () => { const first = engine().construct(assessmentSet()); const replay = engine().construct(assessmentSet()); expect(first).toEqual(replay); expect(first.contextId).toBe(replay.contextId); expect(JSON.parse(JSON.stringify(first))).toEqual(first); expect(Object.isFrozen(first)).toBe(true); expect(Object.isFrozen(first.sections[0].entries)).toBe(true); expect(Object.isFrozen(first.canonicalProvenance.policies)).toBe(true); expect(() => (first.summary as { sectionCount: number }).sectionCount = 0).toThrow(); });
  it("makes registry order irrelevant and rejects duplicate or invalid policies", () => { const reverse = new ExecutiveContextEngine(new ExecutiveContextRegistry([...INITIAL_CONTEXT_POLICIES].reverse())).construct(assessmentSet()); expect(reverse).toEqual(engine().construct(assessmentSet())); const registry = new ExecutiveContextRegistry(); registry.register(INITIAL_CONTEXT_POLICIES[0]); expect(() => registry.register(INITIAL_CONTEXT_POLICIES[0])).toThrow(/duplicate/); expect(() => registry.register({ id: "invalid" } as never)).toThrow(); expect(Object.isFrozen(registry.metadata())).toBe(true); });
  it("fails atomically for malformed policy contributions", () => { const registry = new ExecutiveContextRegistry([{ id: "context.invalid", version: "1", description: "invalid", sectionId: "invalid", construct: () => ({ entries: [{}], statistics: [{ statisticId: "bad", value: Number.NaN, dimensions: {} }] }) }]); expect(() => new ExecutiveContextEngine(registry).construct(assessmentSet())).toThrow(/JSON-compatible/); });
});
