import type { SituationAssessmentSet } from "../assessment";
import type { ContextEvidence, ContextPolicy, ContextPolicyContribution, ContextStatistics } from "./types";
import { compareText, deepFreeze } from "./validation";

const statistic = (statisticId: string, value: number, dimensions: Readonly<Record<string, string>> = {}): ContextStatistics => ({ statisticId, value, dimensions });
const policy = (id: string, sectionId: string, description: string, construct: (set: SituationAssessmentSet) => ContextPolicyContribution): ContextPolicy => deepFreeze({ id, version: "1.0.0", sectionId, description, construct });
const observations = (set: SituationAssessmentSet) => set.assessments.flatMap(assessment => assessment.observations);
const evidenceStrings = (value: ContextEvidence, suffix: string): string[] => { if (Array.isArray(value)) return value.flatMap(item => evidenceStrings(item, suffix)); if (value && typeof value === "object") return Object.entries(value).flatMap(([key, child]) => key.toLowerCase().endsWith(suffix) ? (Array.isArray(child) ? child : [child]).filter((item): item is string => typeof item === "string") : evidenceStrings(child, suffix)); return []; };
const counted = (id: string, values: readonly string[]) => [...new Set(values)].sort(compareText).map(value => statistic(id, values.filter(item => item === value).length, { value }));

export const situationIndexPolicy = policy("context.situation-index", "situations", "Indexes assessed situations without ranking them.", set => ({ entries: set.assessments.map(a => ({ situationId: a.metadata.situationId, snapshotId: a.metadata.currentSnapshotId })), statistics: [] }));
export const assessmentIndexPolicy = policy("context.assessment-index", "assessments", "Indexes assessments and their observation identities.", set => ({ entries: set.assessments.map(a => ({ assessmentId: a.assessmentId, situationId: a.metadata.situationId, observationIds: a.observations.map(o => o.observationId) })), statistics: [] }));
export const attentionIndexPolicy = policy("context.attention-index", "attention", "Indexes originating Attention Records.", set => ({ entries: [...new Set(observations(set).flatMap(o => o.originatingAttentionRecordIds))].sort(compareText).map(attentionId => ({ attentionId })), statistics: [] }));
export const entityStatisticsPolicy = policy("context.entity-statistics", "structural-statistics", "Counts canonical entity references represented by evidence.", set => ({ entries: [], statistics: counted("entities.references", observations(set).flatMap(o => evidenceStrings(o.supportingEvidence, "entityids"))) }));
export const relationshipStatisticsPolicy = policy("context.relationship-statistics", "structural-statistics", "Counts explicit relationship references represented by evidence.", set => ({ entries: [], statistics: counted("relationships.references", observations(set).flatMap(o => evidenceStrings(o.supportingEvidence, "parentids"))) }));
export const domainStatisticsPolicy = policy("context.domain-statistics", "structural-statistics", "Counts explicitly represented assessment domains.", set => ({ entries: [], statistics: counted("domains.observations", observations(set).flatMap(o => evidenceStrings(o.supportingEvidence, "domains"))) }));
export const observationStatisticsPolicy = policy("context.observation-statistics", "structural-statistics", "Counts observations by structural type.", set => ({ entries: [], statistics: [statistic("observations.total", set.summary.observationCount), ...Object.entries(set.summary.observationsByType).map(([value, count]) => statistic("observations.by-type", count, { value }))] }));
export const policyStatisticsPolicy = policy("context.policy-statistics", "canonical-provenance", "Counts observations by assessment policy and exposes canonical provenance.", set => ({ entries: [{ snapshotId: set.currentSnapshotId, assessmentSetId: set.situationSetId }], statistics: Object.entries(set.summary.observationsByPolicy).map(([value, count]) => statistic("policies.observations", count, { value })) }));
export const INITIAL_CONTEXT_POLICIES = Object.freeze([assessmentIndexPolicy, attentionIndexPolicy, domainStatisticsPolicy, entityStatisticsPolicy, observationStatisticsPolicy, policyStatisticsPolicy, relationshipStatisticsPolicy, situationIndexPolicy]);
