import type { SituationAssessmentSet } from "../assessment";
import type { ContextPolicy, ContextPolicyMetadata, ExecutiveContext } from "./types";

export const compareText = (a: string, b: string): number => a < b ? -1 : a > b ? 1 : 0;
export function required(value: unknown, path: string): asserts value is string { if (typeof value !== "string" || value.trim() === "") throw new Error(`${path} must be a non-empty string`); }
export function clone<T>(value: T): T { if (Array.isArray(value)) return value.map(clone) as T; if (value && typeof value === "object") return Object.fromEntries(Object.entries(value).map(([key, child]) => [key, clone(child)])) as T; return value; }
export function deepFreeze<T>(value: T): T { if (value && typeof value === "object" && !Object.isFrozen(value)) { Object.values(value).forEach(deepFreeze); Object.freeze(value); } return value; }
export function jsonCompatible(value: unknown, path = "value", ancestors = new Set<object>()): void { if (value === null || typeof value === "string" || typeof value === "boolean" || (typeof value === "number" && Number.isFinite(value))) return; if (!value || typeof value !== "object" || ancestors.has(value as object) || (!Array.isArray(value) && Object.getPrototypeOf(value) !== Object.prototype)) throw new Error(`${path} must contain only JSON-compatible values`); ancestors.add(value as object); for (const [key, child] of Object.entries(value)) jsonCompatible(child, `${path}.${key}`, ancestors); ancestors.delete(value as object); }
export const policyMetadata = (policy: ContextPolicy): ContextPolicyMetadata => ({ id: policy.id, version: policy.version, description: policy.description, sectionId: policy.sectionId });
export function validatePolicy(policy: ContextPolicy): void { if (!policy || typeof policy !== "object") throw new Error("context policy must be an object"); required(policy.id, "context policy id"); required(policy.version, "context policy version"); required(policy.description, "context policy description"); required(policy.sectionId, "context policy sectionId"); if (typeof policy.construct !== "function") throw new Error("context policy must implement construct()"); }
const encode = (value: string) => encodeURIComponent(value);
export const contextIdentity = (snapshotId: string, assessmentSetId: string, sectionIds: readonly string[]): string => `executive-context:${encode(snapshotId)}:${encode(assessmentSetId)}:${[...sectionIds].sort(compareText).map(encode).join(",")}`;
export function validateAssessmentSet(value: SituationAssessmentSet): void { if (!value || typeof value !== "object" || !Array.isArray(value.assessments)) throw new Error("assessment set is required"); required(value.currentSnapshotId, "assessment set snapshot id"); required(value.situationSetId, "assessment set identifier"); jsonCompatible(value, "assessment set"); }
export function createExecutiveContext(candidate: ExecutiveContext): ExecutiveContext { jsonCompatible(candidate, "executive context"); required(candidate.snapshotId, "context snapshot id"); required(candidate.assessmentSetId, "context assessment set id"); const sectionIds = candidate.sections.map(s => s.sectionId); if (new Set(sectionIds).size !== sectionIds.length || sectionIds.some((id, i) => i > 0 && compareText(sectionIds[i - 1], id) >= 0)) throw new Error("context sections are duplicate or unordered"); for (const section of candidate.sections) { required(section.sectionId, "context section id"); const encoded = section.entries.map(entry => JSON.stringify(entry)); if (new Set(encoded).size !== encoded.length || encoded.some((entry, i) => i > 0 && compareText(encoded[i - 1], entry) >= 0)) throw new Error(`context section entries are duplicate or unordered: ${section.sectionId}`); }
  const keys = candidate.statistics.map(s => `${s.statisticId}:${JSON.stringify(s.dimensions)}`); if (new Set(keys).size !== keys.length || keys.some((key, i) => i > 0 && compareText(keys[i - 1], key) >= 0)) throw new Error("context statistics are duplicate or unordered"); if (candidate.contextId !== contextIdentity(candidate.snapshotId, candidate.assessmentSetId, sectionIds)) throw new Error("invalid executive context identity"); const summary = candidate.summary; const situations = candidate.sections.find(s => s.sectionId === "situations")?.entries.length ?? 0; const assessments = candidate.sections.find(s => s.sectionId === "assessments")?.entries.length ?? 0; const attention = candidate.sections.find(s => s.sectionId === "attention")?.entries.length ?? 0; const observations = candidate.statistics.find(s => s.statisticId === "observations.total")?.value ?? 0; if (summary.sectionCount !== candidate.sections.length || summary.statisticCount !== candidate.statistics.length || summary.situationCount !== situations || summary.assessmentCount !== assessments || summary.attentionRecordCount !== attention || summary.observationCount !== observations) throw new Error("context summary is inconsistent"); return deepFreeze(clone(candidate)); }
