import { describe, expect, it } from "vitest";
import { DeterministicExecutiveOperatingSystemRuntime } from "../runtime";
import { cancelledCommitmentScenario } from "../../../tests/scenarios/cancelled-commitment/scenario";
import { goldenRuntimeConfiguration } from "../../../tests/fixtures/eos/golden-projection-artifact-set";
import { ExecutiveCapabilityRouter, ImmutableExecutiveCapabilityRegistry } from ".";
import type { CapabilityRoutingInput, ExecutiveCapability } from ".";

const capability=(capabilityId:string,changes:Partial<ExecutiveCapability>={}):ExecutiveCapability=>({capabilityId,version:"1.0.0",owningModuleId:"test",displayName:capabilityId,description:"Neutral architectural fixture.",status:"AVAILABLE",supportedInvocationModes:["EXPLICIT","SCENARIO_REQUIRED","CONTEXT_TRIGGERED","DEPENDENCY"],requiredContextContract:"1.0.0",requiredContextConditions:[],prohibitedContextConditions:[],requiredScenarioReferences:[],requiredCapabilities:[],incompatibleCapabilities:[],executionClass:"READ_ONLY_ANALYSIS",ordering:{precedence:10},...changes});
const registry=(items:readonly ExecutiveCapability[])=>new ImmutableExecutiveCapabilityRegistry(items,["test"]);
const input=(items:readonly ExecutiveCapability[]= [capability("test.overview")]):CapabilityRoutingInput=>({context:{contextSnapshotId:"context:fixed",sourceStateSnapshotId:"state:fixed",contextContractVersion:"1.0.0",observedAt:"2026-07-28T09:00:00Z",conditions:[{conditionId:"HAS_CONFLICTS",rule:"conflict_count_greater_than_zero",evidenceIds:["conflict:1"]}],sourceState:{snapshotId:"state:fixed",lifecycleSnapshotId:"lifecycle:fixed",assemblyVersion:"1.0.0",canonicalContractVersion:"projection-artifact-v1"}},registry:registry(items),scenario:{scenarioId:"scenario.fixed",scenarioVersion:"1.0.0",references:["review"],requiredCapabilityIds:[],permittedCapabilityIds:items.map(x=>x.capabilityId),prohibitedCapabilityIds:[],permittedModuleIds:["test"],permittedExecutionClasses:["READ_ONLY_ANALYSIS"]},request:{requestId:"request:fixed",requestedCapabilityIds:["test.overview"],invocationMode:"EXPLICIT",source:"USER",scenarioId:"scenario.fixed",contextSnapshotId:"context:fixed"},policy:{policyId:"routing.fixed",version:"1.0.0",permittedInvocationModes:["EXPLICIT","SCENARIO_REQUIRED","CONTEXT_TRIGGERED","DEPENDENCY"],allowCapabilityIds:[],denyCapabilityIds:[],allowExperimental:false,allowDeprecated:false,requireExplicitRequest:false,maximumCapabilityCount:10,incompatibilityBehaviour:"PUBLISH_CONFLICT",contextRules:[]}});

describe("immutable capability registry",()=>{
 it("rejects duplicates, unresolved references, cycles, and contradictory compatibility",()=>{expect(()=>registry([capability("test.overview"),capability("test.overview")])).toThrow(/duplicate/);expect(()=>registry([capability("test.overview",{requiredCapabilities:["test.missing"]})])).toThrow(/reference/);expect(()=>registry([capability("test.alpha",{requiredCapabilities:["test.beta"]}),capability("test.beta",{requiredCapabilities:["test.alpha"]})])).toThrow(/circular/);expect(()=>registry([capability("test.alpha",{requiredCapabilities:["test.beta"],incompatibleCapabilities:["test.beta"]}),capability("test.beta")])).toThrow(/contradictory/);});
 it("has canonical identity and recursively immutable descriptors independent of insertion order",()=>{const a=registry([capability("test.beta"),capability("test.alpha")]),b=registry([capability("test.alpha"),capability("test.beta")]);expect(a.registryIdentity).toBe(b.registryIdentity);expect(a.capabilities.map(x=>x.capabilityId)).toEqual(["test.alpha","test.beta"]);expect(Object.isFrozen(a.capabilities[0].ordering)).toBe(true);});
});
describe("governed deterministic capability routing",()=>{
 it("preserves requested, eligible, permitted, and routable as distinct facts",()=>{const raw=input([capability("test.overview")]);const governed={...raw,scenario:{...raw.scenario,prohibitedCapabilityIds:["test.overview"]}};const result=new ExecutiveCapabilityRouter().route(governed);expect(result.outcome).toBe("success");if(result.outcome==="success")expect(result.plan.eligibilityRecords[0]).toMatchObject({requested:true,eligible:true,permitted:false,routable:false,prohibitions:["SCENARIO_PROHIBITION"]});});
 it("expands dependencies before dependants and records governing evidence",()=>{const raw=input([capability("test.dependency"),capability("test.overview",{requiredCapabilities:["test.dependency"]})]);const result=new ExecutiveCapabilityRouter().route(raw);expect(result.outcome).toBe("success");if(result.outcome==="success"){expect(result.plan.orderedInvocationCandidates).toEqual(["test.dependency","test.overview"]);expect(result.plan.eligibilityRecords.find(x=>x.capabilityId==="test.dependency")?.invocationAuthorities[0]).toMatchObject({mode:"DEPENDENCY",source:"CAPABILITY_DEPENDENCY",authorityId:"test.overview"});}});
 it("publishes incompatibility without hidden preference",()=>{const raw=input([capability("test.overview",{incompatibleCapabilities:["test.conflict-review"]}),capability("test.conflict-review")]);const governed={...raw,request:{...raw.request,requestedCapabilityIds:["test.overview","test.conflict-review"]}};const result=new ExecutiveCapabilityRouter().route(governed);expect(result.outcome).toBe("success");if(result.outcome==="success"){expect(result.plan.routingConflicts[0].type).toBe("INCOMPATIBLE_CAPABILITIES");expect(result.plan.orderedInvocationCandidates).toEqual(["test.conflict-review","test.overview"]);}});
 it("uses only declared context rules and replays identically without clock or inference fields",()=>{const raw=input([capability("test.overview"),capability("test.conflict-review")]);const governed={...raw,policy:{...raw.policy,contextRules:[{ruleId:"rule.conflicts",version:"1.0.0",targetCapabilityId:"test.conflict-review",requiredConditionIds:["HAS_CONFLICTS"],prohibitedConditionIds:[],scenarioIds:[],operatingModes:[],precedence:1}]}};const router=new ExecutiveCapabilityRouter(),a=router.route(governed),b=router.route(governed);expect(a).toEqual(b);expect(JSON.stringify(a)).not.toMatch(/priority|urgency|importance|recommendation|confidence|natural.language|model/i);});
 it("fails atomically for unresolved explicit identifiers",()=>{const raw=input(),result=new ExecutiveCapabilityRouter().route({...raw,request:{...raw.request,requestedCapabilityIds:["test.missing"]}});expect(result).toMatchObject({outcome:"failure",code:"INVOCATION_REQUEST_FAILURE"});expect("plan" in result).toBe(false);});
 it("publishes a recursively immutable plan with stable identity",()=>{const router=new ExecutiveCapabilityRouter(),first=router.route(input()),second=router.route(input());expect(first).toEqual(second);if(first.outcome==="success"){expect(first.plan.routingPlanId).toBe(second.outcome==="success"?second.plan.routingPlanId:"");expect(Object.isFrozen(first.plan.eligibilityRecords[0].evidence)).toBe(true);}});
});
describe("additive EOS integration",()=>{it("publishes a routing plan without changing the legacy trace or executing a capability",()=>{const raw=input();const runtime=new DeterministicExecutiveOperatingSystemRuntime();const legacy=runtime.run({projectionArtifacts:cancelledCommitmentScenario.projectionArtifacts,configuration:goldenRuntimeConfiguration});const routed=runtime.run({projectionArtifacts:cancelledCommitmentScenario.projectionArtifacts,configuration:goldenRuntimeConfiguration,capabilityRouting:raw});expect(routed.capabilityRoutingPlan?.orderedInvocationCandidates).toEqual(["test.overview"]);expect(routed.trace).toEqual(legacy.trace);expect(routed.context).toEqual(legacy.context);expect(legacy.capabilityRoutingPlan).toBeUndefined();});});
