import { describe,expect,it } from "vitest";
import type { GovernedActionProposal,GovernedActionProposalSet } from "../proposal";
import { ExecutiveCapabilityRegistry,ExecutiveCapabilityRouter,ExecutiveCapabilityRoutingError } from ".";
const proposal=(overrides:Partial<GovernedActionProposal>={}):GovernedActionProposal=>({proposalId:"proposal:1",definitionIdentifier:"definition",definitionVersion:"1",policyIdentifier:"proposal-policy",policyVersion:"1",proposalKind:"consider_candidate",proposalScope:"single_candidate",proposalStatus:"ready_for_human_review",reasonCode:"proposal-ready-for-human-review",candidatePlanIds:["candidate:1"],reasoningObservationIds:[],reasoningQuestionIds:[],reasoningBoundaryIds:[],conditions:[],authorityRequirements:[],evidenceRequirements:[],unresolvedQuestions:[],boundaries:[],payload:{description:"bounded recommendation"},provenance:{contextId:"context:legacy",intentSetId:"intent:1",constraintSetId:"constraints:1",candidatePlanSetId:"plans:1",evaluatedCandidatePlanSetId:"evaluations:1",comparisonSetId:"comparison:1",reasoningRecordId:"reasoning:1",definitionIdentifier:"definition",definitionVersion:"1",policyIdentifier:"proposal-policy",policyVersion:"1",origin:"test",candidatePlanIds:["candidate:1"],evaluationIds:[],comparisonIds:[],observationIds:[],reasoningQuestionIds:[],reasoningBoundaryIds:[],evidenceReferences:[],governanceReferences:[],status:"ready_for_human_review",reasonCode:"proposal-ready-for-human-review"},...overrides});
const set=(proposals:readonly GovernedActionProposal[]=[proposal()]):GovernedActionProposalSet=>({proposalSetId:"governed-action-proposal-set:test",executiveStateSnapshotId:"state:1",executiveContextId:"executive-context:1",deliberationContextId:"deliberation:1",contextId:"context:legacy",intentSetId:"intent:1",constraintSetId:"constraints:1",candidatePlanSetId:"plans:1",evaluatedCandidatePlanSetId:"evaluations:1",comparisonSetId:"comparison:1",reasoningRecordId:"reasoning:1",proposals,summary:{} as never,activePolicies:[],definitions:[],provenance:{proposalIds:proposals.map(x=>x.proposalId)}});
const capability={capabilityId:"review",capabilityVersion:"1",status:"active" as const,dependencyCapabilityIds:[],supportedActionClasses:["consider_candidate" as const]};
const scenario={scenarioId:"canonical",capabilityIds:["review"]},policy={policyId:"constitutional",policyVersion:"1",eligibleCapabilityIds:["review"]},rule={routingRuleId:"consider-review",capabilityId:"review",actionClasses:["consider_candidate" as const]};
const router=()=>new ExecutiveCapabilityRouter(new ExecutiveCapabilityRegistry([capability],[scenario],[policy],[rule]));
describe("ExecutiveCapabilityRouter governed proposal eligibility",()=>{
 it("publishes one replay-stable deeply immutable eligibility plan with complete lineage",()=>{const first=router().route({proposalSet:set(),scenario,policy}),replay=router().route({proposalSet:set(),scenario,policy});expect(replay).toEqual(first);expect(first).toMatchObject({proposalSetId:"governed-action-proposal-set:test",executiveStateSnapshotId:"state:1",executiveContextId:"executive-context:1",deliberationContextId:"deliberation:1",reasoningRecordId:"reasoning:1",metadata:{owner:"ExecutiveCapabilityRouter",semantics:"eligibility_only",approvalGranted:false,invocationPerformed:false,executionPerformed:false}});expect(first.routedCapabilities).toEqual([expect.objectContaining({proposalId:"proposal:1",capabilityId:"review"})]);expect(Object.isFrozen(first)).toBe(true);expect(Object.isFrozen(first.proposalRoutings[0]?.authorityRequirements)).toBe(true)});
 it("preserves approval and authority requirements without granting approval",()=>{const p=proposal({conditions:[{conditionId:"approval:1",conditionType:"approval_required",conditionStatus:"unresolved",sourceCanonicalReference:"governance:1",candidatePlanIds:[],requiredEvidenceReferences:[],requiredAuthorityReferences:["human"],reasonCode:"approval-required-before-execution",policyIdentifier:"proposal-policy",policyVersion:"1",provenance:proposal().provenance}],authorityRequirements:[{authorityRequirementId:"authority:1",authorityType:"human_executive",sourceGovernanceReference:"human",proposalId:"proposal:1",candidatePlanIds:[],requirementStatus:"unresolved",reasonCode:"authority-confirmation-required",provenance:proposal().provenance}]});const result=router().route({proposalSet:set([p]),scenario,policy});expect(result.proposalRoutings[0]).toMatchObject({approvalRequired:true,authorityRequirements:[{authorityType:"human_executive",requirementStatus:"unresolved"}]});expect(result.metadata.approvalGranted).toBe(false)});
 it("classifies inactive, prohibited, unsupported and constitutionally blocked capabilities deterministically",()=>{const capabilities=[capability,{...capability,capabilityId:"inactive",status:"inactive" as const},{...capability,capabilityId:"denied"},{...capability,capabilityId:"unsupported",supportedActionClasses:["defer_pending_evidence" as const]}],s={scenarioId:"all",capabilityIds:capabilities.map(x=>x.capabilityId)},p={policyId:"limited",policyVersion:"1",eligibleCapabilityIds:["review","inactive","unsupported"]},rules=capabilities.map(x=>({...rule,routingRuleId:`rule:${x.capabilityId}`,capabilityId:x.capabilityId}));const result=new ExecutiveCapabilityRouter(new ExecutiveCapabilityRegistry(capabilities,[s],[p],rules)).route({proposalSet:set(),scenario:s,policy:p});expect(result.ineligibleCapabilities.map(x=>[x.capabilityId,x.reason])).toEqual([["denied","not_permitted"],["inactive","inactive"],["unsupported","unsupported_action"]])});
 it("rejects missing, duplicate and discontinuous proposal publications with typed failures",()=>{expect(()=>router().route({proposalSet:undefined as never,scenario,policy})).toThrowError(expect.objectContaining({code:"MISSING_PROPOSAL_SET"}));expect(()=>router().route({proposalSet:set([proposal(),proposal()]),scenario,policy})).toThrowError(expect.objectContaining({code:"DUPLICATE_PROPOSAL_ID"}));const bad=set();(bad as {reasoningRecordId:string}).reasoningRecordId="other";expect(()=>router().route({proposalSet:bad,scenario,policy})).toThrow(ExecutiveCapabilityRoutingError)});
 it("rejects duplicate capability identity and malformed matrix entries",()=>{expect(()=>new ExecutiveCapabilityRegistry([capability,capability],[],[],[])).toThrowError(expect.objectContaining({code:"DUPLICATE_CAPABILITY_ID"}));expect(()=>new ExecutiveCapabilityRegistry([capability],[],[],[{...rule,capabilityId:"unknown"}])).toThrowError(expect.objectContaining({code:"INVALID_CAPABILITY_MATRIX_ENTRY"}))});
});
