import { canonical, compareCodeUnits, deepFreeze, stableIdentity } from "./registry";
import { CAPABILITY_ROUTER_CONTRACT_VERSION, CAPABILITY_ROUTER_IMPLEMENTATION_VERSION } from "./types";
import type { CapabilityEligibilityRecord, CapabilityInvocationMode, CapabilityRoutingFailure, CapabilityRoutingInput, CapabilityRoutingPlan, CapabilityRoutingResult, InvocationAuthority, RoutingConflict } from "./types";

const fail=(input:Partial<CapabilityRoutingInput>,code:CapabilityRoutingFailure["code"],stage:string,rule:string,message:string):CapabilityRoutingFailure=>deepFreeze({outcome:"failure",code,stage,governingRule:rule,message,identities:{...(input.context?.contextSnapshotId?{contextSnapshotId:input.context.contextSnapshotId}:{}),...(input.registry?.registryIdentity?{registryIdentity:input.registry.registryIdentity}:{}),...(input.scenario?.scenarioId?{scenarioId:input.scenario.scenarioId}:{}),...(input.request?.requestId?{requestId:input.request.requestId}:{}),...(input.policy?.policyId?{policyId:input.policy.policyId}:{})}});
const unique=(items:readonly string[])=>[...new Set(items)].sort(compareCodeUnits);
const validId=(v:unknown)=>typeof v==="string"&&/^[a-z][a-z0-9-]*\.[a-z][a-z0-9-]*$/.test(v);
const policyIdentity=(policy:CapabilityRoutingInput["policy"])=>stableIdentity("routing-policy",policy);

/** Pure governed routing. It never imports, calls, or executes an executive module. */
export class ExecutiveCapabilityRouter {
  route(input:CapabilityRoutingInput):CapabilityRoutingResult {
    if(!input?.context||!input.context.contextSnapshotId||input.context.sourceStateSnapshotId!==input.context.sourceState?.snapshotId||!/^\d+\.\d+\.\d+$/.test(input.context.contextContractVersion)||!Array.isArray(input.context.conditions)) return fail(input,"CONTEXT_VALIDATION_FAILURE","input_validation","canonical_executive_context","context snapshot identity, contract, conditions, and source-state linkage are required");
    if(!input.registry||!input.registry.registryIdentity||!Array.isArray(input.registry.capabilities)) return fail(input,"REGISTRY_VALIDATION_FAILURE","registry_validation","immutable_validated_registry","a validated capability registry is required");
    const request=input.request, scenario=input.scenario, policy=input.policy;
    if(!request?.requestId||request.invocationMode!=="EXPLICIT"||request.scenarioId!==scenario?.scenarioId||request.contextSnapshotId!==input.context.contextSnapshotId||!Array.isArray(request.requestedCapabilityIds)||request.requestedCapabilityIds.some(id=>!validId(id)||!input.registry.get(id))) return fail(input,"INVOCATION_REQUEST_FAILURE","input_validation","registered_stable_capability_identifiers","request identities must link to context and scenario and resolve in the registry");
    if(!scenario?.scenarioId||!scenario.scenarioVersion||![scenario.requiredCapabilityIds,scenario.permittedCapabilityIds,scenario.prohibitedCapabilityIds,scenario.references,scenario.permittedModuleIds,scenario.permittedExecutionClasses].every(value=>Array.isArray(value))) return fail(input,"SCENARIO_COMPATIBILITY_FAILURE","input_validation","explicit_scenario_authority","scenario routing authority is malformed");
    const overlap=scenario.requiredCapabilityIds.find(id=>scenario.prohibitedCapabilityIds.includes(id));
    if(overlap) return fail(input,"SCENARIO_COMPATIBILITY_FAILURE","input_validation","non_contradictory_scenario_authority",`scenario both requires and prohibits ${overlap}`);
    if(!policy?.policyId||!/^\d+\.\d+\.\d+$/.test(policy.version)||policy.maximumCapabilityCount<1||policy.allowCapabilityIds.some((id:string)=>policy.denyCapabilityIds.includes(id))) return fail(input,"ROUTING_POLICY_FAILURE","input_validation","valid_non_contradictory_versioned_policy","routing policy is malformed or contradictory");
    const conditions=new Set(input.context.conditions.map(c=>c.conditionId)); const authorities=new Map<string,InvocationAuthority[]>();
    const add=(id:string,a:InvocationAuthority)=>authorities.set(id,[...(authorities.get(id)??[]),a]);
    request.requestedCapabilityIds.forEach(id=>add(id,{mode:"EXPLICIT",source:request.source,authorityId:request.requestId}));
    scenario.requiredCapabilityIds.forEach(id=>add(id,{mode:"SCENARIO_REQUIRED",source:"EXECUTIVE_SCENARIO",authorityId:`${scenario.scenarioId}@${scenario.scenarioVersion}`}));
    for(const rule of [...policy.contextRules].sort((a,b)=>a.precedence-b.precedence||compareCodeUnits(a.ruleId,b.ruleId))) if(rule.requiredConditionIds.every(id=>conditions.has(id))&&rule.prohibitedConditionIds.every(id=>!conditions.has(id))&&(!rule.scenarioIds.length||rule.scenarioIds.includes(scenario.scenarioId))&&(!rule.operatingModes.length||Boolean(scenario.operatingMode&&rule.operatingModes.includes(scenario.operatingMode)))) add(rule.targetCapabilityId,{mode:"CONTEXT_TRIGGERED",source:"DETERMINISTIC_CONTEXT_RULE",authorityId:`${rule.ruleId}@${rule.version}`});
    const roots=[...authorities.keys()]; const expand=(id:string):void=>{ const capability=input.registry.get(id); if(!capability)return; for(const dependency of capability.requiredCapabilities){add(dependency,{mode:"DEPENDENCY",source:"CAPABILITY_DEPENDENCY",authorityId:id});expand(dependency);} }; roots.forEach(expand);
    const records:CapabilityEligibilityRecord[]=[];
    for(const capability of input.registry.capabilities){ const auth=(authorities.get(capability.capabilityId)??[]).sort((a,b)=>compareCodeUnits(`${a.mode}:${a.authorityId}`,`${b.mode}:${b.authorityId}`)); const unsatisfied:string[]=[];
      if(!auth.length) unsatisfied.push("NO_INVOCATION_AUTHORITY"); if(capability.status==="DISABLED") unsatisfied.push("CAPABILITY_DISABLED"); if(capability.requiredContextContract!==input.context.contextContractVersion) unsatisfied.push("CONTEXT_CONTRACT_MISMATCH");
      capability.requiredContextConditions.filter((id:string)=>!conditions.has(id)).forEach((id:string)=>unsatisfied.push(`MISSING_CONTEXT_CONDITION:${id}`)); capability.prohibitedContextConditions.filter((id:string)=>conditions.has(id)).forEach((id:string)=>unsatisfied.push(`PROHIBITED_CONTEXT_CONDITION:${id}`)); capability.requiredScenarioReferences.filter((id:string)=>!scenario.references.includes(id)).forEach((id:string)=>unsatisfied.push(`MISSING_SCENARIO_REFERENCE:${id}`)); auth.filter(a=>!capability.supportedInvocationModes.includes(a.mode)).forEach(a=>unsatisfied.push(`UNSUPPORTED_INVOCATION_MODE:${a.mode}`));
      const eligible=unsatisfied.length===0; const prohibitions:string[]=[]; if(scenario.prohibitedCapabilityIds.includes(capability.capabilityId))prohibitions.push("SCENARIO_PROHIBITION"); if(scenario.permittedCapabilityIds.length&&!scenario.permittedCapabilityIds.includes(capability.capabilityId)&&!scenario.requiredCapabilityIds.includes(capability.capabilityId))prohibitions.push("NOT_SCENARIO_PERMITTED"); if(scenario.permittedModuleIds.length&&!scenario.permittedModuleIds.includes(capability.owningModuleId))prohibitions.push("MODULE_NOT_PERMITTED"); if(scenario.permittedExecutionClasses.length&&!scenario.permittedExecutionClasses.includes(capability.executionClass))prohibitions.push("EXECUTION_CLASS_NOT_PERMITTED"); if(policy.denyCapabilityIds.includes(capability.capabilityId))prohibitions.push("POLICY_DENYLIST"); if(policy.allowCapabilityIds.length&&!policy.allowCapabilityIds.includes(capability.capabilityId))prohibitions.push("POLICY_ALLOWLIST"); if(capability.status==="EXPERIMENTAL"&&!policy.allowExperimental)prohibitions.push("EXPERIMENTAL_NOT_PERMITTED"); if(capability.status==="DEPRECATED"&&!policy.allowDeprecated)prohibitions.push("DEPRECATED_NOT_PERMITTED"); if(auth.some(a=>!policy.permittedInvocationModes.includes(a.mode)))prohibitions.push("INVOCATION_MODE_NOT_PERMITTED");
      const permitted=prohibitions.length===0; records.push({capabilityId:capability.capabilityId,capabilityVersion:capability.version,registryIdentity:input.registry.registryIdentity,requested:request.requestedCapabilityIds.includes(capability.capabilityId),eligible,permitted,routable:eligible&&permitted,invocationAuthorities:auth,satisfiedRequirements:unique([...(auth.length?["INVOCATION_AUTHORITY_PRESENT"]:[]),...capability.requiredContextConditions.filter((id:string)=>conditions.has(id)).map((id:string)=>`CONTEXT_CONDITION:${id}`)]),unsatisfiedRequirements:unique(unsatisfied),prohibitions:unique(prohibitions),dependencies:capability.requiredCapabilities,incompatibilities:capability.incompatibleCapabilities,evidence:unique([input.context.contextSnapshotId,scenario.scenarioId,...auth.map(a=>a.authorityId)])}); }
    const routable=records.filter(r=>r.routable); const conflicts:RoutingConflict[]=[];
    for(const record of routable)for(const peer of record.incompatibilities)if(routable.some(r=>r.capabilityId===peer)){const ids=[record.capabilityId,peer].sort(compareCodeUnits),conflictId=stableIdentity("routing-conflict",ids);if(!conflicts.some(c=>c.conflictId===conflictId))conflicts.push({conflictId,type:"INCOMPATIBLE_CAPABILITIES",capabilityIds:ids,governingRules:["declared_capability_incompatibility"],sourceAuthorities:unique(ids.flatMap(id=>authorities.get(id)?.map(a=>a.authorityId)??[])),evidence:ids,message:`routable capabilities are explicitly incompatible: ${ids.join(" and ")}`});}
    for(const record of routable)for(const dependency of record.dependencies){const dep=records.find(r=>r.capabilityId===dependency)!;if(!dep.routable)conflicts.push({conflictId:stableIdentity("routing-conflict",[record.capabilityId,dependency]),type:dep.permitted?"MISSING_DEPENDENCY":"PROHIBITED_DEPENDENCY",capabilityIds:[record.capabilityId,dependency],governingRules:["all_dependencies_must_be_routable"],sourceAuthorities:record.invocationAuthorities.map(a=>a.authorityId),evidence:dep.prohibitions,message:`dependency ${dependency} is not routable for ${record.capabilityId}`});}
    conflicts.sort((a,b)=>compareCodeUnits(a.conflictId,b.conflictId)); if(conflicts.length&&policy.incompatibilityBehaviour==="FAIL")return fail(input,"ROUTING_CONFLICT_FAILURE","compatibility_evaluation","explicit_conflict_policy",conflicts[0].message);
    const routableIds=new Set(routable.map(r=>r.capabilityId)); const ordered:string[]=[],seen=new Set<string>(); const visit=(id:string):void=>{if(seen.has(id)||!routableIds.has(id))return; const c=input.registry.get(id)!; [...c.requiredCapabilities].sort(compareCodeUnits).forEach(visit);seen.add(id);ordered.push(id);}; [...routable].sort((a,b)=>input.registry.get(a.capabilityId)!.ordering.precedence-input.registry.get(b.capabilityId)!.ordering.precedence||compareCodeUnits(a.capabilityId,b.capabilityId)).forEach(r=>visit(r.capabilityId));
    if(ordered.length>policy.maximumCapabilityCount)return fail(input,"ROUTING_POLICY_FAILURE","canonical_ordering","maximum_capability_count",`routing candidates exceed maximum ${policy.maximumCapabilityCount}`);
    const base={contextSnapshotId:input.context.contextSnapshotId,stateSnapshotId:input.context.sourceStateSnapshotId,scenarioId:scenario.scenarioId,scenarioVersion:scenario.scenarioVersion,registryIdentity:input.registry.registryIdentity,routingPolicyIdentity:policyIdentity(policy),invocationRequestId:request.requestId,explicitReferenceTime:input.explicitReferenceTime,contractVersion:CAPABILITY_ROUTER_CONTRACT_VERSION,implementationVersion:CAPABILITY_ROUTER_IMPLEMENTATION_VERSION,records,ordered,conflicts};
    let routingPlanId:string;try{routingPlanId=stableIdentity("capability-routing-plan",base)}catch{return fail(input,"ROUTING_IDENTITY_FAILURE","routing_identity","canonical_json_identity","routing identity could not be produced");}
    const plan:CapabilityRoutingPlan={routingPlanId,contextSnapshotId:base.contextSnapshotId,stateSnapshotId:base.stateSnapshotId,scenarioId:base.scenarioId,registryIdentity:base.registryIdentity,routingPolicyIdentity:base.routingPolicyIdentity,invocationRequestId:base.invocationRequestId,eligibilityRecords:records,eligibleCapabilities:records.filter(r=>r.eligible).map(r=>r.capabilityId),permittedCapabilities:records.filter(r=>r.permitted).map(r=>r.capabilityId),orderedInvocationCandidates:ordered,excludedCapabilities:records.filter(r=>!r.routable).map(r=>r.capabilityId),unresolvedCapabilities:records.filter(r=>r.eligible&&r.permitted&&!r.routable).map(r=>r.capabilityId),dependencyGraph:records.filter(r=>r.dependencies.length).map(r=>({capabilityId:r.capabilityId,requiredCapabilityIds:r.dependencies})),routingConflicts:conflicts,evidence:unique([input.context.contextSnapshotId,input.registry.registryIdentity,scenario.scenarioId,request.requestId,policy.policyId]),routingMetadata:{contractVersion:CAPABILITY_ROUTER_CONTRACT_VERSION,implementationVersion:CAPABILITY_ROUTER_IMPLEMENTATION_VERSION}};
    if(!plan.routingPlanId||canonical(plan).includes("undefined"))return fail(input,"ROUTING_PLAN_VALIDATION_FAILURE","plan_validation","canonical_complete_plan","routing plan failed validation"); return deepFreeze({outcome:"success",plan});
  }
}
