import { describe, expect, it } from "vitest";
import type { AttentionRecord } from "../attention";
import type { ExecutiveSituationSet } from "../situations";
import { ExecutiveSituationAssessmentEngine, INITIAL_SITUATION_ASSESSMENT_POLICIES, SituationAssessmentRegistry } from ".";

const record = (attentionId: string, domain: AttentionRecord["domain"], entityId: string, code: string): AttentionRecord => ({ attentionId, domain, entityId, changeType: "modified", previousSnapshotId: "previous", currentSnapshotId: "current", previous: domain === "commitments" ? { id: entityId, title: entityId, kind: "meeting", status: "scheduled", roleIds: [], projectIds: [], startsAt: "2026-07-27T09:00:00Z" } : { id: entityId, kind: "calendar", status: "available" }, current: domain === "commitments" ? { id: entityId, title: entityId, kind: "meeting", status: code.includes("cancelled") ? "cancelled" : "scheduled", roleIds: [], projectIds: [], startsAt: "2026-07-27T10:00:00Z" } : { id: entityId, kind: "calendar", status: "unavailable" }, policy: { id: `attention.${attentionId}`, version: "1.0.0" }, reason: { code, message: code, evidence: [] } } as AttentionRecord);
const set = (): ExecutiveSituationSet => ({ currentSnapshotId: "current", queueId: "queue", situations: [{ situationId: "situation:one", currentSnapshotId: "current", formationPolicy: { id: "situation.test", version: "1.0.0" }, memberships: [record("attention:a", "commitments", "commitment:a", "commitment.status.changed-to-cancelled"), record("attention:b", "commitments", "commitment:a", "commitment.start-time.changed")].map(attentionRecord => ({ formationPolicyId: "situation.test", formationPolicyVersion: "1.0.0", reason: { code: "test", evidence: {} }, attentionRecord })) }, { situationId: "situation:two", currentSnapshotId: "current", formationPolicy: { id: "situation.test", version: "1.0.0" }, memberships: [{ formationPolicyId: "situation.test", formationPolicyVersion: "1.0.0", reason: { code: "test", evidence: {} }, attentionRecord: record("attention:c", "sources", "source:a", "source.availability.changed-to-unavailable") }] }], summary: { attentionRecords: 3, executiveSituations: 2, singletonCount: 1, multiRecordCount: 1, recordsByPolicy: { "situation.test": 3 } } });

describe("Executive Situation Assessment", () => {
  it("executes multiple structural policies and produces a consistent summary", () => { const result = new ExecutiveSituationAssessmentEngine(new SituationAssessmentRegistry(INITIAL_SITUATION_ASSESSMENT_POLICIES)).assess(set()); expect(result.assessments).toHaveLength(2); expect(result.summary).toEqual({ situations: 2, assessments: 2, observationCount: 3, observationsByPolicy: { "assessment.contains-cancelled-commitment": 1, "assessment.contains-schedule-modification": 1, "assessment.contains-source-availability-transition": 1 }, observationsByType: { contains_cancelled_commitment: 1, contains_schedule_modification: 1, contains_source_availability_transition: 1 } }); expect(result.assessments[0].observations.map(o => o.observationType)).toEqual(["contains_cancelled_commitment", "contains_schedule_modification"]); });
  it("is replay safe, identity stable, deterministically ordered, and deeply frozen", () => { const engine = new ExecutiveSituationAssessmentEngine(new SituationAssessmentRegistry([...INITIAL_SITUATION_ASSESSMENT_POLICIES].reverse())); const first = engine.assess(set()); const replay = engine.assess(set()); expect(first).toEqual(replay); expect(first.assessments.map(a => a.metadata.situationId)).toEqual(["situation:one", "situation:two"]); expect(Object.isFrozen(first)).toBe(true); expect(Object.isFrozen(first.assessments[0].observations[0].supportingEvidence)).toBe(true); expect(() => (first.summary as { assessments: number }).assessments = 99).toThrow(); });
  it("validates registry entries and rejects duplicate identifiers", () => { const registry = new SituationAssessmentRegistry(); registry.register(INITIAL_SITUATION_ASSESSMENT_POLICIES[0]); expect(() => registry.register(INITIAL_SITUATION_ASSESSMENT_POLICIES[0])).toThrow(/duplicate/); expect(() => registry.register({ id: "invalid", version: "1", observationType: "invalid", description: "invalid" } as never)).toThrow(/implement/); expect(Object.isFrozen(registry.metadata())).toBe(true); });
  it("fails atomically when an applicable policy emits malformed output", () => { const registry = new SituationAssessmentRegistry([{ id: "assessment.invalid", version: "1.0.0", observationType: "invalid", description: "Invalid test policy.", applies: () => true, observe: () => [] }]); expect(() => new ExecutiveSituationAssessmentEngine(registry).assess(set())).toThrow(/returned no observations/); });
});
