import type { AttentionRecord } from "../attention";
import type { ExecutiveSituation } from "../situations";
import type { AssessmentEvidenceValue, SituationAssessmentPolicy } from "./types";
import { compareText, deepFreeze } from "./validation";

type Match = { readonly records: readonly AttentionRecord[]; readonly evidence: Readonly<Record<string, AssessmentEvidenceValue>> };
const records = (situation: ExecutiveSituation): readonly AttentionRecord[] => situation.memberships.map(m => m.attentionRecord);
const ids = (matching: readonly AttentionRecord[]) => matching.map(record => record.attentionId).sort(compareText);
const make = (id: string, observationType: string, description: string, match: (situation: ExecutiveSituation) => Match | undefined): SituationAssessmentPolicy => deepFreeze({
  id, version: "1.0.0", observationType, description,
  applies(situation) { return match(situation) !== undefined; },
  observe(situation) { const result = match(situation); return result ? [{ supportingEvidence: result.evidence, originatingAttentionRecordIds: ids(result.records) }] : []; },
});
const byReason = (code: string, evidence: (matching: readonly AttentionRecord[]) => Readonly<Record<string, AssessmentEvidenceValue>>) => (situation: ExecutiveSituation): Match | undefined => { const matching = records(situation).filter(record => record.reason.code === code); return matching.length ? { records: matching, evidence: evidence(matching) } : undefined; };

export const containsCancelledCommitmentPolicy = make("assessment.contains-cancelled-commitment", "contains_cancelled_commitment", "Observes an explicit commitment transition to cancelled.", byReason("commitment.status.changed-to-cancelled", matching => ({ commitmentEntityIds: matching.map(r => r.entityId ?? null).sort((a, b) => compareText(a ?? "", b ?? "")) })));
export const containsScheduleModificationPolicy = make("assessment.contains-schedule-modification", "contains_schedule_modification", "Observes an explicit commitment start-time modification.", byReason("commitment.start-time.changed", matching => ({ commitmentEntityIds: matching.map(r => r.entityId ?? null).sort((a, b) => compareText(a ?? "", b ?? "")) })));
export const containsSourceAvailabilityTransitionPolicy = make("assessment.contains-source-availability-transition", "contains_source_availability_transition", "Observes an explicit source availability transition.", byReason("source.availability.changed-to-unavailable", matching => ({ sourceEntityIds: matching.map(r => r.entityId ?? null).sort((a, b) => compareText(a ?? "", b ?? "")) })));
export const containsMultipleAttentionDomainsPolicy = make("assessment.contains-multiple-attention-domains", "contains_multiple_attention_domains", "Observes more than one represented Attention domain.", situation => { const all = records(situation); const domains = [...new Set(all.map(record => record.domain))].sort(compareText); return domains.length > 1 ? { records: all, evidence: { domains, domainCount: domains.length } } : undefined; });
export const containsExplicitParentRelationshipPolicy = make("assessment.contains-explicit-parent-relationship", "contains_explicit_parent_relationship", "Observes an explicitly represented parent reference or parent formation relationship.", situation => { const matching = records(situation).filter(record => { const value = (record.current ?? record.previous ?? {}) as { parentId?: unknown; parentCommitmentId?: unknown }; return (typeof value.parentId === "string" && value.parentId.length > 0) || (typeof value.parentCommitmentId === "string" && value.parentCommitmentId.length > 0); }); if (!matching.length && situation.formationPolicy.id !== "situation.explicit-parent-relationship") return undefined; const source = matching.length ? matching : records(situation); const parentIds = source.flatMap(record => { const value = (record.current ?? record.previous ?? {}) as { parentId?: unknown; parentCommitmentId?: unknown }; return [value.parentId, value.parentCommitmentId].filter((id): id is string => typeof id === "string" && id.length > 0); }).filter((id, index, all) => all.indexOf(id) === index).sort(compareText); return { records: source, evidence: { parentIds, formationPolicyId: situation.formationPolicy.id } }; });
export const containsMultipleCanonicalEntitiesPolicy = make("assessment.contains-multiple-canonical-entities", "contains_multiple_canonical_entities", "Observes more than one canonical domain and entity identifier pair.", situation => { const all = records(situation); const canonicalEntities = [...new Set(all.filter(r => r.entityId).map(r => `${r.domain}:${r.entityId}`))].sort(compareText); return canonicalEntities.length > 1 ? { records: all.filter(r => r.entityId), evidence: { canonicalEntities, canonicalEntityCount: canonicalEntities.length } } : undefined; });

export const INITIAL_SITUATION_ASSESSMENT_POLICIES = Object.freeze([containsCancelledCommitmentPolicy, containsExplicitParentRelationshipPolicy, containsMultipleAttentionDomainsPolicy, containsMultipleCanonicalEntitiesPolicy, containsScheduleModificationPolicy, containsSourceAvailabilityTransitionPolicy]);
