import type { ExecutiveSituation } from "../situations";
import type { SituationAssessment, SituationAssessmentObservation, SituationAssessmentPolicy, SituationAssessmentPolicyMetadata, SituationAssessmentSet } from "./types";

export const compareText = (a: string, b: string): number => a < b ? -1 : a > b ? 1 : 0;
export function required(value: unknown, path: string): asserts value is string { if (typeof value !== "string" || value.trim() === "") throw new Error(`${path} must be a non-empty string`); }
export function clone<T>(value: T): T { if (Array.isArray(value)) return value.map(clone) as T; if (value && typeof value === "object") return Object.fromEntries(Object.entries(value).map(([key, child]) => [key, clone(child)])) as T; return value; }
export function deepFreeze<T>(value: T): T { if (value && typeof value === "object" && !Object.isFrozen(value)) { Object.values(value).forEach(deepFreeze); Object.freeze(value); } return value; }
export function jsonCompatible(value: unknown, path = "value", ancestors = new Set<object>()): void { if (value === null || typeof value === "string" || typeof value === "boolean" || (typeof value === "number" && Number.isFinite(value))) return; if (!value || typeof value !== "object" || ancestors.has(value as object) || (!Array.isArray(value) && Object.getPrototypeOf(value) !== Object.prototype)) throw new Error(`${path} must contain only JSON-compatible values`); ancestors.add(value as object); for (const [key, child] of Object.entries(value)) jsonCompatible(child, `${path}.${key}`, ancestors); ancestors.delete(value as object); }
export function validatePolicy(policy: SituationAssessmentPolicy): void { if (!policy || typeof policy !== "object") throw new Error("assessment policy must be an object"); required(policy.id, "assessment policy id"); required(policy.version, "assessment policy version"); required(policy.observationType, "assessment policy observationType"); required(policy.description, "assessment policy description"); if (typeof policy.applies !== "function" || typeof policy.observe !== "function") throw new Error("assessment policy must implement applies() and observe()"); }
export const metadataOf = (policy: SituationAssessmentPolicy): SituationAssessmentPolicyMetadata => ({ id: policy.id, version: policy.version, observationType: policy.observationType, description: policy.description });
const encode = (value: string): string => encodeURIComponent(value);
const stable = (value: unknown): string => { if (Array.isArray(value)) return `[${value.map(stable).join(",")}]`; if (value && typeof value === "object") return `{${Object.entries(value).sort(([a], [b]) => compareText(a, b)).map(([k, v]) => `${JSON.stringify(k)}:${stable(v)}`).join(",")}}`; return JSON.stringify(value); };
export const observationIdentity = (situationId: string, policyId: string, type: string, attentionIds: readonly string[], evidence: unknown): string => `observation:${encode(situationId)}:${encode(policyId)}:${encode(type)}:${attentionIds.map(encode).sort(compareText).join(",")}:${encode(stable(evidence))}`;
export const assessmentIdentity = (situationId: string, observationIds: readonly string[], policyIds: readonly string[]): string => `assessment:${encode(situationId)}:${[...observationIds].sort(compareText).map(encode).join(",")}:${[...policyIds].sort(compareText).map(encode).join(",")}`;
export const situationSetIdentity = (snapshotId: string, situationIds: readonly string[]): string => `assessment-set:${encode(snapshotId)}:${[...situationIds].sort(compareText).map(encode).join(",")}`;
export const compareObservation = (a: SituationAssessmentObservation, b: SituationAssessmentObservation): number => compareText(a.observationId, b.observationId);
export const compareAssessment = (a: SituationAssessment, b: SituationAssessment): number => compareText(a.metadata.situationId, b.metadata.situationId) || compareText(a.observations[0]?.observationId ?? "", b.observations[0]?.observationId ?? "") || compareText(a.assessmentId, b.assessmentId);

export function validateObservation(observation: SituationAssessmentObservation, situation: ExecutiveSituation): void { required(observation.policyId, "observation policyId"); required(observation.policyVersion, "observation policyVersion"); required(observation.observationType, "observation type"); if (observation.originatingSituationId !== situation.situationId) throw new Error("observation originating situation is inconsistent"); jsonCompatible(observation.supportingEvidence, "observation supporting evidence"); if (!Array.isArray(observation.originatingAttentionRecordIds) || observation.originatingAttentionRecordIds.length === 0) throw new Error("observation must identify originating Attention Records"); const allowed = new Set(situation.memberships.map(m => m.attentionRecord.attentionId)); const sorted = [...observation.originatingAttentionRecordIds].sort(compareText); if (new Set(sorted).size !== sorted.length || sorted.some((id, i) => id !== observation.originatingAttentionRecordIds[i] || !allowed.has(id))) throw new Error("observation Attention Record origins are invalid or unordered"); const expected = observationIdentity(situation.situationId, observation.policyId, observation.observationType, sorted, observation.supportingEvidence); if (observation.observationId !== expected) throw new Error("invalid observation identity"); }

export function createSituationAssessmentSet(candidate: SituationAssessmentSet): SituationAssessmentSet { jsonCompatible(candidate, "situation assessment set"); required(candidate.currentSnapshotId, "assessment set currentSnapshotId"); required(candidate.situationSetId, "assessment set situationSetId"); const assessmentIds = new Set<string>(); const situationIds = new Set<string>(); const observationIds = new Set<string>(); let previous: SituationAssessment | undefined; for (const assessment of candidate.assessments) { required(assessment.assessmentId, "assessment id"); if (assessmentIds.has(assessment.assessmentId) || situationIds.has(assessment.metadata.situationId)) throw new Error("duplicate assessment or assessed situation"); assessmentIds.add(assessment.assessmentId); situationIds.add(assessment.metadata.situationId); if (assessment.metadata.currentSnapshotId !== candidate.currentSnapshotId) throw new Error("assessment snapshot is inconsistent"); const policyIds = assessment.metadata.policySet.map(p => p.id); if (new Set(policyIds).size !== policyIds.length || policyIds.some((id, i) => i > 0 && compareText(policyIds[i - 1], id) >= 0)) throw new Error("assessment policy set is invalid or unordered"); let priorObservation: SituationAssessmentObservation | undefined; for (const observation of assessment.observations) { if (observationIds.has(observation.observationId)) throw new Error(`duplicate observation identifier: ${observation.observationId}`); observationIds.add(observation.observationId); if (priorObservation && compareObservation(priorObservation, observation) >= 0) throw new Error("observations are not deterministically ordered"); priorObservation = observation; } if (assessment.assessmentId !== assessmentIdentity(assessment.metadata.situationId, assessment.observations.map(o => o.observationId), policyIds)) throw new Error("invalid assessment identity"); if (previous && compareAssessment(previous, assessment) >= 0) throw new Error("assessments are not deterministically ordered"); previous = assessment; }
  if (candidate.situationSetId !== situationSetIdentity(candidate.currentSnapshotId, [...situationIds])) throw new Error("invalid assessment set identity"); const byPolicy: Record<string, number> = {}; const byType: Record<string, number> = {}; for (const a of candidate.assessments) for (const o of a.observations) { byPolicy[o.policyId] = (byPolicy[o.policyId] ?? 0) + 1; byType[o.observationType] = (byType[o.observationType] ?? 0) + 1; } const ordered = (v: Record<string, number>) => Object.fromEntries(Object.entries(v).sort(([a], [b]) => compareText(a, b))); const s = candidate.summary; if (s.situations !== candidate.assessments.length || s.assessments !== candidate.assessments.length || s.observationCount !== observationIds.size || JSON.stringify(s.observationsByPolicy) !== JSON.stringify(ordered(byPolicy)) || JSON.stringify(s.observationsByType) !== JSON.stringify(ordered(byType))) throw new Error("assessment summary is inconsistent"); return deepFreeze(clone(candidate)); }
