import {describe,expect,it} from "vitest";
import type {GovernedActionProposal,GovernedActionProposalSet} from "../../proposal";
import {ExecutiveCapabilityRegistry,ExecutiveCapabilityRouter} from "..";
import {ExecutiveCapabilityInvocationHandoffBuilder} from ".";
const proposal=(id:string,overrides:Partial<GovernedActionProposal>={}):GovernedActionProposal=>({proposalId:id,definitionIdentifier:"definition",definitionVersion:"1",policyIdentifier:"proposal-policy",policyVersion:"1",proposalKind:"consider_candidate",proposalScope:"single_candidate",proposalStatus:"ready_for_human_review",reasonCode:"proposal-ready-for-human-review",candidatePlanIds:[],reasoningObservationIds:[],reasoningQuestionIds:[],reasoningBoundaryIds:[],conditions:[],authorityRequirements:[],evidenceRequirements:[],unresolvedQuestions:[],boundaries:[],payload:{request:id},provenance:{contextId:"context:legacy",intentSetId:"intent:1",constraintSetId:"constraints:1",candidatePlanSetId:"plans:1",evaluatedCandidatePlanSetId:"evaluations:1",comparisonSetId:"comparison:1",reasoningRecordId:"reasoning:1",definitionIdentifier:"definition",definitionVersion:"1",policyIdentifier:"proposal-policy",policyVersion:"1",origin:"test",candidatePlanIds:[],evaluationIds:[],comparisonIds:[],observationIds:[],reasoningQuestionIds:[],reasoningBoundaryIds:[],evidenceReferences:[],governanceReferences:[],status:"ready_for_human_review",reasonCode:"proposal-ready-for-human-review"},...overrides});
const set=(proposals:readonly GovernedActionProposal[]):GovernedActionProposalSet=>({proposalSetId:"governed-action-proposal-set:test",executiveStateSnapshotId:"state:1",executiveContextId:"context:1",deliberationContextId:"deliberation:1",contextId:"context:legacy",intentSetId:"intent:1",constraintSetId:"constraints:1",candidatePlanSetId:"plans:1",evaluatedCandidatePlanSetId:"evaluations:1",comparisonSetId:"comparison:1",reasoningRecordId:"reasoning:1",proposals,summary:{} as never,activePolicies:[],definitions:[],provenance:{proposalIds:proposals.map(x=>x.proposalId)}});
const capability=(id:string)=>({capabilityId:id,capabilityVersion:"1",status:"active" as const,dependencyCapabilityIds:[],supportedActionClasses:["consider_candidate" as const]});
const route=(proposals:readonly GovernedActionProposal[],ids=["zeta","alpha"])=>{const capabilities=ids.map(capability),scenario={scenarioId:"scenario",capabilityIds:ids},policy={policyId:"routing",policyVersion:"1",eligibleCapabilityIds:ids},rules=ids.map(id=>({routingRuleId:`rule:${id}`,capabilityId:id,actionClasses:["consider_candidate" as const]}));return new ExecutiveCapabilityRouter(new ExecutiveCapabilityRegistry(capabilities,[scenario],[policy],rules)).route({proposalSet:set(proposals),scenario,policy})};
const lexical={policyId:"handoff:lexical",policyVersion:"1",selectionMode:"lexical_first" as const};
describe("ExecutiveCapabilityInvocationHandoffBuilder",()=>{
 it("publishes exactly one replay-stable deeply immutable handoff in proposal order",()=>{const plan=route([proposal("proposal:z"),proposal("proposal:a")]),builder=new ExecutiveCapabilityInvocationHandoffBuilder(),first=builder.build({routingPlan:plan,policy:lexical}),replay=builder.build({routingPlan:plan,policy:lexical});expect(replay).toEqual(first);expect(first.items.map(x=>[x.proposalId,x.capabilityId])).toEqual([["proposal:a","alpha"],["proposal:z","alpha"]]);expect(first).toMatchObject({routingPlanId:plan.routingPlanId,proposalSetId:plan.proposalSetId,metadata:{owner:"ExecutiveCapabilityInvocationHandoffBuilder",approvalGranted:false,invocationPerformed:false,executionPerformed:false}});expect(Object.isFrozen(first.items[0].boundedRequest)).toBe(true)});
 it("preserves approval, authority, conditions, constraints, request and routing reason without approval",()=>{const base=proposal("proposal:1"),condition={conditionId:"approval:1",conditionType:"approval_required" as const,conditionStatus:"unresolved" as const,sourceCanonicalReference:"governance:1",candidatePlanIds:[],requiredEvidenceReferences:[],requiredAuthorityReferences:["human"],reasonCode:"approval-required-before-execution" as const,policyIdentifier:"proposal-policy",policyVersion:"1",provenance:base.provenance},authority={authorityRequirementId:"authority:1",authorityType:"human_executive" as const,sourceGovernanceReference:"human",proposalId:"proposal:1",candidatePlanIds:[],requirementStatus:"unresolved" as const,reasonCode:"authority-confirmation-required" as const,provenance:base.provenance};const result=new ExecutiveCapabilityInvocationHandoffBuilder().build({routingPlan:route([{...base,conditions:[condition],authorityRequirements:[authority]}]),policy:lexical});expect(result.items[0]).toMatchObject({boundedRequest:{request:"proposal:1"},routingReason:"eligible",approvalRequired:true,approvalGranted:false,authorityRequirements:[{authorityType:"human_executive",requirementStatus:"unresolved"}],unresolvedConditions:["approval:1"],invocationPerformed:false,executionPerformed:false})});
 it("represents blocked and no-invocation outcomes explicitly",()=>{const blocked=proposal("proposal:b",{proposalStatus:"blocked",boundaries:[{boundaryId:"boundary:1",boundaryType:"execution_prohibited",boundaryStatus:"blocked",sourceReasoningReference:"reasoning:1",proposalId:"proposal:b",candidatePlanIds:[],reasonCode:"execution-boundary-not-crossed",provenance:proposal("proposal:b").provenance}]}),defer=proposal("proposal:d",{proposalKind:"defer_pending_evidence"});expect(new ExecutiveCapabilityInvocationHandoffBuilder().build({routingPlan:route([blocked]),policy:lexical}).items[0].disposition).toBe("blocked");expect(new ExecutiveCapabilityInvocationHandoffBuilder().build({routingPlan:route([defer],[]),policy:lexical}).items[0].disposition).toBe("no_invocation")});
 it("refuses implicit ambiguous selection and rejects fabricated routing structures",()=>{const plan=route([proposal("proposal:1")]);expect(()=>new ExecutiveCapabilityInvocationHandoffBuilder().build({routingPlan:plan,policy:{...lexical,selectionMode:"require_unambiguous"}})).toThrowError(expect.objectContaining({code:"AMBIGUOUS_ELIGIBLE_CAPABILITIES"}));expect(()=>new ExecutiveCapabilityInvocationHandoffBuilder().build({routingPlan:undefined as never,policy:lexical})).toThrowError(expect.objectContaining({code:"MISSING_ROUTING_PLAN"}));const bad=structuredClone(plan);(bad.routedCapabilities[0] as {capabilityId:string}).capabilityId="fabricated";expect(()=>new ExecutiveCapabilityInvocationHandoffBuilder().build({routingPlan:bad,policy:lexical})).toThrowError(expect.objectContaining({code:"INVALID_ROUTING_PLAN_IDENTITY"}))});
});
