import { createHash } from "node:crypto";
import { EXECUTIVE_CAPABILITY_ROUTING_CONTRACT_VERSION } from "..";
import type { ExecutiveCapabilityRoutingPlan, ProposalCapabilityRouting, RoutedExecutiveCapability } from "..";
import { EXECUTIVE_CAPABILITY_INVOCATION_HANDOFF_VERSION,ExecutiveCapabilityInvocationHandoffError } from "./types";
import type { ExecutiveCapabilityInvocationHandoff,ExecutiveCapabilityInvocationHandoffInput,ExecutiveCapabilityInvocationHandoffItem } from "./types";
const compare=(a:string,b:string)=>a<b?-1:a>b?1:0;
const canonical=(v:unknown):string=>Array.isArray(v)?`[${v.map(canonical)}]`:v&&typeof v==="object"?`{${Object.keys(v).sort(compare).map(k=>`${JSON.stringify(k)}:${canonical((v as Record<string,unknown>)[k])}`)}}`:JSON.stringify(v);
const hash=(prefix:string,v:unknown)=>`${prefix}:${createHash("sha256").update(canonical(v)).digest("hex")}`;
const freeze=<T>(v:T):T=>{if(v&&typeof v==="object"&&!Object.isFrozen(v)){Object.values(v).forEach(freeze);Object.freeze(v)}return v};
const clone=<T>(v:T):T=>structuredClone(v);
const nonAction=new Set(["defer_pending_evidence","preserve_options","no_action_pending_resolution"]);
function validate(plan:ExecutiveCapabilityRoutingPlan|undefined):asserts plan is ExecutiveCapabilityRoutingPlan{if(!plan)throw new ExecutiveCapabilityInvocationHandoffError("MISSING_ROUTING_PLAN","canonical routing plan is required");if(!plan.routingPlanId?.startsWith("executive-capability-routing:")||plan.routingContractVersion!==EXECUTIVE_CAPABILITY_ROUTING_CONTRACT_VERSION||plan.routingPlanId!==hash("executive-capability-routing",Object.fromEntries(Object.entries(plan).filter(([key])=>key!=="routingPlanId"))))throw new ExecutiveCapabilityInvocationHandoffError("INVALID_ROUTING_PLAN_IDENTITY","routing identity or contract is invalid");const proposals=plan.proposalRoutings.map(x=>x.proposalId),routes=plan.routedCapabilities.map(x=>`${x.proposalId}|${x.capabilityId}`);if(new Set(proposals).size!==proposals.length||new Set(routes).size!==routes.length)throw new ExecutiveCapabilityInvocationHandoffError("DUPLICATE_ROUTING_OUTCOME","routing outcomes must be unique");for(const route of plan.routedCapabilities){const proposal=plan.proposalRoutings.find(x=>x.proposalId===route.proposalId);if(!proposal)throw new ExecutiveCapabilityInvocationHandoffError("PROPOSAL_IDENTITY_MISMATCH","routed proposal is absent");if(!proposal.eligibleCapabilityIds.includes(route.capabilityId))throw new ExecutiveCapabilityInvocationHandoffError("SELECTED_CAPABILITY_NOT_ELIGIBLE","routed capability is not eligible")}}
const blocked=(r:ProposalCapabilityRouting)=>r.proposalStatus==="blocked"||r.routingReason==="blocked_by_constitutional_constraint"||r.boundaries.some(x=>x.boundaryType==="execution_prohibited"||x.boundaryStatus==="blocked");
function item(r:ProposalCapabilityRouting,route:RoutedExecutiveCapability|undefined):ExecutiveCapabilityInvocationHandoffItem{const disposition:ExecutiveCapabilityInvocationHandoffItem["disposition"]=blocked(r)?"blocked":!route||nonAction.has(r.actionClass)||r.proposalStatus==="not_applicable"?"no_invocation":"prepared";const body={proposalId:r.proposalId,capabilityId:route?.capabilityId,capabilityVersion:route?.capabilityVersion,routingRuleIds:route?[...route.routingRuleIds]:[],dependencyCapabilityIds:route?[...route.dependencyCapabilityIds]:[],routingOutcomeIdentity:hash("routing-outcome",{proposalId:r.proposalId,capabilityId:route?.capabilityId,reason:r.routingReason}),routingReason:r.routingReason,actionClass:r.actionClass,boundedRequest:clone(r.boundedRequest),constraints:[...r.constitutionalConstraintsApplied].sort(compare),evidenceRequirements:[...r.evidenceRequirements].sort(compare),conditions:clone(r.conditions),authorityRequirements:clone(r.authorityRequirements),approvalRequired:r.approvalRequired,approvalGranted:false as const,boundaries:clone(r.boundaries),unresolvedConditions:r.conditions.filter(x=>x.conditionStatus==="blocked"||x.conditionStatus==="unresolved").map(x=>x.conditionId).sort(compare),disposition,invocationPerformed:false as const,executionPerformed:false as const};return {handoffItemId:hash("capability-invocation-handoff-item",body),...body}}
export class ExecutiveCapabilityInvocationHandoffBuilder{build(input:ExecutiveCapabilityInvocationHandoffInput):ExecutiveCapabilityInvocationHandoff{validate(input?.routingPlan);const policy=input?.policy;if(!policy?.policyId?.trim()||!policy.policyVersion?.trim()||!(["lexical_first","require_unambiguous"] as const).includes(policy.selectionMode))throw new ExecutiveCapabilityInvocationHandoffError("INVALID_HANDOFF_POLICY","an explicit registered handoff policy is required");const items=input.routingPlan.proposalRoutings.map(r=>{const routes=input.routingPlan.routedCapabilities.filter(x=>x.proposalId===r.proposalId).sort((a,b)=>compare(a.capabilityId,b.capabilityId));if(routes.length>1&&policy.selectionMode==="require_unambiguous")throw new ExecutiveCapabilityInvocationHandoffError("AMBIGUOUS_ELIGIBLE_CAPABILITIES",`proposal ${r.proposalId} has multiple eligible capabilities`);return item(r,routes[0])}).sort((a,b)=>compare(a.proposalId,b.proposalId));const body={handoffContractVersion:EXECUTIVE_CAPABILITY_INVOCATION_HANDOFF_VERSION,routingPlanId:input.routingPlan.routingPlanId,routingScenarioId:input.routingPlan.scenarioId,routingPolicyId:input.routingPlan.policyId,routingPolicyVersion:input.routingPlan.policyVersion,proposalSetId:input.routingPlan.proposalSetId,executiveStateSnapshotId:input.routingPlan.executiveStateSnapshotId,executiveContextId:input.routingPlan.executiveContextId,deliberationContextId:input.routingPlan.deliberationContextId,reasoningRecordId:input.routingPlan.reasoningRecordId,selectionPolicyId:policy.policyId,selectionPolicyVersion:policy.policyVersion,selectionMode:policy.selectionMode,items,metadata:{owner:"ExecutiveCapabilityInvocationHandoffBuilder",semantics:"request_preparation_only",approvalGranted:false,invocationPerformed:false,executionPerformed:false} as const};return freeze({handoffId:hash("executive-capability-invocation-handoff",body),...body})}}
