import type { ExecutiveCapabilityRoutingPlan, ProposalCapabilityRouting } from "..";

export const EXECUTIVE_CAPABILITY_INVOCATION_HANDOFF_VERSION="executive-capability-invocation-handoff-v1" as const;
export type HandoffSelectionMode="lexical_first"|"require_unambiguous";
export interface ExecutiveCapabilityInvocationHandoffPolicy {readonly policyId:string;readonly policyVersion:string;readonly selectionMode:HandoffSelectionMode}
export interface ExecutiveCapabilityInvocationHandoffInput {readonly routingPlan:ExecutiveCapabilityRoutingPlan;readonly policy:ExecutiveCapabilityInvocationHandoffPolicy}
export type InvocationHandoffDisposition="prepared"|"blocked"|"no_invocation";
export interface ExecutiveCapabilityInvocationHandoffItem {
 readonly handoffItemId:string;readonly proposalId:string;readonly capabilityId?:string;readonly capabilityVersion?:string;readonly routingRuleIds:readonly string[];readonly dependencyCapabilityIds:readonly string[];readonly routingOutcomeIdentity:string;readonly routingReason:string;readonly actionClass:ProposalCapabilityRouting["actionClass"];readonly boundedRequest:ProposalCapabilityRouting["boundedRequest"];readonly constraints:readonly string[];readonly evidenceRequirements:readonly string[];readonly conditions:ProposalCapabilityRouting["conditions"];readonly authorityRequirements:ProposalCapabilityRouting["authorityRequirements"];readonly approvalRequired:boolean;readonly approvalGranted:false;readonly boundaries:ProposalCapabilityRouting["boundaries"];readonly unresolvedConditions:readonly string[];readonly disposition:InvocationHandoffDisposition;readonly invocationPerformed:false;readonly executionPerformed:false;
}
export interface ExecutiveCapabilityInvocationHandoff {readonly handoffId:string;readonly handoffContractVersion:typeof EXECUTIVE_CAPABILITY_INVOCATION_HANDOFF_VERSION;readonly routingPlanId:string;readonly routingScenarioId:string;readonly routingPolicyId:string;readonly routingPolicyVersion:string;readonly proposalSetId:string;readonly executiveStateSnapshotId:string;readonly executiveContextId:string;readonly deliberationContextId:string;readonly reasoningRecordId:string;readonly selectionPolicyId:string;readonly selectionPolicyVersion:string;readonly selectionMode:HandoffSelectionMode;readonly items:readonly ExecutiveCapabilityInvocationHandoffItem[];readonly metadata:Readonly<{owner:"ExecutiveCapabilityInvocationHandoffBuilder";semantics:"request_preparation_only";approvalGranted:false;invocationPerformed:false;executionPerformed:false}>}
export type ExecutiveCapabilityInvocationHandoffFailureCode="MISSING_ROUTING_PLAN"|"INVALID_ROUTING_PLAN_IDENTITY"|"DUPLICATE_ROUTING_OUTCOME"|"PROPOSAL_IDENTITY_MISMATCH"|"CAPABILITY_IDENTITY_MISMATCH"|"SELECTED_CAPABILITY_NOT_ELIGIBLE"|"AMBIGUOUS_ELIGIBLE_CAPABILITIES"|"INVALID_HANDOFF_POLICY"|"MISSING_AUTHORITY_REQUIREMENT"|"MISSING_APPROVAL_STATE"|"INVALID_HANDOFF_IDENTITY";
export class ExecutiveCapabilityInvocationHandoffError extends Error{constructor(readonly code:ExecutiveCapabilityInvocationHandoffFailureCode,message:string){super(message);this.name="ExecutiveCapabilityInvocationHandoffError"}}
