import { describe, expect, it } from "vitest";
import { normalizeGoogleEvent } from "../../connectors/calendar-event";
import { AttentionPolicyRegistry, INITIAL_ATTENTION_POLICIES, constructExecutiveAttentionQueue } from "../attention";
import { ExecutiveSituationAssessmentEngine, INITIAL_SITUATION_ASSESSMENT_POLICIES, SituationAssessmentRegistry } from "../assessment";
import { ExecutiveContextEngine, ExecutiveContextRegistry, INITIAL_CONTEXT_POLICIES } from "../context";
import { compareSituationalAwarenessSnapshots, createSituationalAwarenessSnapshot } from "../situational-awareness/lifecycle";
import { CalendarProjectionAdapter, ProjectionEngine, ProjectionRegistry } from "../situational-awareness/projection";
import { ExecutiveSituationEngine, INITIAL_SITUATION_FORMATION_POLICIES, SituationFormationRegistry } from "../situations";
import { DeterministicConstraintEngine, DeterministicIntentEngine, ExecutiveConstraintRegistry, ExecutiveIntentRegistry, INITIAL_CONSTRAINT_POLICIES, INITIAL_INTENT_POLICIES } from ".";

async function project(status: "confirmed" | "cancelled", observedAt: string) { const event = normalizeGoogleEvent({ id: "board", summary: "Board review", status, start: { dateTime: "2026-07-28T09:00:00Z" }, end: { dateTime: "2026-07-28T10:00:00Z" } }, 0, { calendarId: "executive", calendarName: "Executive" }); const registry = new ProjectionRegistry(); registry.register(new CalendarProjectionAdapter({ identity: { userId: "u", displayName: "User" }, observedAt, connector: { source: "google", listUpcoming: async () => [event] } })); return new ProjectionEngine(registry).project(); }
describe("Calendar to Intent and Constraint integration", () => { it("carries canonical context identity into deterministic sets without inferring from the calendar", async () => { const previous = createSituationalAwarenessSnapshot({ snapshotId: "calendar-a", observedAt: "2026-07-27T08:00:00Z", state: await project("confirmed", "2026-07-27T08:00:00Z") }); const current = createSituationalAwarenessSnapshot({ snapshotId: "calendar-b", observedAt: "2026-07-27T09:00:00Z", state: await project("cancelled", "2026-07-27T09:00:00Z") }); const queue = constructExecutiveAttentionQueue(compareSituationalAwarenessSnapshots(previous, current), new AttentionPolicyRegistry(INITIAL_ATTENTION_POLICIES)); const situations = new ExecutiveSituationEngine(new SituationFormationRegistry(INITIAL_SITUATION_FORMATION_POLICIES)).form(queue); const assessments = new ExecutiveSituationAssessmentEngine(new SituationAssessmentRegistry(INITIAL_SITUATION_ASSESSMENT_POLICIES)).assess(situations); const assessedContext = new ExecutiveContextEngine(new ExecutiveContextRegistry(INITIAL_CONTEXT_POLICIES)).construct(assessments); const context = { ...assessedContext, deliberationContextId: assessedContext.contextId }; const intentEngine = new DeterministicIntentEngine(new ExecutiveIntentRegistry(INITIAL_INTENT_POLICIES)); const constraintEngine = new DeterministicConstraintEngine(new ExecutiveConstraintRegistry(INITIAL_CONSTRAINT_POLICIES)); const intentConfig = { objectives: [{ identifier: "objective:board-governance", type: "standing" as const, description: "Maintain board governance.", origin: "organisation:configuration", activationStatus: "active" as const, scope: { board: "executive" } }] }; const constraintConfig = { constraints: [{ identifier: "constraint:board-approval", type: "approval" as const, origin: "governance:configuration", bindingStatus: "binding" as const, scope: { action: "board-decision" } }] }; const intentSet = intentEngine.construct(context, intentConfig); const constraintSet = constraintEngine.construct(context, constraintConfig); expect(intentSet.contextId).toBe(context.contextId); expect(constraintSet.contextId).toBe(context.contextId); expect(intentSet).toEqual(intentEngine.construct(context, intentConfig)); expect(constraintSet).toEqual(constraintEngine.construct(context, constraintConfig)); expect(intentSet.objectives).toHaveLength(1); expect(constraintSet.constraints).toHaveLength(1); }); });
