import { describe, expect, it } from "vitest";
import type { ExecutiveContext } from "../context";
import { DeterministicConstraintEngine, DeterministicIntentEngine, ExecutiveConstraintRegistry, ExecutiveIntentRegistry, INITIAL_CONSTRAINT_POLICIES, INITIAL_INTENT_POLICIES, createConstraintSet, createIntentSet } from ".";

const context = (): ExecutiveContext => ({ contextId: "executive-context:calendar", snapshotId: "snapshot:calendar", assessmentSetId: "assessment:calendar", sections: [], statistics: [], summary: { sectionCount: 0, statisticCount: 0, situationCount: 0, assessmentCount: 0, attentionRecordCount: 0, observationCount: 0 }, canonicalProvenance: { snapshotId: "snapshot:calendar", assessmentSetId: "assessment:calendar", situationSetId: "situation:calendar", policies: [] } });
const intents = { objectives: [{ identifier: "objective:z", type: "standing", description: "Preserve regulatory compliance.", origin: "organisation:governance", activationStatus: "active", scope: { organisation: "jarvis" } }, { identifier: "objective:a", type: "operational", description: "Complete the explicitly authorised operating review.", origin: "user:configuration", activationStatus: "inactive", scope: { session: "current" } }] } as const;
const constraints = { constraints: [{ identifier: "constraint:z", type: "temporal", origin: "user:configuration", scope: { notAfter: "2026-07-31T00:00:00Z" }, bindingStatus: "binding" }, { identifier: "constraint:a", type: "authority", origin: "governance:delegation", scope: { decision: "board-only" }, bindingStatus: "binding" }, { identifier: "constraint:m", type: "approval", origin: "constitution:human-control", scope: { execution: "human-approval-required" }, bindingStatus: "non-binding" }] } as const;
const intentEngine = (policies = INITIAL_INTENT_POLICIES) => new DeterministicIntentEngine(new ExecutiveIntentRegistry(policies));
const constraintEngine = (policies = INITIAL_CONSTRAINT_POLICIES) => new DeterministicConstraintEngine(new ExecutiveConstraintRegistry(policies));

describe("Executive Intent and Constraint Model", () => {
  it("constructs ordered objectives and constraints with stable identities and summaries", () => { const intentSet = intentEngine().construct(context(), intents); const constraintSet = constraintEngine().construct(context(), constraints); expect(intentSet.objectives.map(i => i.identifier)).toEqual(["objective:a", "objective:z"]); expect(constraintSet.constraints.map(i => i.identifier)).toEqual(["constraint:a", "constraint:m", "constraint:z"]); expect(intentSet.summary).toEqual({ objectiveCount: 2, activeCount: 1, inactiveCount: 1, byType: { operational: 1, strategic: 0, standing: 1, session: 0, mission: 0 } }); expect(constraintSet.summary).toEqual({ constraintCount: 3, bindingCount: 2, nonBindingCount: 1, byType: { authority: 1, temporal: 1, resource: 0, governance: 0, behavioural: 0, privacy: 0, execution: 0, approval: 1 } }); });
  it("is replay safe, registry-order independent, JSON-compatible, immutable, and deeply frozen", () => { const first = intentEngine().construct(context(), intents); expect(intentEngine().construct(context(), intents)).toEqual(first); expect(intentEngine([...INITIAL_INTENT_POLICIES].reverse()).construct(context(), intents)).toEqual(first); expect(JSON.parse(JSON.stringify(first))).toEqual(first); expect(Object.isFrozen(first)).toBe(true); expect(Object.isFrozen(first.objectives[0].scope)).toBe(true); expect(() => (first.summary as { objectiveCount: number }).objectiveCount = 9).toThrow(); });
  it("rejects duplicate identifiers atomically", () => { const duplicate = { objectives: [intents.objectives[0], { ...intents.objectives[0] }] }; expect(() => intentEngine().construct(context(), duplicate)).toThrow(/duplicate objective/); expect(() => constraintEngine().construct(context(), { constraints: [constraints.constraints[0], constraints.constraints[0]] })).toThrow(/duplicate constraint/); });
  it("validates registries, identities, ordering, and summary consistency", () => { const registry = new ExecutiveIntentRegistry(); registry.register(INITIAL_INTENT_POLICIES[0]); expect(() => registry.register(INITIAL_INTENT_POLICIES[0])).toThrow(/duplicate/); expect(() => registry.register({ id: "bad" } as never)).toThrow(); const good = intentEngine().construct(context(), intents); expect(() => createIntentSet({ ...good, intentSetId: "random" })).toThrow(/identity/); expect(() => createIntentSet({ ...good, summary: { ...good.summary, activeCount: 7 } })).toThrow(/summary/); const goodConstraints = constraintEngine().construct(context(), constraints); expect(() => createConstraintSet({ ...goodConstraints, constraints: [...goodConstraints.constraints].reverse() })).toThrow(/lexical/); });
});
