import type { ExecutiveContext } from "../context";
import type { ConstraintPolicy, ConstraintSet, ConstraintSummary, ExecutiveConstraint, ExecutiveIntent, IntentPolicy, IntentSet, IntentSummary } from "./types";

export const compareText = (a: string, b: string): number => a < b ? -1 : a > b ? 1 : 0;
export function required(value: unknown, path: string): asserts value is string { if (typeof value !== "string" || value.trim() === "") throw new Error(`${path} must be a non-empty string`); }
export function clone<T>(value: T): T { if (Array.isArray(value)) return value.map(clone) as T; if (value && typeof value === "object") return Object.fromEntries(Object.entries(value).map(([key, child]) => [key, clone(child)])) as T; return value; }
export function deepFreeze<T>(value: T): T { if (value && typeof value === "object" && !Object.isFrozen(value)) { Object.values(value).forEach(deepFreeze); Object.freeze(value); } return value; }
export function jsonCompatible(value: unknown, path = "value", ancestors = new Set<object>()): void { if (value === null || typeof value === "string" || typeof value === "boolean" || (typeof value === "number" && Number.isFinite(value))) return; if (!value || typeof value !== "object" || ancestors.has(value as object) || (!Array.isArray(value) && Object.getPrototypeOf(value) !== Object.prototype)) throw new Error(`${path} must contain only JSON-compatible values`); ancestors.add(value as object); for (const [key, child] of Object.entries(value)) jsonCompatible(child, `${path}.${key}`, ancestors); ancestors.delete(value as object); }
const encode = encodeURIComponent;
export const intentSetIdentity = (contextId: string, identifiers: readonly string[]): string => `intent-set:${encode(contextId)}:${[...identifiers].sort(compareText).map(encode).join(",")}`;
export const constraintSetIdentity = (contextId: string, identifiers: readonly string[]): string => `constraint-set:${encode(contextId)}:${[...identifiers].sort(compareText).map(encode).join(",")}`;
export function validateContext(context: ExecutiveContext): void { if (!context || typeof context !== "object") throw new Error("executive context is required"); required(context.contextId, "executive context identifier"); jsonCompatible(context, "executive context"); }
export function validateIntentPolicy(policy: IntentPolicy): void { if (!policy || typeof policy !== "object") throw new Error("intent policy must be an object"); required(policy.id, "intent policy id"); required(policy.version, "intent policy version"); required(policy.description, "intent policy description"); required(policy.intentType, "intent policy type"); if (typeof policy.construct !== "function") throw new Error("intent policy must implement construct()"); }
export function validateConstraintPolicy(policy: ConstraintPolicy): void { if (!policy || typeof policy !== "object") throw new Error("constraint policy must be an object"); required(policy.id, "constraint policy id"); required(policy.version, "constraint policy version"); required(policy.description, "constraint policy description"); if (!Array.isArray(policy.constraintTypes) || policy.constraintTypes.length === 0) throw new Error("constraint policy types are required"); if (typeof policy.construct !== "function") throw new Error("constraint policy must implement construct()"); }
const orderedUnique = (ids: readonly string[], label: string) => { if (new Set(ids).size !== ids.length) throw new Error(`duplicate ${label} identifier`); if (ids.some((id, index) => index > 0 && compareText(ids[index - 1], id) >= 0)) throw new Error(`${label}s must use lexical identifier order`); };
const intentTypes = ["operational", "strategic", "standing", "session", "mission"] as const;
const constraintTypes = ["authority", "temporal", "resource", "governance", "behavioural", "privacy", "execution", "approval"] as const;
export const intentSummary = (items: readonly ExecutiveIntent[]): IntentSummary => ({ objectiveCount: items.length, activeCount: items.filter(i => i.activationStatus === "active").length, inactiveCount: items.filter(i => i.activationStatus === "inactive").length, byType: Object.fromEntries(intentTypes.map(type => [type, items.filter(i => i.type === type).length])) as unknown as IntentSummary["byType"] });
export const constraintSummary = (items: readonly ExecutiveConstraint[]): ConstraintSummary => ({ constraintCount: items.length, bindingCount: items.filter(i => i.bindingStatus === "binding").length, nonBindingCount: items.filter(i => i.bindingStatus === "non-binding").length, byType: Object.fromEntries(constraintTypes.map(type => [type, items.filter(i => i.type === type).length])) as unknown as ConstraintSummary["byType"] });
export function createIntentSet(candidate: IntentSet): IntentSet { jsonCompatible(candidate, "intent set"); required(candidate.contextId, "intent set context identifier"); candidate.objectives.forEach((item, i) => { required(item.identifier, `objective ${i} identifier`); required(item.description, `objective ${i} description`); required(item.origin, `objective ${i} origin`); }); const ids = candidate.objectives.map(i => i.identifier); orderedUnique(ids, "objective"); if (candidate.intentSetId !== intentSetIdentity(candidate.contextId, ids)) throw new Error("invalid intent set identity"); if (JSON.stringify(candidate.summary) !== JSON.stringify(intentSummary(candidate.objectives))) throw new Error("intent summary is inconsistent"); if (candidate.provenance.contextId !== candidate.contextId) throw new Error("intent provenance is inconsistent"); return deepFreeze(clone(candidate)); }
export function createConstraintSet(candidate: ConstraintSet): ConstraintSet { jsonCompatible(candidate, "constraint set"); required(candidate.contextId, "constraint set context identifier"); candidate.constraints.forEach((item, i) => { required(item.identifier, `constraint ${i} identifier`); required(item.origin, `constraint ${i} origin`); }); const ids = candidate.constraints.map(i => i.identifier); orderedUnique(ids, "constraint"); if (candidate.constraintSetId !== constraintSetIdentity(candidate.contextId, ids)) throw new Error("invalid constraint set identity"); if (JSON.stringify(candidate.summary) !== JSON.stringify(constraintSummary(candidate.constraints))) throw new Error("constraint summary is inconsistent"); if (candidate.provenance.contextId !== candidate.contextId) throw new Error("constraint provenance is inconsistent"); return deepFreeze(clone(candidate)); }
