import type { GovernedClaimInput } from "./types";

export type AdmittedClaimType = "contact_address_lookup" | "message_importance";
export type BoundaryOutcome = "recognised" | "missing_required_parameter" | "ambiguous_governed_intent" | "unresolved_entity" | "unsupported_language" | "unsupported_claim_type" | "no_governed_factual_claim";
export type CommunicationTypedIntent = { readonly type: "contact_address_lookup"; readonly personName?: string } | { readonly type: "message_importance"; readonly personName?: string };
export interface BoundaryEntity { readonly entityId: string; readonly personName: string; readonly displayLabel: string }
export interface ClaimTemplate { readonly claimType: AdmittedClaimType; readonly material: true; readonly supported: boolean; readonly sourceRequirement: string; readonly completenessRule: string; readonly contentKind: "metadata" }
export interface BoundaryRule { readonly ruleId: string; readonly claimType: AdmittedClaimType; readonly mechanism: "exact_command" | "alias" | "lexical_pattern" | "grammar"; readonly expression: string }
export interface ClaimBoundaryRulesetBody { readonly schemaVersion: "1"; readonly rulesetVersion: "1.0.0"; readonly precedence: readonly ["typed_capability", "typed_ui_intent", "exact_command_or_alias", "lexical_pattern_or_grammar", "clarification", "unsupported"]; readonly typedIntents: readonly AdmittedClaimType[]; readonly rules: readonly BoundaryRule[]; readonly claimTemplates: readonly ClaimTemplate[]; readonly clarificationRules: readonly ["missing_required_parameter", "ambiguous_governed_intent", "unresolved_entity"]; readonly unsupportedRules: readonly ["unsupported_language", "unsupported_claim_type", "second_unresolved_clarification"]; readonly prohibitedHeuristicFields: readonly ["unread", "important", "needsReply", "labels", "messageOrdering", "legacyAttentionMetadata"] }
export interface ClaimBoundaryRuleset extends ClaimBoundaryRulesetBody { readonly claimBoundaryRulesetId: string; readonly publicationDigest: string }
export interface MatchedSpan { readonly segmentId: string; readonly ruleId: string; readonly claimType: AdmittedClaimType; readonly start: number; readonly end: number; readonly text: string }
export interface ExtractedParameter { readonly segmentId: string; readonly name: "personName" | "entityId"; readonly value: string }
export interface ClarificationPublication { readonly reason: "missing_required_parameter" | "ambiguous_governed_intent" | "unresolved_entity"; readonly requiredField: "personName" | "intent" | "entityId"; readonly choices: readonly { readonly value: string; readonly label: string }[]; readonly continuationToken: string; readonly priorEvaluationId?: string }
export interface ClaimBoundaryEvaluation { readonly claimBoundaryEvaluationId: string; readonly schemaVersion: "1"; readonly claimBoundaryRulesetId: string; readonly threadId: string; readonly requestId: string; readonly exchangeId: string; readonly inputDigest: string; readonly referenceTime: string; readonly typedIntentResult: "not_supplied" | "valid" | "invalid"; readonly matchedRuleIds: readonly string[]; readonly matchedSpans: readonly MatchedSpan[]; readonly extractedParameters: readonly ExtractedParameter[]; readonly segmentation: readonly { readonly segmentId: string; readonly start: number; readonly end: number; readonly disposition: "governed" | "residual" }[]; readonly outcome: BoundaryOutcome; readonly uncertaintyReason?: string; readonly clarification?: ClarificationPublication; readonly unsupportedReason?: string; readonly priorEvaluationId?: string; readonly createdAt: string }
export interface GovernedClaimSet { readonly governedClaimSetId: string; readonly schemaVersion: "1"; readonly claimBoundaryEvaluationId: string; readonly claimBoundaryRulesetId: string; readonly threadId: string; readonly requestId: string; readonly exchangeId: string; readonly referenceTime: string; readonly claims: readonly GovernedClaimInput[]; readonly segmentLinks: readonly { readonly segmentId: string; readonly claimId: string }[]; readonly claimIds: readonly string[]; readonly createdAt: string }
export interface BoundaryEngineInput { readonly text: string; readonly typedIntent?: unknown; readonly typedIntentSource?: "capability" | "ui"; readonly threadId: string; readonly requestId: string; readonly exchangeId: string; readonly referenceTime: string; readonly createdAt: string; readonly entities?: readonly BoundaryEntity[]; readonly priorEvaluationId?: string; readonly clarificationAttempt?: number; readonly compatibilityContext?: unknown }
export interface BoundaryEngineResult { readonly evaluation: ClaimBoundaryEvaluation; readonly claimSet?: GovernedClaimSet }
