import { lineageIdentity } from "./lineage-types";

export const CONVERSATIONAL_EXCHANGE_STATES = ["created", "input_projected", "model_invocation_started", "model_output_received", "validation_passed", "validation_failed", "safe_response_created", "completed", "failed"] as const;
export type ConversationalExchangeState = (typeof CONVERSATIONAL_EXCHANGE_STATES)[number];
export type ConversationalFailureCategory = "projection" | "source" | "provider" | "malformed_output" | "validation" | "persistence";
export interface ConversationalLifecycleEvent { readonly eventId: string; readonly exchangeId: string; readonly from: ConversationalExchangeState; readonly to: ConversationalExchangeState; readonly occurredAt: string; readonly eventCode: string; readonly attemptId?: string; readonly projectionId?: string; readonly responseEnvelopeId?: string; readonly failureCategory?: ConversationalFailureCategory; readonly failureCode?: string }
const transitions: Readonly<Record<ConversationalExchangeState, readonly ConversationalExchangeState[]>> = { created: ["input_projected", "failed"], input_projected: ["model_invocation_started", "failed"], model_invocation_started: ["model_output_received", "failed"], model_output_received: ["validation_passed", "validation_failed"], validation_passed: ["completed"], validation_failed: ["safe_response_created", "failed"], safe_response_created: ["completed"], completed: [], failed: [] };
export const isPermittedTransition = (from: ConversationalExchangeState, to: ConversationalExchangeState) => transitions[from].includes(to);
export function constructLifecycleEvent(input: Omit<ConversationalLifecycleEvent, "eventId"> & { readonly eventDiscriminator: string }): ConversationalLifecycleEvent { const { eventDiscriminator, ...body } = input; if (!eventDiscriminator || !isPermittedTransition(body.from, body.to)) throw new Error(`prohibited exchange transition: ${body.from} -> ${body.to}`); if (body.to === "failed" && (!body.failureCategory || !body.failureCode)) throw new Error("failed transition requires failure category and code"); return Object.freeze({ ...body, eventId: lineageIdentity("conversational-lifecycle-event", { ...body, eventDiscriminator }) }); }
