import type { GmailProductionAcquisition } from "../connectors/google/gmail";
import type { MemoryStore } from "../memory/schema";
import { evaluateClaimBoundary } from "./claim-boundary-engine";
import { evaluateGovernedConversationalConflicts } from "./conflict-boundary-engine";
import { CONFLICT_EVALUATION_RULESET } from "./conflict-boundary-ruleset";
import type { ConversationalConflictClass, GovernedSourceObservation } from "./conflict-boundary-types";
import { constructGovernedConversationalInput } from "./input";
import { lineageIdentity } from "./lineage-types";
import { invokeGovernedConversationModel, type GovernedConversationModelAdapter } from "./model-invocation";
import { composeGovernedConversationalProjection, constructGovernedConflictSummary } from "./projection-composer";
import { assembleGovernedSourceEvidence, type GovernedSourceEvidenceAssemblyInput } from "./source-evidence-assembly";

export const FULL_ASSEMBLY_TIME = "2026-08-01T12:00:00.000Z";
export const FULL_ASSEMBLY_SCENARIO_IDS = ["cassie-compound-contact-conflict", "single-contact-no-conflict", "legacy-memory-unattested", "connector-disconnected-local-fallback", "gmail-conflict-plus-unsupported-claim", "conflict-evaluation-unavailable", "conflict-evaluation-unsupported", "conflict-evaluation-failed", "partial-source-failure", "deterministic-replay"] as const;
export type FullAssemblyScenarioId = typeof FULL_ASSEMBLY_SCENARIO_IDS[number];
export type SeamStatus = "compatible" | "bounded-adapter-needed" | "semantic-incompatibility" | "unresolved";
export interface StageResult { readonly passed: boolean; readonly evidence: string }
export interface FullAssemblyFinding { readonly seam: string; readonly status: SeamStatus; readonly evidence: string; readonly requiredNextStep: string }
export interface FullAssemblyRegressionResult { readonly scenarioId: FullAssemblyScenarioId; readonly passed: boolean; readonly stageResults: { readonly assembly: StageResult; readonly claims: StageResult; readonly conflicts: StageResult; readonly projection: StageResult; readonly governedInput: StageResult; readonly modelInvocation: StageResult; readonly validation: StageResult }; readonly findings: readonly FullAssemblyFinding[]; readonly identities: Readonly<Record<string, string | undefined>>; readonly statuses: Readonly<Record<string, unknown>> }

const gmail: GmailProductionAcquisition = Object.freeze({ messages: [], observedAt: FULL_ASSEMBLY_TIME, snapshotId: "google-gmail:sprint-3.102", observations: Object.freeze([{ id: "gmail-provider-cassie", retrievedAt: FULL_ASSEMBLY_TIME, internalDate: "1785582000000", payload: { headers: [{ name: "Message-ID", value: "<cassie@example.com>" }, { name: "From", value: "Cassie <cassie.primary@example.com>" }, { name: "To", value: "operator@example.com" }, { name: "Date", value: "Sat, 1 Aug 2026 12:00:00 +0000" }] } }]) });
const memory: MemoryStore = { priorities: [{ rank: 1, title: "Unattested", detail: "private", due: "today", urgent: true }], projects: [], signals: [], calendar: [], gmailThreads: [], driveFiles: [], updatedAt: FULL_ASSEMBLY_TIME };
export function fullAssemblySourceInput(id: FullAssemblyScenarioId): GovernedSourceEvidenceAssemblyInput {
  const gmailUnavailable = id === "partial-source-failure";
  return {
    gmail: { connector: { acquireRecent: async () => { if (gmailUnavailable) throw new Error("deterministic unavailable fixture"); return gmail; } }, limit: 5 },
    calendar: { connector: { source: "google", listUpcoming: async () => [{ id: "event-3.102", title: "Private", start: "2026-08-02T09:00:00Z", end: "2026-08-02T10:00:00Z", day: "SUN", time: "09:00", source: "google", calendarId: "primary", calendarName: "Private" }] }, clock: (() => { const values = [new Date(FULL_ASSEMBLY_TIME), new Date("2026-08-01T12:00:01Z")]; return () => values.shift()!; })(), requestedLimit: 5, horizonDays: 7 },
    memory: { read: async () => memory },
    connectorAvailability: { observedAt: FULL_ASSEMBLY_TIME, results: [{ connectorId: "calendar", source: "google", connected: true }, { connectorId: "gmail", source: "google", connected: id !== "connector-disconnected-local-fallback" }, { connectorId: "drive", source: "local", connected: false }] },
  };
}

const compound = (id: FullAssemblyScenarioId) => !["single-contact-no-conflict", "conflict-evaluation-unavailable", "conflict-evaluation-unsupported", "conflict-evaluation-failed", "deterministic-replay"].includes(id);
const expectedOutcome = (id: FullAssemblyScenarioId) => id === "single-contact-no-conflict" || id === "legacy-memory-unattested" || id === "connector-disconnected-local-fallback" || id === "partial-source-failure" ? "evaluated_no_conflict" : id === "deterministic-replay" ? "evaluated_conflict_found" : id === "conflict-evaluation-unavailable" ? "evaluation_unavailable" : id === "conflict-evaluation-unsupported" ? "evaluation_unsupported" : id === "conflict-evaluation-failed" ? "evaluation_failed" : "partially_evaluated";

export async function runFullAssemblyRegressionScenario(scenarioId: FullAssemblyScenarioId): Promise<FullAssemblyRegressionResult> {
  const assembled = await assembleGovernedSourceEvidence(fullAssemblySourceInput(scenarioId));
  const lineage = { threadId: `thread:3.102:${scenarioId}`, requestId: `request:3.102:${scenarioId}`, exchangeId: `exchange:3.102:${scenarioId}` };
  const claims = evaluateClaimBoundary({ text: compound(scenarioId) ? "What's Cassie's email? Anything important?" : "What's Cassie's email?", ...lineage, referenceTime: FULL_ASSEMBLY_TIME, createdAt: FULL_ASSEMBLY_TIME, entities: [{ entityId: "person:cassie", personName: "Cassie", displayLabel: "Cassie" }] });
  if (!claims.claimSet) throw new Error("scenario did not publish a claim set");
  const contact = claims.claimSet.claims.find(claim => claim.claimType === "contact_address_lookup")!;
  const observation = (suffix: string, value: string, overrides: Partial<GovernedSourceObservation> = {}): GovernedSourceObservation => ({ sourcePublicationId: `gmail-evidence:${suffix}`, sourceOwnerId: `gmail-owner:${suffix}`, sourceType: "governed_contact_observation", resourceEntityId: "person:cassie", affectedClaimId: contact.claimId, comparisonKey: "resolved_contact_address", canonicalFactualValue: value, originalFactualValue: value, observedAt: FULL_ASSEMBLY_TIME, publishedAt: FULL_ASSEMBLY_TIME, provenance: `gmail-publisher:${suffix}`, comparisonScope: "current_primary_deliverable_address", availability: "available", coverage: "complete", supersessionStatus: "current", contentKind: "contact_address", schemaVersion: "1", ...overrides });
  let observations: readonly GovernedSourceObservation[] = [observation("a", "cassie.primary@example.com"), observation("b", "CASSIE.PRIMARY@example.com")];
  let ruleset = CONFLICT_EVALUATION_RULESET; let classes: readonly ConversationalConflictClass[] = ["source_value_contradiction"];
  if (["cassie-compound-contact-conflict", "gmail-conflict-plus-unsupported-claim", "deterministic-replay"].includes(scenarioId)) observations = [observation("a", "cassie.primary@example.com"), observation("b", "cassie.other@example.org")];
  if (scenarioId === "conflict-evaluation-unavailable") observations = [observation("a", "", { availability: "unavailable", contentKind: "unavailable_marker" })];
  if (scenarioId === "conflict-evaluation-unsupported") classes = ["policy_incompatibility"];
  if (scenarioId === "conflict-evaluation-failed") observations = [observation("a", "cassie@example.com", { sourceOwnerId: "" })];
  const conflicts = evaluateGovernedConversationalConflicts({ ruleset, claimSet: claims.claimSet, observations, requestedConflictClasses: classes, referenceTime: FULL_ASSEMBLY_TIME, createdAt: FULL_ASSEMBLY_TIME, evaluationDiscriminator: scenarioId });
  if (!conflicts.evaluation) throw new Error("scenario did not publish conflict evaluation");
  const projection = composeGovernedConversationalProjection({ schemaVersion: "1", evidenceRulesetId: "evidence:3.102", compatibilityRulesetId: "compatibility:3.102", claimClassificationRulesetId: claims.evaluation.claimBoundaryRulesetId, claimBoundaryEvaluation: claims.evaluation, governedClaimSet: claims.claimSet, conflictEvaluation: conflicts.evaluation, governedConflictSet: conflicts.conflictSet, ...lineage, referenceTime: FULL_ASSEMBLY_TIME, createdAt: FULL_ASSEMBLY_TIME, sourceEvidence: [], connectorAvailability: assembled.connectorAvailability, calendarEvidence: assembled.calendarEvidence, communicationEvidence: assembled.communicationEvidence, memoryPriorityReferences: assembled.memoryPriorityReferences, compatibilityContext: [], conversationHistory: [], claims: claims.claimSet.claims, conflicts: conflicts.conflictSet?.conflicts.map(constructGovernedConflictSummary) ?? [] });
  const effectiveClaims = projection.claims.map(claim => ({ ...claim, status: projection.effectiveClaimStatuses.find(item => item.claimId === claim.claimId)!.effectiveStatus }));
  const input = constructGovernedConversationalInput({ inputId: lineageIdentity("governed-input", projection.projectionId), ...lineage, projectionId: projection.projectionId, projectionLineage: { ...lineage, projectionId: projection.projectionId }, referenceTime: FULL_ASSEMBLY_TIME, question: { text: compound(scenarioId) ? "What's Cassie's email? Anything important?" : "What's Cassie's email?" }, claims: effectiveClaims, sources: [{ sourceId: "gmail", available: assembled.sourceResults.gmail.status === "available", status: assembled.sourceResults.gmail.status === "available" ? "available" : "unavailable", observedAt: FULL_ASSEMBLY_TIME, provenance: "source-evidence-assembly" }] });
  const adapter: GovernedConversationModelAdapter = { invoke: async () => JSON.stringify({ interpretation: { ownership: "model_interpretation", claimIds: input.claims.map(c => c.claimId), text: "The governed evidence is constrained; no disputed value or unsupported importance is asserted.", evidenceReferences: [], uncertaintyReferences: input.claims.filter(c => c.status !== "available").map(c => c.claimId) } }) };
  const model = await invokeGovernedConversationModel(input, adapter, { attemptId: `attempt:${scenarioId}`, agentId: "deterministic-regression-adapter", completedAt: FULL_ASSEMBLY_TIME, schemaVersion: "2", validationPolicyId: "validation/1", policyReferences: ["validation/1"] });
  const outcomePass = conflicts.evaluation.outcome === expectedOutcome(scenarioId);
  const singleAvailable = scenarioId !== "single-contact-no-conflict" || contact.status === "available";
  const findings: FullAssemblyFinding[] = singleAvailable ? [] : [{ seam: "source assembly → claim boundary", status: "semantic-incompatibility", evidence: "The real claim boundary publishes contact_address_lookup as insufficient_coverage and has no input for assembled governed source evidence.", requiredNextStep: "Govern an evidence-to-claim enrichment/correlation contract; do not repair in this evaluation." }];
  const stages = { assembly: { passed: true, evidence: JSON.stringify(assembled.sourceResults) }, claims: { passed: singleAvailable, evidence: claims.claimSet.claims.map(c => `${c.claimType}:${c.status}`).join(",") }, conflicts: { passed: outcomePass, evidence: conflicts.evaluation.outcome }, projection: { passed: projection.conflictEvaluationOutcome === conflicts.evaluation.outcome, evidence: projection.projectionId }, governedInput: { passed: input.projectionId === projection.projectionId, evidence: input.overallStatus }, modelInvocation: { passed: ["accepted", "validation_failed"].includes(model.modelOutcome), evidence: model.modelOutcome }, validation: { passed: model.validation.outcome === "passed" || model.modelOutcome === "validation_failed", evidence: model.validation.outcome } };
  return Object.freeze({ scenarioId, passed: Object.values(stages).every(stage => stage.passed), stageResults: stages, findings, identities: { ...lineage, projectionId: projection.projectionId, claimBoundaryRulesetId: projection.claimBoundaryRulesetId, claimBoundaryEvaluationId: projection.claimBoundaryEvaluationId, governedClaimSetId: projection.governedClaimSetId, conflictEvaluationRulesetId: projection.conflictEvaluationRulesetId, conflictEvaluationId: projection.conflictEvaluationId, governedConflictSetId: projection.governedConflictSetId, responseEnvelopeId: model.envelope.envelopeId, executionRecordId: model.executionRecord.executionRecordId }, statuses: { sourceResults: assembled.sourceResults, conflictEvaluationOutcome: projection.conflictEvaluationOutcome, effectiveClaimStatuses: projection.effectiveClaimStatuses, memoryPriorityCount: projection.memoryPriorityReferences.length, connectorAvailability: projection.connectorAvailability } });
}

export async function runFullAssemblyRegressionMatrix() { return Promise.all(FULL_ASSEMBLY_SCENARIO_IDS.map(runFullAssemblyRegressionScenario)); }
