import { constructClaimBoundaryEvaluation, constructGovernedClaimSet } from "./claim-boundary-publications";
import { constructConflictEvaluation, constructGovernedConflictSet } from "./conflict-boundary-publications";
import type { GovernedClaimInput } from "./types";

export function publicationChainForClaims(claims: readonly GovernedClaimInput[], lineage: { threadId: string; requestId: string; exchangeId: string; referenceTime: string }, discriminator = "projection-fixture") {
  const claimBoundaryRulesetId = `claim-boundary-ruleset:${discriminator}`;
  const claimBoundaryEvaluation = constructClaimBoundaryEvaluation({ schemaVersion: "1", claimBoundaryRulesetId, ...lineage, inputDigest: `digest:${discriminator}`, typedIntentResult: "not_supplied", matchedRuleIds: [], matchedSpans: [], extractedParameters: [], segmentation: claims.map((_, index) => ({ segmentId: `segment:${index}`, start: index, end: index + 1, disposition: "governed" as const })), outcome: claims.length ? "recognised" : "no_governed_factual_claim", createdAt: lineage.referenceTime }, `claim-evaluation:${discriminator}`);
  const governedClaimSet = constructGovernedClaimSet({ schemaVersion: "1", claimBoundaryEvaluationId: claimBoundaryEvaluation.claimBoundaryEvaluationId, claimBoundaryRulesetId, ...lineage, claims, segmentLinks: claims.map((claim, index) => ({ segmentId: `segment:${index}`, claimId: claim.claimId })), createdAt: lineage.referenceTime }, `claim-set:${discriminator}`);
  if (!claims.length) return { claimBoundaryEvaluation, governedClaimSet, claimClassificationRulesetId: claimBoundaryRulesetId };
  const conflictEvaluationRulesetId = `conflict-evaluation-ruleset:${discriminator}`;
  const body = { schemaVersion: "1" as const, conflictEvaluationRulesetId, governedClaimSetId: governedClaimSet.governedClaimSetId, evaluatedClaimIds: claims.map(claim => claim.claimId), requestedConflictClasses: ["source_value_contradiction" as const], executableConflictClasses: ["source_value_contradiction" as const], sourcePublicationReferences: [], sourceOwnerIds: [], sourceAvailabilityReferences: [], sourceCoverageReferences: [], referenceTime: lineage.referenceTime, cellEvaluations: claims.map(claim => ({ claimId: claim.claimId, conflictClass: "source_value_contradiction" as const, comparisonScope: "fixture", result: "no_match" as const, coverage: "complete" as const })), outcome: "evaluated_no_conflict" as const, unevaluatedReasons: [], createdAt: lineage.referenceTime, threadId: lineage.threadId, requestId: lineage.requestId, exchangeId: lineage.exchangeId };
  const initial = constructConflictEvaluation(body, `conflict-evaluation:${discriminator}`);
  const governedConflictSet = constructGovernedConflictSet({ schemaVersion: "1", conflictEvaluationId: initial.conflictEvaluationId, conflictEvaluationRulesetId, governedClaimSetId: governedClaimSet.governedClaimSetId, evaluatedClaimIds: claims.map(claim => claim.claimId), evaluatedClasses: ["source_value_contradiction"], sourcePublicationReferences: [], evaluationCoverage: "complete", conflicts: [], createdAt: lineage.referenceTime });
  const conflictEvaluation = constructConflictEvaluation({ ...body, conflictSetId: governedConflictSet.governedConflictSetId }, `conflict-evaluation:${discriminator}`);
  return { claimBoundaryEvaluation, governedClaimSet, claimClassificationRulesetId: claimBoundaryRulesetId, conflictEvaluation, governedConflictSet };
}
