import { lineageIdentity } from "./lineage-types";
import type { ConversationalExecutionRecord, ConversationalExchange, ConversationalRequest, ConversationalRequestRejectionRecord, ConversationalThread, ModelInvocationAttempt, ValidatedConversationalResponseEnvelopeReference } from "./lineage-types";
import type { ConversationalLifecycleEvent } from "./exchange-lifecycle";
import type { GovernedConversationalProjection, GovernedInputReference } from "./projection-composer";
import type { CommitFailure, CommitResult, ConversationalExchangeAggregate, ConversationalLineageRepository } from "./lineage-repository";

type Operation = "createThread" | "closeThread" | "commitAcceptedRequest" | "commitRequestRejection" | "createExchange" | "commitProjection" | "startAttempt" | "completeAttempt" | "commitValidatedEnvelope" | "transitionExchange" | "commitTerminalRecord";
export interface InMemoryRepositoryOptions { readonly now?: () => string; readonly fail?: (operation: Operation) => boolean }
type MutableAggregate = { exchange: ConversationalExchange; projection?: GovernedConversationalProjection; governedInputReference?: GovernedInputReference; attempts: ModelInvocationAttempt[]; envelope?: ValidatedConversationalResponseEnvelopeReference; lifecycleEvents: ConversationalLifecycleEvent[]; terminalRecord?: ConversationalExecutionRecord };
const copy = <T>(value: T): T => Object.freeze(structuredClone(value)) as T;
export class InMemoryConversationalLineageRepository implements ConversationalLineageRepository {
  private readonly threads = new Map<string, ConversationalThread>(); private readonly requests = new Map<string, ConversationalRequest>(); private readonly rejections = new Map<string, ConversationalRequestRejectionRecord>(); private readonly exchanges = new Map<string, MutableAggregate>(); private readonly idempotency = new Map<string, string>(); private readonly requestExchange = new Map<string, string>(); private commitOrdinal = 0;
  constructor(private readonly options: InMemoryRepositoryOptions = {}) {}
  private result(operation: Operation, failure?: CommitFailure, detail = ""): CommitResult { if (this.options.fail?.(operation)) return { committed: false, failure: "repository_unavailable", detail: `${operation} unavailable` }; if (failure) return { committed: false, failure, detail }; const committedAt = this.options.now?.() ?? "1970-01-01T00:00:00.000Z"; this.commitOrdinal += 1; return { committed: true, commitId: lineageIdentity("in-memory-lineage-commit", { operation, committedAt, ordinal: this.commitOrdinal }), committedAt }; }
  async createThread(thread: ConversationalThread) { const ready = this.result("createThread", this.threads.has(thread.threadId) ? "duplicate" : undefined, "thread already exists"); if (ready.committed) this.threads.set(thread.threadId, copy(thread)); return ready; }
  async closeThread(threadId: string, closedAt: string) { const thread = this.threads.get(threadId); const ready = this.result("closeThread", !thread || thread.status === "closed" ? "conflict" : undefined, "thread cannot be closed"); if (ready.committed && thread) this.threads.set(threadId, copy({ ...thread, status: "closed" as const, closedAt })); return ready; }
  async commitAcceptedRequest(request: ConversationalRequest) { const existing = request.idempotencyKey && this.idempotency.get(request.idempotencyKey); const failure = !this.threads.has(request.threadId) ? "lineage_mismatch" : existing && existing !== request.requestId ? "conflict" : this.requests.has(request.requestId) ? "duplicate" : undefined; const ready = this.result("commitAcceptedRequest", failure, "request lineage or identity is invalid"); if (ready.committed) { this.requests.set(request.requestId, copy(request)); if (request.idempotencyKey) this.idempotency.set(request.idempotencyKey, request.requestId); } return ready; }
  async commitRequestRejection(rejection: ConversationalRequestRejectionRecord) { const ready = this.result("commitRequestRejection", this.rejections.has(rejection.rejectionId) ? "duplicate" : undefined, "rejection exists"); if (ready.committed) this.rejections.set(rejection.rejectionId, copy(rejection)); return ready; }
  async createExchange(exchange: ConversationalExchange) { const request = this.requests.get(exchange.requestId); const failure = !request || request.threadId !== exchange.threadId ? "lineage_mismatch" : this.requestExchange.has(exchange.requestId) ? "conflict" : this.exchanges.has(exchange.exchangeId) ? "duplicate" : undefined; const ready = this.result("createExchange", failure, "one accepted request maps to one exchange"); if (ready.committed) { this.exchanges.set(exchange.exchangeId, { exchange: copy(exchange), attempts: [], lifecycleEvents: [] }); this.requestExchange.set(exchange.requestId, exchange.exchangeId); } return ready; }
  async commitProjection(exchangeId: string, projection: GovernedConversationalProjection, governedInputReference: GovernedInputReference) { const aggregate = this.exchanges.get(exchangeId); const mismatch = !aggregate || projection.exchangeId !== exchangeId || projection.requestId !== aggregate.exchange.requestId || projection.threadId !== aggregate.exchange.threadId || governedInputReference.exchangeId !== exchangeId || governedInputReference.projectionId !== projection.projectionId; const ready = this.result("commitProjection", mismatch ? "lineage_mismatch" : aggregate?.projection ? "duplicate" : undefined, "projection lineage is invalid"); if (ready.committed && aggregate) { aggregate.projection = copy(projection); aggregate.governedInputReference = copy(governedInputReference); } return ready; }
  async startAttempt(attempt: ModelInvocationAttempt) { const aggregate = this.exchanges.get(attempt.exchangeId); const expected = (aggregate?.attempts.length ?? 0) + 1; const prior = aggregate?.attempts.at(-1); const invalid = !aggregate?.projection || attempt.governedInputId !== aggregate.governedInputReference?.governedInputId || attempt.ordinal !== expected || (expected > 1 && attempt.parentAttemptId !== prior?.attemptId); const ready = this.result("startAttempt", invalid ? "lineage_mismatch" : undefined, "attempt requires ordered committed input lineage"); if (ready.committed && aggregate) aggregate.attempts.push(copy(attempt)); return ready; }
  async completeAttempt(attempt: ModelInvocationAttempt) { const aggregate = this.exchanges.get(attempt.exchangeId); const index = aggregate?.attempts.findIndex((item) => item.attemptId === attempt.attemptId) ?? -1; const invalid = index < 0 || aggregate?.attempts[index].outcome !== "started" || attempt.outcome === "started"; const ready = this.result("completeAttempt", invalid ? "lineage_mismatch" : undefined, "attempt result does not match a started attempt"); if (ready.committed && aggregate) aggregate.attempts[index] = copy(attempt); return ready; }
  async commitValidatedEnvelope(envelope: ValidatedConversationalResponseEnvelopeReference) { const aggregate = this.exchanges.get(envelope.exchangeId); const failure = !aggregate || envelope.governedInputId !== aggregate.governedInputReference?.governedInputId ? "lineage_mismatch" : aggregate.envelope ? "duplicate" : aggregate.exchange.currentState !== "validation_passed" && aggregate.exchange.currentState !== "safe_response_created" ? "invalid_transition" : undefined; const ready = this.result("commitValidatedEnvelope", failure, "accepted envelope requires validated exchange lineage"); if (ready.committed && aggregate) aggregate.envelope = copy(envelope); return ready; }
  async transitionExchange(event: ConversationalLifecycleEvent) { const aggregate = this.exchanges.get(event.exchangeId); const failure = !aggregate || aggregate.exchange.currentState !== event.from ? "invalid_transition" : aggregate.terminalRecord ? "invalid_transition" : event.to === "completed" && (!aggregate.envelope || !aggregate.terminalRecord) ? "invalid_transition" : undefined; const ready = this.result("transitionExchange", failure, "exchange transition is not current or terminal requirements are missing"); if (ready.committed && aggregate) { aggregate.exchange = copy({ ...aggregate.exchange, currentState: event.to }); aggregate.lifecycleEvents.push(copy(event)); } return ready; }
  async commitTerminalRecord(record: ConversationalExecutionRecord) { const aggregate = this.exchanges.get(record.exchangeId); const expectedPreterminal = record.terminalState === "completed" ? ["validation_passed", "safe_response_created"].includes(aggregate?.exchange.currentState ?? "") : aggregate && aggregate.exchange.currentState !== "completed" && aggregate.exchange.currentState !== "failed"; const lineage = aggregate && record.threadId === aggregate.exchange.threadId && record.requestId === aggregate.exchange.requestId && record.attemptIds.every((id) => aggregate.attempts.some((attempt) => attempt.attemptId === id)); const envelope = record.terminalState === "completed" ? aggregate?.envelope?.responseEnvelopeId === record.acceptedEnvelopeId : !record.acceptedEnvelopeId; const failure = !aggregate || !lineage || !expectedPreterminal || !envelope ? "lineage_mismatch" : aggregate.terminalRecord ? "terminal_record_exists" : undefined; const ready = this.result("commitTerminalRecord", failure, "terminal record lineage or prerequisites are invalid"); if (ready.committed && aggregate) { aggregate.terminalRecord = copy(record); aggregate.exchange = copy({ ...aggregate.exchange, currentState: record.terminalState }); } return ready; }
  async getThread(id: string) { const value = this.threads.get(id); return value ? copy(value) : null; } async getRequest(id: string) { const value = this.requests.get(id); return value ? copy(value) : null; } async getExchange(id: string): Promise<ConversationalExchangeAggregate | null> { const value = this.exchanges.get(id); return value ? copy(value) : null; } async getByIdempotencyKey(key: string) { const id = this.idempotency.get(key); return id ? this.getRequest(id) : null; }
}
