import { describe, expect, it } from "vitest";
import { constructConversationalExecutionRecord, constructConversationalExchange, constructConversationalRequest, constructConversationalThread, constructModelInvocationAttempt, constructRequestRejection, constructValidatedEnvelopeReference } from "./lineage-types";
import { lineage, time } from "./lineage-test-fixtures";
describe("conversational lineage identities", () => {
  it("creates stable event identities without raw content or implied descendants", () => { const { thread, request, exchange } = lineage(); expect(thread).not.toHaveProperty("exchangeId"); expect(request).not.toHaveProperty("rawText"); expect(exchange.currentState).toBe("created"); expect(Object.isFrozen(exchange)).toBe(true); expect(lineage().exchange.exchangeId).toBe(exchange.exchangeId); });
  it("distinguishes later requests and deliberate thread forks", () => { const { thread } = lineage(); const later = constructConversationalRequest({ schemaVersion: "1", threadId: thread.threadId, acceptedAt: time, requestContentReference: "content:1", requestDigest: "digest:question", eventDiscriminator: "later" }); const fork = constructConversationalThread({ schemaVersion: "1", openedAt: time, continuityPolicyId: "continuity/1", optionalParentThreadId: thread.threadId, eventDiscriminator: "fork" }); expect(later.requestId).not.toBe(lineage().request.requestId); expect(fork.threadId).not.toBe(thread.threadId); });
  it("enforces accepted request, attempt, validation, and terminal preconditions", () => { const { thread, request, exchange } = lineage(); expect(() => constructConversationalExchange({ ...exchange, acceptedRequest: { ...request, requestId: "wrong" }, eventDiscriminator: "bad" })).toThrow(); expect(() => constructModelInvocationAttempt({ schemaVersion: "1", exchangeId: exchange.exchangeId, governedInputId: "input", ordinal: 2, startedAt: time, providerConfigurationReference: "provider", projectionCommitted: true, eventDiscriminator: "bad" })).toThrow(); expect(() => constructValidatedEnvelopeReference({ schemaVersion: "1", exchangeId: exchange.exchangeId, governedInputId: "input", validationPolicyId: "v", validationResultId: "r", envelopeDigest: "d", envelopeKind: "model_response", validatedAt: time, validationOutcome: "failed" as "passed" })).toThrow(); expect(() => constructConversationalExecutionRecord({ schemaVersion: "1", threadId: thread.threadId, requestId: request.requestId, exchangeId: exchange.exchangeId, attemptIds: [], acceptedEnvelopeId: "envelope", finalDisposition: "failed", terminalState: "failed", createdAt: time, completedAt: time, policyReferences: [], sourceReferences: [], eventDiscriminator: "bad" })).toThrow(); });
  it("keeps pre-acceptance rejection outside exchange lineage", () => { const rejection = constructRequestRejection({ schemaVersion: "1", receivedAt: time, rejectionCode: "INVALID_SHAPE", eventDiscriminator: "reject" }); expect(rejection).not.toHaveProperty("exchangeId"); });
});
