import { describe, expect, it } from "vitest"; import { InMemoryConversationalLineageRepository, type InMemoryRepositoryOptions } from "./in-memory-lineage-repository"; import { ConversationalLineageOrchestrator } from "./lineage-orchestrator"; import { composeGovernedConversationalProjection, constructGovernedInputReference } from "./projection-composer"; import { constructConversationalExecutionRecord, constructModelInvocationAttempt, constructValidatedEnvelopeReference } from "./lineage-types"; import { lineage, projectionInput, time } from "./lineage-test-fixtures";
async function scenario(fail?: InMemoryRepositoryOptions["fail"], validationPassed=true){const events:string[]=[]; const {thread,request,exchange}=lineage(); const projection=composeGovernedConversationalProjection(projectionInput(exchange)); const governed=constructGovernedInputReference(projection); const attempt=constructModelInvocationAttempt({schemaVersion:"1",exchangeId:exchange.exchangeId,governedInputId:governed.governedInputId,ordinal:1,startedAt:time,providerConfigurationReference:"provider",projectionCommitted:true,eventDiscriminator:"attempt"}); const repository=new InMemoryConversationalLineageRepository({now:()=>time,fail}); await repository.createThread(thread); const makeEnvelope=(kind:"model_response"|"safe_response")=>constructValidatedEnvelopeReference({schemaVersion:"1",exchangeId:exchange.exchangeId,governedInputId:governed.governedInputId,validationPolicyId:"validation/1",validationResultId:`validation:${kind}`,envelopeDigest:`digest:${kind}`,envelopeKind:kind,validatedAt:time,validationOutcome:"passed"}); const orchestrator=new ConversationalLineageOrchestrator({repository,composeProjection:composeGovernedConversationalProjection,now:()=>time,invokeModel:async current=>{events.push("model"); return {completedAttempt:{...current,outcome:"output_received",completedAt:time,outputDigest:"output"},candidate:{}};},validateEnvelope:async()=>validationPassed?{passed:true,envelope:makeEnvelope("model_response")}:{passed:false},constructSafeEnvelope:async()=>makeEnvelope("safe_response"),releaseResponse:async()=>{events.push("release");}}); const result=await orchestrator.execute({request,exchange,projectionInput:projectionInput(exchange),attempt,constructTerminalRecord:({projection:made,governedInput,completedAttempt,envelope,safe})=>constructConversationalExecutionRecord({schemaVersion:"1",threadId:thread.threadId,requestId:request.requestId,exchangeId:exchange.exchangeId,projectionId:made.projectionId,governedInputId:governedInput.governedInputId,attemptIds:[completedAttempt.attemptId],acceptedEnvelopeId:envelope.responseEnvelopeId,finalDisposition:safe?"completed_safe_response":"completed",terminalState:"completed",validationOutcome:safe?"failed":"passed",createdAt:time,completedAt:time,policyReferences:["validation/1"],sourceReferences:["gmail"],eventDiscriminator:"terminal"})}); return {result,events,aggregate:await repository.getExchange(exchange.exchangeId)};}
describe("fail-closed lineage orchestration",()=>{
  it("commits both terminal publications before response release",async()=>{const {result,events,aggregate}=await scenario(); expect(result.released).toBe(true); expect(events).toEqual(["model","release"]); expect(aggregate?.envelope).toBeDefined(); expect(aggregate?.terminalRecord).toBeDefined(); expect(aggregate?.exchange.currentState).toBe("completed");});
  it("supports a validated safe-response completion distinct from model success",async()=>{const {result,aggregate}=await scenario(undefined,false); expect(result.released).toBe(true); expect(aggregate?.envelope?.envelopeKind).toBe("safe_response"); expect(aggregate?.terminalRecord?.finalDisposition).toBe("completed_safe_response");});
  it.each([
    ["commitAcceptedRequest",false],["createExchange",false],["commitProjection",false],["startAttempt",false],["completeAttempt",true],["commitValidatedEnvelope",true],["commitTerminalRecord",true]
  ] as const)("blocks later action when %s fails",async(operation,modelOccurred)=>{const {result,events,aggregate}=await scenario(op=>op===operation); expect(result.released).toBe(false); expect(events.includes("model")).toBe(modelOccurred); expect(events).not.toContain("release"); expect(aggregate?.terminalRecord).toBeUndefined(); expect(aggregate?.exchange.currentState).not.toBe("completed"); expect(result.failureCategory).toBe("persistence");});
});
