import { createHash } from "node:crypto";
import type { ConversationalExchangeState, ConversationalFailureCategory } from "./exchange-lifecycle";
import type { ClaimOwnership, ConversationalEvidenceStatus, GovernedSourceReference } from "./types";

export interface RealEosContextReference { readonly publicationId: string; readonly publicationType: string; readonly schemaVersion: string; readonly genuinePublication: true }
export interface ConversationalThread { readonly threadId: string; readonly schemaVersion: string; readonly openedAt: string; readonly status: "open" | "closed"; readonly closedAt?: string; readonly continuityPolicyId: string; readonly optionalAgentContext?: string; readonly optionalParentThreadId?: string }
export interface ConversationalRequest { readonly requestId: string; readonly schemaVersion: string; readonly threadId: string; readonly acceptedAt: string; readonly requestContentReference: string; readonly requestDigest: string; readonly idempotencyKey?: string; readonly operatorIdentityReference?: string; readonly agentId?: string }
export interface ConversationalExchange { readonly exchangeId: string; readonly schemaVersion: string; readonly threadId: string; readonly requestId: string; readonly createdAt: string; readonly currentState: ConversationalExchangeState; readonly referenceTime: string; readonly validationPolicyId: string; readonly evidencePolicyId: string; readonly retryPolicyId: string; readonly optionalReplayOfExchangeId?: string; readonly optionalRealEosReferences?: readonly RealEosContextReference[] }
export type ModelInvocationAttemptOutcome = "started" | "output_received" | "provider_failed" | "parse_failed" | "validation_failed" | "accepted";
export interface ModelInvocationAttempt { readonly attemptId: string; readonly schemaVersion: string; readonly exchangeId: string; readonly governedInputId: string; readonly ordinal: number; readonly startedAt: string; readonly completedAt?: string; readonly providerConfigurationReference: string; readonly outcome: ModelInvocationAttemptOutcome; readonly parentAttemptId?: string; readonly outputDigest?: string; readonly failureCode?: string }
export interface ValidatedConversationalResponseEnvelopeReference { readonly responseEnvelopeId: string; readonly schemaVersion: string; readonly exchangeId: string; readonly governedInputId: string; readonly validationPolicyId: string; readonly validationResultId: string; readonly envelopeDigest: string; readonly envelopeKind: "model_response" | "safe_response"; readonly validatedAt: string }
export interface ConversationalExecutionRecord { readonly executionRecordId: string; readonly schemaVersion: string; readonly threadId: string; readonly requestId: string; readonly exchangeId: string; readonly projectionId?: string; readonly governedInputId?: string; readonly runId?: string; readonly sessionId?: string; readonly interfaceContractId?: string; readonly attemptIds: readonly string[]; readonly acceptedEnvelopeId?: string; readonly finalDisposition: "completed" | "completed_safe_response" | "failed"; readonly terminalState: "completed" | "failed"; readonly validationOutcome?: "passed" | "failed"; readonly validatorVersion?: string; readonly failureCategory?: ConversationalFailureCategory; readonly failureCode?: string; readonly createdAt: string; readonly completedAt: string; readonly policyReferences: readonly string[]; readonly sourceReferences: readonly (string | GovernedSourceReference)[]; readonly sourceAvailability?: Readonly<Record<string, boolean>>; readonly evidenceStatusSummary?: Readonly<Record<ConversationalEvidenceStatus, number>>; readonly claimStatusSummary?: readonly Readonly<{ claimId: string; status: ConversationalEvidenceStatus }>[]; readonly retrievalPolicyDecisionReferences?: readonly string[]; readonly ownershipSummary?: Readonly<Record<ClaimOwnership, number>>; readonly refusalOutcome?: string | null; readonly segmentSummary?: Readonly<{ deterministic: number; modelOwned: number }>; readonly agentId?: string; readonly modelExecutionMetadataReferences?: readonly string[] }
export interface ConversationalRequestRejectionRecord { readonly rejectionId: string; readonly schemaVersion: string; readonly receivedAt: string; readonly rejectionCode: string; readonly requestDigest?: string; readonly idempotencyKey?: string }

export function canonicalise(value: unknown): string {
  if (Array.isArray(value)) return `[${value.map(canonicalise).join(",")}]`;
  if (value && typeof value === "object") return `{${Object.entries(value as Record<string, unknown>).filter(([, item]) => item !== undefined).sort(([a], [b]) => a.localeCompare(b)).map(([key, item]) => `${JSON.stringify(key)}:${canonicalise(item)}`).join(",")}}`;
  return JSON.stringify(value);
}
export const lineageIdentity = (prefix: string, body: unknown): string => `${prefix}:${createHash("sha256").update(canonicalise(body), "utf8").digest("hex")}`;
const freeze = <T>(value: T): Readonly<T> => Object.freeze(structuredClone(value));
function required(condition: unknown, message: string): asserts condition { if (!condition) throw new Error(message); }
const instant = (value: string, field: string) => required(value.length > 0 && !Number.isNaN(Date.parse(value)), `${field} must be an ISO instant`);

export type ThreadConstruction = Omit<ConversationalThread, "threadId" | "status"> & { readonly eventDiscriminator: string; readonly status?: "open" };
export function constructConversationalThread(input: ThreadConstruction): ConversationalThread { instant(input.openedAt, "openedAt"); required(input.eventDiscriminator, "eventDiscriminator is required"); required(input.continuityPolicyId, "continuityPolicyId is required"); const { eventDiscriminator, ...body } = input; return freeze({ ...body, status: "open", threadId: lineageIdentity("conversational-thread", { ...body, eventDiscriminator }) }); }
export type RequestConstruction = Omit<ConversationalRequest, "requestId"> & { readonly eventDiscriminator: string };
export function constructConversationalRequest(input: RequestConstruction): ConversationalRequest { instant(input.acceptedAt, "acceptedAt"); required(input.threadId && input.requestContentReference && input.requestDigest && input.eventDiscriminator, "accepted request lineage and event discriminator are required"); const { eventDiscriminator, ...body } = input; return freeze({ ...body, requestId: lineageIdentity("conversational-request", { ...body, eventDiscriminator }) }); }
export type ExchangeConstruction = Omit<ConversationalExchange, "exchangeId" | "currentState"> & { readonly acceptedRequest: ConversationalRequest; readonly eventDiscriminator: string };
export function constructConversationalExchange(input: ExchangeConstruction): ConversationalExchange { const { acceptedRequest, eventDiscriminator, ...body } = input; required(eventDiscriminator && acceptedRequest.requestId === body.requestId && acceptedRequest.threadId === body.threadId, "exchange requires its accepted request lineage"); instant(body.createdAt, "createdAt"); instant(body.referenceTime, "referenceTime"); return freeze({ ...body, currentState: "created", exchangeId: lineageIdentity("conversational-exchange", { ...body, eventDiscriminator }) }); }
export type AttemptConstruction = Omit<ModelInvocationAttempt, "attemptId" | "outcome"> & { readonly projectionCommitted: true; readonly eventDiscriminator: string; readonly outcome?: "started" };
export function constructModelInvocationAttempt(input: AttemptConstruction): ModelInvocationAttempt { const { projectionCommitted, eventDiscriminator, ...body } = input; required(projectionCommitted && eventDiscriminator && body.ordinal >= 1 && Number.isInteger(body.ordinal), "attempt requires committed input, ordinal, and event discriminator"); required(body.ordinal === 1 ? !body.parentAttemptId : Boolean(body.parentAttemptId), "attempt parent linkage does not match ordinal"); instant(body.startedAt, "startedAt"); return freeze({ ...body, outcome: "started", attemptId: lineageIdentity("model-invocation-attempt", { ...body, eventDiscriminator }) }); }
export type EnvelopeReferenceConstruction = Omit<ValidatedConversationalResponseEnvelopeReference, "responseEnvelopeId"> & { readonly validationOutcome: "passed" };
export function constructValidatedEnvelopeReference(input: EnvelopeReferenceConstruction): ValidatedConversationalResponseEnvelopeReference { const { validationOutcome, ...body } = input; required(validationOutcome === "passed" && body.validationResultId && body.envelopeDigest, "validated envelope requires passed validation"); instant(body.validatedAt, "validatedAt"); return freeze({ ...body, responseEnvelopeId: lineageIdentity("validated-conversational-response-envelope", body) }); }
export type ExecutionRecordConstruction = Omit<ConversationalExecutionRecord, "executionRecordId"> & { readonly eventDiscriminator: string };
export function constructConversationalExecutionRecord(input: ExecutionRecordConstruction): ConversationalExecutionRecord { const { eventDiscriminator, ...body } = input; required(eventDiscriminator && (body.terminalState === "completed" || body.terminalState === "failed"), "execution record requires a terminal exchange"); required((body.terminalState === "failed") === (body.finalDisposition === "failed"), "terminal state and disposition must agree"); required(body.finalDisposition === "failed" ? !body.acceptedEnvelopeId : Boolean(body.acceptedEnvelopeId), "accepted envelope does not match disposition"); required(body.finalDisposition !== "completed_safe_response" || body.validationOutcome === "failed", "safe response must record failed model validation"); return freeze({ ...body, executionRecordId: lineageIdentity("conversational-execution-record", { ...body, eventDiscriminator }) }); }
export function constructRequestRejection(input: Omit<ConversationalRequestRejectionRecord, "rejectionId"> & { readonly eventDiscriminator: string }): ConversationalRequestRejectionRecord { const { eventDiscriminator, ...body } = input; required(eventDiscriminator && body.rejectionCode, "rejection event semantics are required"); return freeze({ ...body, rejectionId: lineageIdentity("conversational-request-rejection", { ...body, eventDiscriminator }) }); }
