import type { CompatibilityContext, GovernedClaimInput, GovernedConflict, GovernedConversationTurn, GovernedSourceReference } from "./types";
import { lineageIdentity, type RealEosContextReference } from "./lineage-types";

export interface GovernedPublicationReference { readonly publicationId: string; readonly publicationType: string; readonly schemaVersion: string }
export interface GovernedSourceEvidenceInput { readonly sourceReference: GovernedSourceReference; readonly publicationReference: GovernedPublicationReference; readonly available: boolean; readonly status: "available" | "insufficient_coverage" | "unavailable" | "unsupported"; readonly provenanceReference: string; readonly retrievalTime: string; readonly contentDigest?: string; readonly contentKind: string; readonly policyReference: string }
export interface GovernedConnectorAvailabilityInput { readonly connectorId: string; readonly sourceId: string; readonly availability: "available" | "unavailable" | "unauthorised"; readonly observedAt: string; readonly causeCode?: string; readonly fallbackStatus: "none" | "governed_fallback" | "unavailable" }
export interface GovernedCalendarEvidenceInput { readonly commitmentReference: string; readonly sourceReference: GovernedSourceReference; readonly start: string; readonly end: string; readonly timezone: string; readonly provenanceReference: string; readonly available: boolean; readonly coverageLimit: string; readonly policyReference: string }
export interface GovernedCommunicationEvidenceInput { readonly communicationReference: string; readonly recipientEvidenceReference: string; readonly sourceReference: GovernedSourceReference; readonly provenanceReference: string; readonly retrievalTime: string; readonly available: boolean; readonly contentDigest?: string; readonly contentKind: string; readonly compatibilityBoundary: string; readonly policyReference: string }
export interface GovernedMemoryPriorityReference { readonly memoryReference: string; readonly sourceOwner: string; readonly freshness: string; readonly available: boolean; readonly classification: "operator_priority" | "derived_interpretation"; readonly policyReference: string; readonly contentDigest?: string }
export interface GovernedConflictInput { readonly conflictId: string; readonly sourceOwners: readonly string[]; readonly affectedClaimIds: readonly string[]; readonly statusRestriction: "insufficient_coverage" | "unavailable" | "unsupported"; readonly descriptionReference: string }
export interface GovernedConversationalProjectionInput { readonly schemaVersion: string; readonly evidenceRulesetId: string; readonly compatibilityRulesetId: string; readonly claimClassificationRulesetId: string; readonly threadId: string; readonly requestId: string; readonly exchangeId: string; readonly referenceTime: string; readonly createdAt: string; readonly sourceEvidence: readonly GovernedSourceEvidenceInput[]; readonly connectorAvailability: readonly GovernedConnectorAvailabilityInput[]; readonly calendarEvidence: readonly GovernedCalendarEvidenceInput[]; readonly communicationEvidence: readonly GovernedCommunicationEvidenceInput[]; readonly memoryPriorityReferences: readonly GovernedMemoryPriorityReference[]; readonly compatibilityContext: readonly CompatibilityContext[]; readonly conversationHistory: readonly GovernedConversationTurn[]; readonly claims: readonly GovernedClaimInput[]; readonly conflicts: readonly GovernedConflictInput[]; readonly optionalApplicationContextReferences?: readonly string[]; readonly optionalRealEosReferences?: readonly RealEosContextReference[] }
export interface GovernedConversationalProjection { readonly projectionId: string; readonly schemaVersion: string; readonly evidenceRulesetId: string; readonly compatibilityRulesetId: string; readonly claimClassificationRulesetId: string; readonly threadId: string; readonly requestId: string; readonly exchangeId: string; readonly referenceTime: string; readonly createdAt: string; readonly upstreamPublicationReferences: readonly GovernedPublicationReference[]; readonly sourceEvidenceReferences: readonly GovernedSourceEvidenceInput[]; readonly connectorAvailability: readonly GovernedConnectorAvailabilityInput[]; readonly calendarEvidence: readonly GovernedCalendarEvidenceInput[]; readonly communicationEvidence: readonly GovernedCommunicationEvidenceInput[]; readonly memoryPriorityReferences: readonly GovernedMemoryPriorityReference[]; readonly compatibilityContext: readonly CompatibilityContext[]; readonly conversationHistory: readonly GovernedConversationTurn[]; readonly claims: readonly GovernedClaimInput[]; readonly conflicts: readonly GovernedConflictInput[]; readonly optionalApplicationContextReferences: readonly string[]; readonly optionalRealEosReferences: readonly RealEosContextReference[] }

function assertProjection(input: GovernedConversationalProjectionInput): void {
  if (!input.threadId || !input.requestId || !input.exchangeId || input.exchangeId === input.optionalRealEosReferences?.find((x) => x.publicationId === input.exchangeId)?.publicationId) throw new Error("distinct conversational lineage is required");
  if (!input.schemaVersion || !input.evidenceRulesetId || !input.compatibilityRulesetId || !input.claimClassificationRulesetId) throw new Error("projection ruleset identities are required");
  if (input.connectorAvailability.some((item) => !item.availability || !item.observedAt)) throw new Error("connector availability is required");
  const claimIds = input.claims.map((claim) => claim.claimId); if (new Set(claimIds).size !== claimIds.length) throw new Error("duplicate claim identity");
  const sourceKeys = new Set(input.sourceEvidence.map((item) => `${item.sourceReference.sourceId}|${item.sourceReference.resourceId}|${item.sourceReference.field}|${item.sourceReference.observedAt}`));
  for (const claim of input.claims) for (const reference of claim.sourceReferences) if (!sourceKeys.has(`${reference.sourceId}|${reference.resourceId}|${reference.field}|${reference.observedAt}`)) throw new Error("claim references unknown governed source");
  if (input.conflicts.some((conflict) => conflict.affectedClaimIds.some((id) => !claimIds.includes(id)))) throw new Error("conflict references unknown claim");
  if (input.conversationHistory.some((turn) => turn.canonicalEvidence !== false)) throw new Error("conversation history is non-canonical");
  if (input.compatibilityContext.some((context) => context.authority !== "none")) throw new Error("compatibility context has no evidence authority");
  if (input.optionalRealEosReferences?.some((reference) => reference.genuinePublication !== true)) throw new Error("synthetic EOS references are prohibited");
}
export function composeGovernedConversationalProjection(input: GovernedConversationalProjectionInput): GovernedConversationalProjection {
  assertProjection(input);
  const body = { schemaVersion: input.schemaVersion, evidenceRulesetId: input.evidenceRulesetId, compatibilityRulesetId: input.compatibilityRulesetId, claimClassificationRulesetId: input.claimClassificationRulesetId, threadId: input.threadId, requestId: input.requestId, exchangeId: input.exchangeId, referenceTime: input.referenceTime, createdAt: input.createdAt, upstreamPublicationReferences: input.sourceEvidence.map((item) => item.publicationReference), sourceEvidenceReferences: input.sourceEvidence, connectorAvailability: input.connectorAvailability, calendarEvidence: input.calendarEvidence, communicationEvidence: input.communicationEvidence, memoryPriorityReferences: input.memoryPriorityReferences, compatibilityContext: input.compatibilityContext, conversationHistory: input.conversationHistory, claims: input.claims, conflicts: input.conflicts, optionalApplicationContextReferences: input.optionalApplicationContextReferences ?? [], optionalRealEosReferences: input.optionalRealEosReferences ?? [] };
  return Object.freeze(structuredClone({ projectionId: lineageIdentity("governed-conversational-projection", body), ...body }));
}

export interface GovernedInputReference { readonly governedInputId: string; readonly projectionId: string; readonly requestId: string; readonly exchangeId: string; readonly referenceTime: string; readonly schemaVersion: string }
export function constructGovernedInputReference(projection: GovernedConversationalProjection): GovernedInputReference { const body = { projectionId: projection.projectionId, requestId: projection.requestId, exchangeId: projection.exchangeId, referenceTime: projection.referenceTime, schemaVersion: projection.schemaVersion }; return Object.freeze({ governedInputId: lineageIdentity("governed-conversational-input", body), ...body }); }

// Re-exporting the existing conflict type documents that it remains authoritative.
export type ExistingGovernedConflict = GovernedConflict;
