export const EVIDENCE_STATUSES = ["available", "insufficient_coverage", "unavailable", "unsupported"] as const;
export type ConversationalEvidenceStatus = (typeof EVIDENCE_STATUSES)[number];
export type ClaimOwnership = "deterministic_observation" | "deterministic_status" | "operator_provided" | "legacy_compatibility" | "model_interpretation" | "model_advisory" | "unsupported";
export type CommunicationClaimType = "contact_address_lookup" | "recipient_membership" | "message_identity" | "message_subject" | "message_excerpt" | "message_full_content" | "message_absence" | "message_importance" | "message_urgency" | "message_actionability";
export type ContentKind = "metadata" | "partial_excerpt" | "plain_text_body" | "negative_result";
export interface GovernedSourceReference { readonly sourceId: string; readonly resourceId: string; readonly field: string; readonly observedAt: string; }
export interface GovernedConflict { readonly conflictId: string; readonly claimId: string; readonly governedReference: GovernedSourceReference; readonly compatibilityContextId: string; readonly description: string; }
export interface GovernedClaimInput { readonly claimId: string; readonly claimType: CommunicationClaimType; readonly material: boolean; readonly status: ConversationalEvidenceStatus; readonly ownership: "deterministic_observation" | "deterministic_status" | "unsupported"; readonly sourceReferences: readonly GovernedSourceReference[]; readonly factualValues: readonly unknown[]; readonly sourceAvailable: boolean; readonly provenance: string; readonly observedAt: string; readonly contentKind: ContentKind; readonly boundedComplete: boolean; readonly conflicts: readonly GovernedConflict[]; }
export interface GovernedSourceInput { readonly sourceId: string; readonly available: boolean; readonly status: ConversationalEvidenceStatus; readonly observedAt: string; readonly provenance: string; }
export interface CompatibilityContext { readonly contextId: string; readonly legacySource: string; readonly governedResourceId?: string; readonly classification: "compatibility" | "fallback"; readonly authority: "none"; readonly descriptiveFields: Readonly<Record<string, string | boolean>>; readonly excludedHeuristicFields: readonly string[]; }
export type ConversationHistoryClassification = "operator_provided" | "assistant_prior_output" | "retrieval_reference";
export interface GovernedConversationTurn { readonly turnId: string; readonly classification: ConversationHistoryClassification; readonly canonicalEvidence: false; readonly content: string; }
export interface GovernedQuestion { readonly text: string; readonly timezone?: string; readonly locale?: string; }
export interface GovernedConversationalInput { readonly inputId: string; readonly threadId: string; readonly requestId: string; readonly exchangeId: string; readonly projectionId: string; readonly runId?: string; readonly sessionId?: string; readonly interfaceContractId?: string; readonly referenceTime: string; readonly question: GovernedQuestion; readonly claims: readonly GovernedClaimInput[]; readonly sources: readonly GovernedSourceInput[]; readonly compatibilityContext: readonly CompatibilityContext[]; readonly conversationHistory: readonly GovernedConversationTurn[]; readonly overallStatus: ConversationalEvidenceStatus; }
export interface GovernedResponseClaim { readonly claimId: string; readonly claimType: CommunicationClaimType; readonly material: boolean; readonly status: ConversationalEvidenceStatus; readonly sourceReferences: readonly GovernedSourceReference[]; readonly disclosure?: string; }
export interface GovernedObservedFact { readonly factId: string; readonly claimId: string; readonly sourceReference: GovernedSourceReference; readonly status: ConversationalEvidenceStatus; readonly ownership: "deterministic_observation"; readonly value: unknown; readonly contentKind: ContentKind; readonly boundedComplete: boolean; }
export interface GovernedInterpretation { readonly ownership: "model_interpretation"; readonly text: string; readonly evidenceClaimIds: readonly string[]; readonly uncertainty: string; }
export interface GovernedUncertainty { readonly uncertaintyId: string; readonly claimId: string; readonly description: string; }
export interface GovernedAdvisoryNextStep { readonly stepId: string; readonly ownership: "model_advisory"; readonly claimIds: readonly string[]; readonly text: string; readonly kind: "clarification" | "evidence_gathering" | "source_verification" | "review_consideration"; readonly subjectToOperatorJudgment: true; }
export interface GovernedRefusal { readonly claimIds: readonly string[]; readonly reason: "unsupported" | "unavailable" | "validation_failure" | "prohibited_recommendation"; readonly explanation: string; }
export interface GovernedValidationFailure { readonly ruleId: string; readonly affectedId: string; readonly reason: string; readonly severity: "error"; readonly safeHandling: "omit" | "refuse" | "safe_envelope"; }
export interface GovernedValidationWarning { readonly ruleId: string; readonly affectedId: string; readonly reason: string; }
export interface GovernedValidationResult { readonly validatorVersion: string; readonly valid: boolean; readonly outcome: "passed" | "failed"; readonly failures: readonly GovernedValidationFailure[]; readonly warnings: readonly GovernedValidationWarning[]; readonly safeResponseRequired: boolean; }
export interface GovernedConversationalResponseEnvelope { readonly envelopeId: string; readonly inputId: string; readonly overallStatus: ConversationalEvidenceStatus; readonly claims: readonly GovernedResponseClaim[]; readonly observedFacts: readonly GovernedObservedFact[]; readonly interpretation?: GovernedInterpretation; readonly uncertainties: readonly GovernedUncertainty[]; readonly conflicts: readonly GovernedConflict[]; readonly advisoryNextSteps?: readonly GovernedAdvisoryNextStep[]; readonly refusal?: GovernedRefusal; readonly validation: GovernedValidationResult; }
