import {describe,expect,it} from "vitest";
import {createConstraintSet,createIntentSet} from "../../intent";
import {DeterministicCandidatePlanConstructionEngine,DeterministicCandidatePlanRegistry,explicitObjectivePlanPolicy,type CandidatePlanDefinition} from "../candidates";
import {DeterministicCandidatePlanEvaluationEngine,DeterministicCandidatePlanEvaluationRegistry,explicitConstraintReferenceEvaluationPolicy} from "../evaluation";
import {canonicalReferenceSetComparisonPolicy,DeterministicCandidatePlanComparisonEngine,DeterministicCandidatePlanComparisonRegistry,findingStatusCountComparisonPolicy,planStructureComparisonPolicy,typedTemporalValueComparisonPolicy,type CandidatePlanComparisonDefinition} from ".";

const context={contextId:"ctx",snapshotId:"snap",assessmentSetId:"assess",sections:[],statistics:[],summary:{sectionCount:0,statisticCount:0,situationCount:0,assessmentCount:0,attentionRecordCount:0,observationCount:0},canonicalProvenance:{snapshotId:"snap",assessmentSetId:"assess",situationSetId:"situations",policies:[]}} as const;
const intentSet=createIntentSet({intentSetId:"intent-set:ctx:objective",contextId:"ctx",objectives:[{identifier:"objective",type:"operational",description:"Typed objective",origin:"test",activationStatus:"active",scope:{},metadata:{policyId:"p",policyVersion:"1"}}],summary:{objectiveCount:1,activeCount:1,inactiveCount:0,byType:{operational:1,strategic:0,standing:0,session:0,mission:0}},provenance:{contextId:"ctx",policies:[]}});
const constraintSet=createConstraintSet({constraintSetId:"constraint-set:ctx:constraint",contextId:"ctx",constraints:[{identifier:"constraint",type:"governance",origin:"test",scope:{},bindingStatus:"binding",metadata:{policyId:"p",policyVersion:"1"}}],summary:{constraintCount:1,bindingCount:1,nonBindingCount:0,byType:{authority:0,temporal:0,resource:0,governance:1,behavioural:0,privacy:0,execution:0,approval:0}},provenance:{contextId:"ctx",policies:[]}});
const plan=(identifier:string,steps:number):CandidatePlanDefinition=>({identifier,version:"1",metadata:{identifier,version:"1",displayName:identifier,description:"Configured",origin:"test",status:"active"},category:"operational-response",objectiveReferences:["objective"],contextRequirements:[],steps:Array.from({length:steps},(_,i)=>({identifier:`step-${i}`,type:"typed",ordinal:i,description:"Not compared"})),assumptions:[],dependencies:[],approvalRequirements:[],completionConditions:[],constraintReferences:["constraint"],origin:"test"});
const candidatePlanSet=new DeterministicCandidatePlanConstructionEngine(new DeterministicCandidatePlanRegistry([explicitObjectivePlanPolicy])).construct({context,intentSet,constraintSet,definitions:[plan("a",1),plan("b",2)]});
const evaluatedCandidatePlanSet=new DeterministicCandidatePlanEvaluationEngine(new DeterministicCandidatePlanEvaluationRegistry([explicitConstraintReferenceEvaluationPolicy])).evaluate({context,intentSet,constraintSet,candidatePlanSet,definitions:[]});
const def=(x:Partial<CandidatePlanComparisonDefinition>&Pick<CandidatePlanComparisonDefinition,"identifier"|"policyIdentifier"|"dimensionType"|"target"|"valueShape">):CandidatePlanComparisonDefinition=>({version:"1",applicability:{},origin:"test",pairwiseComparisonEnabled:true,...x});
const definitions=[def({identifier:"objective",policyIdentifier:canonicalReferenceSetComparisonPolicy.identifier,dimensionType:"objective-reference-set",target:"objective-references",valueShape:"reference-set"}),def({identifier:"structure",policyIdentifier:planStructureComparisonPolicy.identifier,dimensionType:"plan-step-structure",target:"plan-steps",valueShape:"structure"}),def({identifier:"temporal",policyIdentifier:typedTemporalValueComparisonPolicy.identifier,dimensionType:"typed-temporal-value",target:"temporal-constraint-scope",valueShape:"temporal"})];
const input={context,intentSet,constraintSet,candidatePlanSet,evaluatedCandidatePlanSet,definitions};
const engine=()=>new DeterministicCandidatePlanComparisonEngine(new DeterministicCandidatePlanComparisonRegistry([typedTemporalValueComparisonPolicy,planStructureComparisonPolicy,canonicalReferenceSetComparisonPolicy]));

describe("deterministic candidate plan comparative analysis",()=>{
 it("registers defensively and independently of registration order",()=>{const r=new DeterministicCandidatePlanComparisonRegistry([planStructureComparisonPolicy,canonicalReferenceSetComparisonPolicy]);expect(r.policies().map(x=>x.identifier)).toEqual([canonicalReferenceSetComparisonPolicy.identifier,planStructureComparisonPolicy.identifier].sort());expect(Object.isFrozen(r.policies()[0].metadata)).toBe(true);expect(()=>r.register(planStructureComparisonPolicy)).toThrow(/duplicate/)});
 it("preserves every candidate, emits explicit structural relations, and replays",()=>{const before=JSON.stringify({candidatePlanSet,evaluatedCandidatePlanSet});const result=engine().compare(input);expect(result).toEqual(engine().compare(input));expect(result.profiles.map(x=>x.candidatePlanId)).toEqual(candidatePlanSet.candidates.map(x=>x.candidatePlanId));expect(result.pairwiseComparisons).toHaveLength(1);expect(result.pairwiseComparisons[0].results.map(x=>x.relation)).toEqual(expect.arrayContaining(["equivalent","different","not_comparable"]));expect(JSON.stringify({candidatePlanSet,evaluatedCandidatePlanSet})).toBe(before);expect(Object.isFrozen(result.profiles[0].observations)).toBe(true);for(const prohibited of ["score","rank","winner","recommendation","selection","approval"])expect(JSON.stringify(result)).not.toContain(`\"${prohibited}\"`)});
 it("supports zero observations, a single candidate, and empty sets",()=>{const zero=engine().compare({...input,definitions:[]});expect(zero.profiles.every(x=>x.observations.length===0)).toBe(true);const oneSet={...candidatePlanSet,candidates:candidatePlanSet.candidates.slice(0,1),summary:{...candidatePlanSet.summary,candidateCount:1}};const oneEval={...evaluatedCandidatePlanSet,candidatePlanSetId:oneSet.candidatePlanSetId,evaluatedCandidates:evaluatedCandidatePlanSet.evaluatedCandidates.slice(0,1)};expect(engine().compare({...input,candidatePlanSet:oneSet,evaluatedCandidatePlanSet:oneEval,definitions:[]}).pairwiseComparisons).toEqual([]);const emptySet={...candidatePlanSet,candidates:[],summary:{...candidatePlanSet.summary,candidateCount:0}};const emptyEval={...evaluatedCandidatePlanSet,evaluatedCandidates:[],summary:{...evaluatedCandidatePlanSet.summary,candidatePlansEvaluated:0}};expect(engine().compare({...input,candidatePlanSet:emptySet,evaluatedCandidatePlanSet:emptyEval,definitions:[]}).profiles).toEqual([])});
 it("fails atomically for incoherence, duplicates, unsupported policy output, and policy exceptions",()=>{expect(()=>engine().compare({...input,evaluatedCandidatePlanSet:{...evaluatedCandidatePlanSet,contextId:"other"}})).toThrow(/identities/);expect(()=>engine().compare({...input,definitions:[definitions[0],definitions[0]]})).toThrow(/duplicate/);const bad={...findingStatusCountComparisonPolicy,identifier:"bad",metadata:{...findingStatusCountComparisonPolicy.metadata,identifier:"bad"},observe(){throw new Error("policy exception")}};const d=def({identifier:"bad-def",policyIdentifier:"bad",dimensionType:"status-count",target:"finding-status",selectorKey:"satisfied",valueShape:"count"});expect(()=>new DeterministicCandidatePlanComparisonEngine(new DeterministicCandidatePlanComparisonRegistry([bad])).compare({...input,definitions:[d]})).toThrow(/policy exception/)})
});
