import { createConstraintSet,createIntentSet } from "../../intent";
import { DeterministicCandidatePlanComparisonRegistry } from "./registry";
import type { CandidatePlanComparisonDefinition,CandidatePlanComparisonEngine,CandidatePlanComparisonInput,CandidatePlanComparisonOutcome,CandidatePlanComparisonProfile,CandidatePlanComparisonRelation,CandidatePlanComparisonSet,CandidatePlanDimensionObservation,CandidatePlanPairwiseComparison,CandidatePlanPairwiseDimensionResult,ComparisonSourceIdentities } from "./types";
import { canonical,clone,compareText,deepFreeze,identity,jsonCompatible,outcomes,reasonCodes,relations,validateDefinition } from "./validation";

const zero=(keys:readonly string[])=>Object.fromEntries(keys.map(k=>[k,0])) as Record<string,number>;
const definitionIdentity=(d:CandidatePlanComparisonDefinition)=>({identifier:d.identifier,version:d.version});
export class DeterministicCandidatePlanComparisonEngine implements CandidatePlanComparisonEngine{
 constructor(private readonly registry:DeterministicCandidatePlanComparisonRegistry){if(!(registry instanceof DeterministicCandidatePlanComparisonRegistry))throw new Error("candidate plan comparison registry is required")}
 compare(raw:CandidatePlanComparisonInput):CandidatePlanComparisonSet{
  if(!raw?.context||!raw.intentSet||!raw.constraintSet||!raw.candidatePlanSet||!raw.evaluatedCandidatePlanSet||!Array.isArray(raw.definitions))throw new Error("candidate plan comparison input is required");jsonCompatible(raw,"candidate plan comparison input");const input=deepFreeze(clone(raw));createIntentSet(input.intentSet);createConstraintSet(input.constraintSet);
  const c=input.candidatePlanSet,e=input.evaluatedCandidatePlanSet;
  if(c.contextId!==input.context.contextId||input.intentSet.contextId!==input.context.contextId||input.constraintSet.contextId!==input.context.contextId||c.intentSetId!==input.intentSet.intentSetId||c.constraintSetId!==input.constraintSet.constraintSetId)throw new Error("comparison source identities do not agree");
  if(e.contextId!==input.context.contextId||e.intentSetId!==input.intentSet.intentSetId||e.constraintSetId!==input.constraintSet.constraintSetId||e.candidatePlanSetId!==c.candidatePlanSetId)throw new Error("evaluated candidate plan source identities do not agree");
  if(new Set(c.candidates.map(x=>x.candidatePlanId)).size!==c.candidates.length||new Set(e.evaluatedCandidates.map(x=>x.candidatePlan.candidatePlanId)).size!==e.evaluatedCandidates.length||c.candidates.length!==e.evaluatedCandidates.length)throw new Error("each candidate plan must have exactly one evaluation");
  const evaluated=new Map(e.evaluatedCandidates.map(x=>[x.candidatePlan.candidatePlanId,x]));for(const candidate of c.candidates){const item=evaluated.get(candidate.candidatePlanId);if(!item||item.evaluation.candidatePlanId!==candidate.candidatePlanId)throw new Error("missing or mismatched candidate plan evaluation");if(canonical(candidate)!==canonical(item.candidatePlan))throw new Error("evaluated candidate plan does not preserve its source candidate")}
  input.definitions.forEach(validateDefinition);if(new Set(input.definitions.map(x=>x.identifier)).size!==input.definitions.length)throw new Error("duplicate comparison definition identifier");
  const policies=this.registry.policies().filter(x=>x.metadata.status==="active"),policyMap=new Map(policies.map(x=>[x.identifier,x]));for(const d of input.definitions){const p=policyMap.get(d.policyIdentifier);if(!p)throw new Error(`unresolved comparison policy: ${d.policyIdentifier}`);if(!p.supportedDimensionTypes.includes(d.dimensionType))throw new Error(`comparison policy does not support dimension: ${d.dimensionType}`);for(const id of [...(d.candidateScope??[]),...(d.applicability.candidateIdentifiers??[])])if(!c.candidates.some(x=>x.candidatePlanId===id))throw new Error(`unresolved comparison candidate: ${id}`)}
  const source:ComparisonSourceIdentities={contextId:input.context.contextId,intentSetId:input.intentSet.intentSetId,constraintSetId:input.constraintSet.constraintSetId,candidatePlanSetId:c.candidatePlanSetId,evaluatedCandidatePlanSetId:e.evaluatedCandidatePlanSetId};
  const policyIds=policies.map(x=>({identifier:x.identifier,version:x.version})),definitions=[...input.definitions].sort((a,b)=>compareText(`${a.identifier}\0${a.version}`,`${b.identifier}\0${b.version}`)),definitionIds=definitions.map(definitionIdentity),profiles:CandidatePlanComparisonProfile[]=[];
  for(const candidate of c.candidates){const item=evaluated.get(candidate.candidatePlanId)!,observations:CandidatePlanDimensionObservation[]=[];for(const d of definitions){const p=policyMap.get(d.policyIdentifier)!;const args=[deepFreeze(clone(input)),deepFreeze(clone(candidate)),deepFreeze(clone(item.evaluation)),deepFreeze(clone(d))] as const;const applies=p.applies(...args);if(typeof applies!=="boolean")throw new Error("malformed comparison applicability result");if(!applies)continue;const draft=clone(p.observe(...args));jsonCompatible(draft,"comparison observation");if(draft.dimensionType!==d.dimensionType||!reasonCodes.includes(draft.reasonCode)||!["present","absent","unsupported","conflicting"].includes(draft.valuePresence)||!Array.isArray(draft.sourceReferences))throw new Error("malformed comparison observation");const sourceReferences=[...new Set(draft.sourceReferences)].sort(compareText),provenance={...source,definitionIdentifier:d.identifier,definitionVersion:d.version,policyIdentifier:p.identifier,policyVersion:p.version,origin:d.origin,sourceReferences};const base={...draft,sourceReferences,candidatePlanId:candidate.candidatePlanId,candidatePlanEvaluationId:item.evaluation.evaluationId,definitionIdentifier:d.identifier,definitionVersion:d.version,policyIdentifier:p.identifier,policyVersion:p.version,provenance};const observationId=identity("candidate-plan-dimension-observation",candidate.candidatePlanId,item.evaluation.evaluationId,d.identifier,d.version,d.dimensionType,draft.value,sourceReferences,p.identifier,p.version,draft.reasonCode);observations.push({...base,observationId})}
   observations.sort((a,b)=>compareText(`${a.definitionIdentifier}\0${a.definitionVersion}\0${a.dimensionType}\0${a.policyIdentifier}\0${a.observationId}`,`${b.definitionIdentifier}\0${b.definitionVersion}\0${b.dimensionType}\0${b.policyIdentifier}\0${b.observationId}`));if(new Set(observations.map(x=>x.observationId)).size!==observations.length)throw new Error("duplicate comparison observation");const byDimension:Record<string,number>={},byPolicy:Record<string,number>={},referenceCounts:Record<string,number>={};observations.forEach(x=>{byDimension[x.dimensionType]=(byDimension[x.dimensionType]??0)+1;byPolicy[x.policyIdentifier]=(byPolicy[x.policyIdentifier]??0)+1;referenceCounts[x.dimensionType]=(referenceCounts[x.dimensionType]??0)+x.sourceReferences.length});const summary={totalObservations:observations.length,observationsByDimensionType:ordered(byDimension),observationsByPolicy:ordered(byPolicy),presentValues:observations.filter(x=>x.valuePresence==="present").length,absentValues:observations.filter(x=>x.valuePresence==="absent").length,unsupportedValues:observations.filter(x=>x.valuePresence==="unsupported").length,referenceCounts:ordered(referenceCounts)};const profileId=identity("candidate-plan-comparison-profile",candidate.candidatePlanId,item.evaluation.evaluationId,e.evaluatedCandidatePlanSetId,policyIds,definitionIds,observations.map(x=>x.observationId).sort(compareText));profiles.push({profileId,candidatePlanId:candidate.candidatePlanId,candidatePlanEvaluationId:item.evaluation.evaluationId,observations,summary,activePolicies:policyIds,definitions:definitionIds,sourceIdentities:source,provenance:{observationIdentifiers:observations.map(x=>x.observationId)}})}
  const profileMap=new Map(profiles.map(x=>[x.candidatePlanId,x])),ids=[...profileMap.keys()].sort(compareText),pairs:CandidatePlanPairwiseComparison[]=[];for(let i=0;i<ids.length;i++)for(let j=i+1;j<ids.length;j++){const left=profileMap.get(ids[i])!,right=profileMap.get(ids[j])!,results:CandidatePlanPairwiseDimensionResult[]=[];for(const d of definitions.filter(x=>x.pairwiseComparisonEnabled===true)){const lo=left.observations.find(x=>x.definitionIdentifier===d.identifier&&x.definitionVersion===d.version),ro=right.observations.find(x=>x.definitionIdentifier===d.identifier&&x.definitionVersion===d.version);if(!lo&&!ro)continue;const p=policyMap.get(d.policyIdentifier)!;let draft;if(!lo||!ro){draft={dimensionType:d.dimensionType,relation:lo?"only_left":"only_right",outcome:lo?"present_only_left":"present_only_right",leftValue:lo?.value??null,rightValue:ro?.value??null,reasonCode:lo?"dimension-present-only-left":"dimension-present-only-right"} as const}else{if(!p.compare)throw new Error(`pairwise comparison is unsupported by policy: ${p.identifier}`);draft=clone(p.compare(deepFreeze(clone(lo)),deepFreeze(clone(ro)),deepFreeze(clone(d))))}jsonCompatible(draft,"pairwise dimension result");if(draft.dimensionType!==d.dimensionType||!relations.includes(draft.relation)||!outcomes.includes(draft.outcome)||!reasonCodes.includes(draft.reasonCode))throw new Error("malformed pairwise dimension result");const leftRefs=lo?.sourceReferences??[],rightRefs=ro?.sourceReferences??[],provenance={...source,definitionIdentifier:d.identifier,definitionVersion:d.version,policyIdentifier:p.identifier,policyVersion:p.version,origin:d.origin,sourceReferences:[...new Set([...leftRefs,...rightRefs])].sort(compareText),leftSourceReferences:leftRefs,rightSourceReferences:rightRefs};const base={...draft,leftCandidatePlanId:left.candidatePlanId,rightCandidatePlanId:right.candidatePlanId,leftCandidatePlanEvaluationId:left.candidatePlanEvaluationId,rightCandidatePlanEvaluationId:right.candidatePlanEvaluationId,definitionIdentifier:d.identifier,definitionVersion:d.version,policyIdentifier:p.identifier,policyVersion:p.version,provenance};results.push({...base,resultId:identity("candidate-plan-pairwise-dimension-result",left.candidatePlanId,right.candidatePlanId,d.identifier,d.version,d.dimensionType,draft.relation,draft.outcome,draft.leftValue,draft.rightValue,p.identifier,p.version,draft.reasonCode)})}
   results.sort((a,b)=>compareText(`${a.definitionIdentifier}\0${a.definitionVersion}\0${a.dimensionType}\0${a.policyIdentifier}\0${a.resultId}`,`${b.definitionIdentifier}\0${b.definitionVersion}\0${b.dimensionType}\0${b.policyIdentifier}\0${b.resultId}`));if(new Set(results.map(x=>x.resultId)).size!==results.length)throw new Error("duplicate pairwise dimension result");const byRelation=zero(relations),byDimension:Record<string,number>={},byPolicy:Record<string,number>={};results.forEach(x=>{byRelation[x.relation]++;byDimension[x.dimensionType]=(byDimension[x.dimensionType]??0)+1;byPolicy[x.policyIdentifier]=(byPolicy[x.policyIdentifier]??0)+1});const summary={totalDimensionResults:results.length,byRelation:byRelation as Record<CandidatePlanComparisonRelation,number>,resultsByDimensionType:ordered(byDimension),resultsByPolicy:ordered(byPolicy)};const pairDefinitions=definitions.filter(x=>x.pairwiseComparisonEnabled).map(definitionIdentity),pairwiseComparisonId=identity("candidate-plan-pairwise-comparison",left.candidatePlanId,right.candidatePlanId,left.candidatePlanEvaluationId,right.candidatePlanEvaluationId,policyIds,pairDefinitions,results.map(x=>x.resultId));pairs.push({pairwiseComparisonId,leftCandidatePlanId:left.candidatePlanId,rightCandidatePlanId:right.candidatePlanId,results,summary,activePolicies:policyIds,definitions:pairDefinitions,provenance:{...source,resultIdentifiers:results.map(x=>x.resultId)}})}
  const allObs=profiles.flatMap(x=>[...x.observations]),allResults=pairs.flatMap(x=>[...x.results]),byDimension:Record<string,number>={},byRelation=zero(relations),byOutcome=zero(outcomes);allObs.forEach(x=>byDimension[x.dimensionType]=(byDimension[x.dimensionType]??0)+1);allResults.forEach(x=>{byRelation[x.relation]++;byOutcome[x.outcome]++});const summary={candidatesCompared:c.candidates.length,profilesCreated:profiles.length,pairwiseComparisonsCreated:pairs.length,comparisonPoliciesActive:policyIds.length,comparisonDefinitionsActive:definitionIds.length,totalObservations:allObs.length,totalPairwiseDimensionResults:allResults.length,observationsByDimensionType:ordered(byDimension),pairwiseResultsByRelation:byRelation as Record<CandidatePlanComparisonRelation,number>,pairwiseResultsByOutcome:byOutcome as Record<CandidatePlanComparisonOutcome,number>,candidatesWithZeroObservations:profiles.filter(x=>!x.observations.length).length,pairsWithZeroDimensionResults:pairs.filter(x=>!x.results.length).length,unsupportedObservations:allObs.filter(x=>x.valuePresence==="unsupported").length,notComparableResults:allResults.filter(x=>x.relation==="not_comparable").length,indeterminateResults:allResults.filter(x=>x.relation==="indeterminate").length};const provenance={profileIdentifiers:profiles.map(x=>x.profileId),pairwiseComparisonIdentifiers:pairs.map(x=>x.pairwiseComparisonId)};const result:CandidatePlanComparisonSet={comparisonSetId:identity("candidate-plan-comparison-set",source,policyIds,definitionIds,[...provenance.profileIdentifiers].sort(compareText),[...provenance.pairwiseComparisonIdentifiers].sort(compareText)),sourceIdentities:source,profiles,pairwiseComparisons:pairs,activePolicies:policyIds,definitions:definitionIds,summary,provenance};jsonCompatible(result,"candidate plan comparison set");return deepFreeze(clone(result));
 }
}
function ordered(v:Record<string,number>):Record<string,number>{return Object.fromEntries(Object.entries(v).sort((a,b)=>compareText(a[0],b[0])))}
