import type { ExecutiveContext } from "../../context";
import type { CanonicalValue, ConstraintSet, IntentSet } from "../../intent";
import type { CandidatePlan, CandidatePlanSet } from "../candidates";
import type { CandidatePlanEvaluation, EvaluatedCandidatePlanSet } from "../evaluation";

export type CandidatePlanComparisonRelation="equivalent"|"different"|"only_left"|"only_right"|"not_comparable"|"indeterminate";
export type CandidatePlanComparisonOutcome="same_value"|"different_value"|"same_count"|"different_count"|"present_in_both"|"absent_in_both"|"present_only_left"|"present_only_right"|"unsupported"|"conflicting";
export type CandidatePlanComparisonDimensionType="status-count"|"finding-type-count"|"policy-count"|"constraint-reference-set"|"objective-reference-set"|"evidence-reference-set"|"missing-evidence-set"|"conflicting-evidence-set"|"approval-requirement-set"|"dependency-set"|"assumption-set"|"completion-condition-set"|"typed-temporal-value"|"typed-resource-value"|"plan-step-structure"|"provenance-reference-set"|"configured-metadata-value";
export type CandidatePlanComparisonReasonCode="dimension-value-observed"|"dimension-value-absent"|"unsupported-dimension-shape"|"dimension-values-equivalent"|"dimension-values-different"|"dimension-present-only-left"|"dimension-present-only-right"|"dimension-values-not-comparable"|"dimension-values-conflicting"|"status-counts-equivalent"|"status-counts-different"|"finding-type-counts-equivalent"|"finding-type-counts-different"|"constraint-reference-sets-equivalent"|"constraint-reference-sets-different"|"evidence-reference-missing-left"|"evidence-reference-missing-right"|"typed-resource-values-different"|"typed-temporal-values-equivalent";
export type ComparisonValuePresence="present"|"absent"|"unsupported"|"conflicting";
export type ComparisonValueShape="count"|"reference-set"|"temporal"|"resource"|"structure"|"metadata";
export type ComparisonTargetSelector="finding-status"|"finding-type"|"finding-policy"|"constraint-references"|"objective-references"|"evidence-references"|"missing-evidence-references"|"conflicting-evidence-references"|"approval-requirements"|"dependencies"|"assumptions"|"completion-conditions"|"temporal-constraint-scope"|"resource-constraint-scope"|"plan-steps"|"provenance-references"|"candidate-metadata";
export interface CandidatePlanComparisonPolicyMetadata{readonly identifier:string;readonly version:string;readonly displayName:string;readonly description:string;readonly supportedDimensionTypes:readonly CandidatePlanComparisonDimensionType[];readonly origin:string;readonly status:"active"|"inactive"}
export interface CandidatePlanComparisonDefinition{readonly identifier:string;readonly version:string;readonly policyIdentifier:string;readonly dimensionType:CandidatePlanComparisonDimensionType;readonly target:ComparisonTargetSelector;readonly selectorKey?:string;readonly applicability:Readonly<{readonly candidateIdentifiers?:readonly string[]}>;readonly valueShape:ComparisonValueShape;readonly origin:string;readonly candidateScope?:readonly string[];readonly pairwiseComparisonEnabled?:boolean}
export interface CandidatePlanComparisonInput{readonly context:ExecutiveContext;readonly intentSet:IntentSet;readonly constraintSet:ConstraintSet;readonly candidatePlanSet:CandidatePlanSet;readonly evaluatedCandidatePlanSet:EvaluatedCandidatePlanSet;readonly definitions:readonly CandidatePlanComparisonDefinition[]}
export interface ComparisonSourceIdentities{readonly contextId:string;readonly intentSetId:string;readonly constraintSetId:string;readonly candidatePlanSetId:string;readonly evaluatedCandidatePlanSetId:string}
export interface ComparisonProvenance extends ComparisonSourceIdentities{readonly definitionIdentifier:string;readonly definitionVersion:string;readonly policyIdentifier:string;readonly policyVersion:string;readonly origin:string;readonly sourceReferences:readonly string[]}
export interface CandidatePlanDimensionObservation{readonly observationId:string;readonly candidatePlanId:string;readonly candidatePlanEvaluationId:string;readonly definitionIdentifier:string;readonly definitionVersion:string;readonly dimensionType:CandidatePlanComparisonDimensionType;readonly valueShape:ComparisonValueShape;readonly value:CanonicalValue;readonly valuePresence:ComparisonValuePresence;readonly sourceReferences:readonly string[];readonly policyIdentifier:string;readonly policyVersion:string;readonly reasonCode:CandidatePlanComparisonReasonCode;readonly provenance:ComparisonProvenance}
export type ObservationDraft=Omit<CandidatePlanDimensionObservation,"observationId"|"candidatePlanId"|"candidatePlanEvaluationId"|"definitionIdentifier"|"definitionVersion"|"policyIdentifier"|"policyVersion"|"provenance">;
export interface CandidatePlanPairwiseDimensionResult{readonly resultId:string;readonly leftCandidatePlanId:string;readonly rightCandidatePlanId:string;readonly leftCandidatePlanEvaluationId:string;readonly rightCandidatePlanEvaluationId:string;readonly definitionIdentifier:string;readonly definitionVersion:string;readonly dimensionType:CandidatePlanComparisonDimensionType;readonly relation:CandidatePlanComparisonRelation;readonly outcome:CandidatePlanComparisonOutcome;readonly leftValue:CanonicalValue;readonly rightValue:CanonicalValue;readonly reasonCode:CandidatePlanComparisonReasonCode;readonly policyIdentifier:string;readonly policyVersion:string;readonly provenance:Readonly<ComparisonProvenance&{leftSourceReferences:readonly string[];rightSourceReferences:readonly string[]}>}
export type PairwiseResultDraft=Omit<CandidatePlanPairwiseDimensionResult,"resultId"|"leftCandidatePlanId"|"rightCandidatePlanId"|"leftCandidatePlanEvaluationId"|"rightCandidatePlanEvaluationId"|"definitionIdentifier"|"definitionVersion"|"policyIdentifier"|"policyVersion"|"provenance">;
export interface CandidatePlanComparisonPolicy{readonly identifier:string;readonly version:string;readonly metadata:CandidatePlanComparisonPolicyMetadata;readonly supportedDimensionTypes:readonly CandidatePlanComparisonDimensionType[];applies(input:CandidatePlanComparisonInput,candidate:CandidatePlan,evaluation:CandidatePlanEvaluation,definition:CandidatePlanComparisonDefinition):boolean;observe(input:CandidatePlanComparisonInput,candidate:CandidatePlan,evaluation:CandidatePlanEvaluation,definition:CandidatePlanComparisonDefinition):ObservationDraft;compare?(left:CandidatePlanDimensionObservation,right:CandidatePlanDimensionObservation,definition:CandidatePlanComparisonDefinition):PairwiseResultDraft}
export interface CandidatePlanComparisonProfileSummary{readonly totalObservations:number;readonly observationsByDimensionType:Readonly<Record<string,number>>;readonly observationsByPolicy:Readonly<Record<string,number>>;readonly presentValues:number;readonly absentValues:number;readonly unsupportedValues:number;readonly referenceCounts:Readonly<Record<string,number>>}
export interface PolicyIdentity{readonly identifier:string;readonly version:string}
export interface DefinitionIdentity{readonly identifier:string;readonly version:string}
export interface CandidatePlanComparisonProfile{readonly profileId:string;readonly candidatePlanId:string;readonly candidatePlanEvaluationId:string;readonly observations:readonly CandidatePlanDimensionObservation[];readonly summary:CandidatePlanComparisonProfileSummary;readonly activePolicies:readonly PolicyIdentity[];readonly definitions:readonly DefinitionIdentity[];readonly sourceIdentities:ComparisonSourceIdentities;readonly provenance:Readonly<{readonly observationIdentifiers:readonly string[]}>}
export interface CandidatePlanPairwiseSummary{readonly totalDimensionResults:number;readonly byRelation:Readonly<Record<CandidatePlanComparisonRelation,number>>;readonly resultsByDimensionType:Readonly<Record<string,number>>;readonly resultsByPolicy:Readonly<Record<string,number>>}
export interface CandidatePlanPairwiseComparison{readonly pairwiseComparisonId:string;readonly leftCandidatePlanId:string;readonly rightCandidatePlanId:string;readonly results:readonly CandidatePlanPairwiseDimensionResult[];readonly summary:CandidatePlanPairwiseSummary;readonly activePolicies:readonly PolicyIdentity[];readonly definitions:readonly DefinitionIdentity[];readonly provenance:Readonly<ComparisonSourceIdentities&{readonly resultIdentifiers:readonly string[]}>}
export interface CandidatePlanComparisonSummary{readonly candidatesCompared:number;readonly profilesCreated:number;readonly pairwiseComparisonsCreated:number;readonly comparisonPoliciesActive:number;readonly comparisonDefinitionsActive:number;readonly totalObservations:number;readonly totalPairwiseDimensionResults:number;readonly observationsByDimensionType:Readonly<Record<string,number>>;readonly pairwiseResultsByRelation:Readonly<Record<CandidatePlanComparisonRelation,number>>;readonly pairwiseResultsByOutcome:Readonly<Record<CandidatePlanComparisonOutcome,number>>;readonly candidatesWithZeroObservations:number;readonly pairsWithZeroDimensionResults:number;readonly unsupportedObservations:number;readonly notComparableResults:number;readonly indeterminateResults:number}
export interface CandidatePlanComparisonSet{readonly comparisonSetId:string;readonly sourceIdentities:ComparisonSourceIdentities;readonly profiles:readonly CandidatePlanComparisonProfile[];readonly pairwiseComparisons:readonly CandidatePlanPairwiseComparison[];readonly activePolicies:readonly PolicyIdentity[];readonly definitions:readonly DefinitionIdentity[];readonly summary:CandidatePlanComparisonSummary;readonly provenance:Readonly<{readonly profileIdentifiers:readonly string[];readonly pairwiseComparisonIdentifiers:readonly string[]}>}
export interface CandidatePlanComparisonRegistry{register(policy:CandidatePlanComparisonPolicy):void;policies():readonly CandidatePlanComparisonPolicy[]}
export interface CandidatePlanComparisonEngine{compare(input:CandidatePlanComparisonInput):CandidatePlanComparisonSet}
