import type { CandidatePlanComparisonDefinition,CandidatePlanComparisonDimensionType,CandidatePlanComparisonOutcome,CandidatePlanComparisonPolicy,CandidatePlanComparisonReasonCode,CandidatePlanComparisonRelation } from "./types";
export const compareText=(a:string,b:string)=>a<b?-1:a>b?1:0;
export const dimensions:readonly CandidatePlanComparisonDimensionType[]=["status-count","finding-type-count","policy-count","constraint-reference-set","objective-reference-set","evidence-reference-set","missing-evidence-set","conflicting-evidence-set","approval-requirement-set","dependency-set","assumption-set","completion-condition-set","typed-temporal-value","typed-resource-value","plan-step-structure","provenance-reference-set","configured-metadata-value"];
export const relations:readonly CandidatePlanComparisonRelation[]=["equivalent","different","only_left","only_right","not_comparable","indeterminate"];
export const outcomes:readonly CandidatePlanComparisonOutcome[]=["same_value","different_value","same_count","different_count","present_in_both","absent_in_both","present_only_left","present_only_right","unsupported","conflicting"];
export const reasonCodes:readonly CandidatePlanComparisonReasonCode[]=["dimension-value-observed","dimension-value-absent","unsupported-dimension-shape","dimension-values-equivalent","dimension-values-different","dimension-present-only-left","dimension-present-only-right","dimension-values-not-comparable","dimension-values-conflicting","status-counts-equivalent","status-counts-different","finding-type-counts-equivalent","finding-type-counts-different","constraint-reference-sets-equivalent","constraint-reference-sets-different","evidence-reference-missing-left","evidence-reference-missing-right","typed-resource-values-different","typed-temporal-values-equivalent"];
export function required(v:unknown,label:string):asserts v is string{if(typeof v!=="string"||!v.trim())throw new Error(`${label} must be a non-empty string`)}
export function clone<T>(v:T):T{if(Array.isArray(v))return v.map(clone) as T;if(v&&typeof v==="object")return Object.fromEntries(Object.entries(v).map(([k,x])=>[k,clone(x)])) as T;return v}
export function deepFreeze<T>(v:T):T{if(v&&typeof v==="object"&&!Object.isFrozen(v)){Object.values(v).forEach(deepFreeze);Object.freeze(v)}return v}
export function jsonCompatible(v:unknown,p="value",seen=new Set<object>()):void{if(v===null||typeof v==="string"||typeof v==="boolean"||(typeof v==="number"&&Number.isFinite(v)))return;if(!v||typeof v!=="object"||seen.has(v as object)||(!Array.isArray(v)&&Object.getPrototypeOf(v)!==Object.prototype))throw new Error(`${p} must contain only JSON-compatible values`);seen.add(v as object);Object.entries(v).forEach(([k,x])=>jsonCompatible(x,`${p}.${k}`,seen));seen.delete(v as object)}
export function canonical(v:unknown):string{if(Array.isArray(v))return `[${v.map(canonical).join(",")}]`;if(v&&typeof v==="object")return `{${Object.keys(v).sort(compareText).map(k=>`${JSON.stringify(k)}:${canonical((v as Record<string,unknown>)[k])}`).join(",")}}`;return JSON.stringify(v)}
export const identity=(kind:string,...parts:unknown[])=>`${kind}:${parts.map(x=>encodeURIComponent(typeof x==="string"?x:canonical(x))).join(":")}`;
export function validatePolicy(p:CandidatePlanComparisonPolicy):void{if(!p||typeof p!=="object")throw new Error("comparison policy must be an object");required(p.identifier,"policy identifier");required(p.version,"policy version");if(p.metadata?.identifier!==p.identifier||p.metadata?.version!==p.version)throw new Error("policy metadata identity is inconsistent");[p.metadata?.displayName,p.metadata?.description,p.metadata?.origin].forEach((x,i)=>required(x,`policy metadata field ${i}`));if(p.metadata.status!=="active"&&p.metadata.status!=="inactive")throw new Error("invalid policy status");if(!Array.isArray(p.supportedDimensionTypes)||!p.supportedDimensionTypes.length||p.supportedDimensionTypes.some(x=>!dimensions.includes(x)))throw new Error("invalid supported comparison dimensions");if(canonical([...p.supportedDimensionTypes].sort(compareText))!==canonical([...p.metadata.supportedDimensionTypes].sort(compareText)))throw new Error("policy metadata dimensions are inconsistent");jsonCompatible(p.metadata,"policy metadata");if(typeof p.applies!=="function"||typeof p.observe!=="function"||(p.compare!==undefined&&typeof p.compare!=="function"))throw new Error("policy contract is incomplete")}
export function validateDefinition(d:CandidatePlanComparisonDefinition):void{jsonCompatible(d,"comparison definition");required(d?.identifier,"definition identifier");required(d.version,"definition version");required(d.policyIdentifier,"definition policy identifier");required(d.target,"definition target");required(d.valueShape,"definition value shape");required(d.origin,"definition origin");if(!dimensions.includes(d.dimensionType))throw new Error("unsupported comparison dimension");if(!d.applicability||typeof d.applicability!=="object")throw new Error("definition applicability is required");for(const key of ["weight","score","rank","preference","recommendation","higherIsBetter","lowerIsBetter"]){if(key in (d as unknown as Record<string,unknown>))throw new Error(`prohibited comparison definition field: ${key}`)}}
