import type { ExecutiveReasoningBoundary,ExecutiveReasoningDefinition,ExecutiveReasoningEngine,ExecutiveReasoningInput,ExecutiveReasoningObservation,ExecutiveReasoningPolicy,ExecutiveReasoningProvenance,ExecutiveReasoningQuestion,ExecutiveReasoningRecord,ExecutiveReasoningSummary } from "./types";
import type { ExecutiveReasoningRegistry } from "./types";
import { canonical,clone,compareText,deepFreeze,identity,jsonCompatible,observationTypes,reasonCodes,scopes,statuses,validateDefinition,validatePolicy } from "./validation";

const count=(values:readonly string[])=>Object.fromEntries([...new Set(values)].sort(compareText).map(k=>[k,values.filter(x=>x===k).length]));
const sorted=(v:readonly string[])=>[...new Set(v)].sort(compareText);
function checkInput(i:ExecutiveReasoningInput):void{
 jsonCompatible(i.context,"context");jsonCompatible(i.intentSet,"intent set");jsonCompatible(i.constraintSet,"constraint set");jsonCompatible(i.candidatePlanSet,"candidate plan set");jsonCompatible(i.evaluatedCandidatePlanSet,"evaluated candidate plan set");jsonCompatible(i.candidatePlanComparisonSet,"comparison set");
 const context=i.context.contextId;if(i.intentSet.contextId!==context||i.constraintSet.contextId!==context||i.candidatePlanSet.contextId!==context||i.evaluatedCandidatePlanSet.contextId!==context||i.candidatePlanComparisonSet.sourceIdentities.contextId!==context)throw new Error("reasoning input context identity mismatch");
 if(i.candidatePlanSet.intentSetId!==i.intentSet.intentSetId||i.evaluatedCandidatePlanSet.intentSetId!==i.intentSet.intentSetId||i.candidatePlanComparisonSet.sourceIdentities.intentSetId!==i.intentSet.intentSetId)throw new Error("reasoning input intent set identity mismatch");
 if(i.candidatePlanSet.constraintSetId!==i.constraintSet.constraintSetId||i.evaluatedCandidatePlanSet.constraintSetId!==i.constraintSet.constraintSetId||i.candidatePlanComparisonSet.sourceIdentities.constraintSetId!==i.constraintSet.constraintSetId)throw new Error("reasoning input constraint set identity mismatch");
 if(i.evaluatedCandidatePlanSet.candidatePlanSetId!==i.candidatePlanSet.candidatePlanSetId||i.candidatePlanComparisonSet.sourceIdentities.candidatePlanSetId!==i.candidatePlanSet.candidatePlanSetId)throw new Error("reasoning input candidate plan set identity mismatch");
 if(i.candidatePlanComparisonSet.sourceIdentities.evaluatedCandidatePlanSetId!==i.evaluatedCandidatePlanSet.evaluatedCandidatePlanSetId)throw new Error("reasoning input evaluated candidate plan set identity mismatch");
 const candidates=[...i.candidatePlanSet.candidates].sort((a,b)=>compareText(a.candidatePlanId,b.candidatePlanId));const evaluated=[...i.evaluatedCandidatePlanSet.evaluatedCandidates].sort((a,b)=>compareText(a.candidatePlan.candidatePlanId,b.candidatePlan.candidatePlanId));if(candidates.length!==evaluated.length||candidates.some((x,n)=>canonical(x)!==canonical(evaluated[n]?.candidatePlan)))throw new Error("candidate evaluation preservation mismatch");
 const profiles=[...i.candidatePlanComparisonSet.profiles].sort((a,b)=>compareText(a.candidatePlanId,b.candidatePlanId));if(profiles.length!==candidates.length||profiles.some((x,n)=>x.candidatePlanId!==candidates[n].candidatePlanId||x.candidatePlanEvaluationId!==evaluated[n].evaluation.evaluationId))throw new Error("comparison profile preservation mismatch");
}
export class DeterministicExecutiveReasoningEngine implements ExecutiveReasoningEngine{
 constructor(private readonly registry:ExecutiveReasoningRegistry){}
 reason(source:ExecutiveReasoningInput):ExecutiveReasoningRecord{
  checkInput(source);const definitions=source.definitions.map(clone);definitions.forEach(validateDefinition);const ids=new Set<string>();for(const d of definitions){if(ids.has(d.identifier))throw new Error(`duplicate reasoning definition identifier: ${d.identifier}`);ids.add(d.identifier)}
  const policies=this.registry.policies();policies.forEach(validatePolicy);const byId=new Map(policies.map(p=>[p.identifier,p]));for(const d of definitions)if(!byId.has(d.policyIdentifier))throw new Error(`reasoning policy is not registered: ${d.policyIdentifier}`);
  const input=deepFreeze(clone(source));const observations:ExecutiveReasoningObservation[]=[];const questions:ExecutiveReasoningQuestion[]=[];const boundaries:ExecutiveReasoningBoundary[]=[];
  const work:readonly ExecutiveReasoningDefinition[]=definitions.flatMap(d=>d.scope==="candidate"&&!d.candidateScope?.length&&!d.applicability.candidateIdentifiers?.length?input.candidatePlanSet.candidates.map(c=>({...d,candidateScope:[c.candidatePlanId]})): [d]).sort((a,b)=>compareText(`${a.scope}|${a.observationType}|${a.candidateScope?.[0]??""}|${a.identifier}`,`${b.scope}|${b.observationType}|${b.candidateScope?.[0]??""}|${b.identifier}`));
  for(const d of work){const p=byId.get(d.policyIdentifier)!;if(!p.supportedScopes.includes(d.scope)||!p.supportedObservationTypes.includes(d.observationType))throw new Error("reasoning definition is unsupported by policy");if(!p.applies(clone(input),clone(d)))continue;const r=clone(p.reason(clone(input),clone(d)));jsonCompatible(r,"policy result");if(!statuses.includes(r.status)||!reasonCodes.includes(r.reasonCode)||!d.supportedStatuses.includes(r.status))throw new Error("invalid or unauthorised reasoning status");
   const candidateIds=sorted(r.candidatePlanIds??[]),evaluationIds=sorted(r.evaluationIds??candidateIds.map(id=>input.evaluatedCandidatePlanSet.evaluatedCandidates.find(x=>x.candidatePlan.candidatePlanId===id)?.evaluation.evaluationId).filter((x):x is string=>!!x)),comparisonIds=sorted(r.comparisonIds??[]),evidence=sorted(r.evidenceReferences??[]),governance=sorted(r.governanceReferences??[]);
   if(candidateIds.some(id=>!input.candidatePlanSet.candidates.some(x=>x.candidatePlanId===id))||evaluationIds.some(id=>!input.evaluatedCandidatePlanSet.evaluatedCandidates.some(x=>x.evaluation.evaluationId===id)))throw new Error("unresolved mandatory canonical reference");
   const provenance:ExecutiveReasoningProvenance={contextId:input.context.contextId,intentSetId:input.intentSet.intentSetId,constraintSetId:input.constraintSet.constraintSetId,candidatePlanSetId:input.candidatePlanSet.candidatePlanSetId,evaluatedCandidatePlanSetId:input.evaluatedCandidatePlanSet.evaluatedCandidatePlanSetId,comparisonSetId:input.candidatePlanComparisonSet.comparisonSetId,definitionIdentifier:d.identifier,definitionVersion:d.version,policyIdentifier:p.identifier,policyVersion:p.version,origin:d.origin,candidatePlanIds:candidateIds,evaluationIds,comparisonIds,evidenceReferences:evidence,governanceReferences:governance,status:r.status,reasonCode:r.reasonCode};
   const observationId=identity("reasoning-observation",provenance,d.scope,d.observationType,r.value);const observation:ExecutiveReasoningObservation={observationId,definitionIdentifier:d.identifier,definitionVersion:d.version,policyIdentifier:p.identifier,policyVersion:p.version,scope:d.scope,observationType:d.observationType,status:r.status,reasonCode:r.reasonCode,candidatePlanIds:candidateIds,evaluationIds,comparisonIds,evidenceReferences:evidence,governanceBoundaryReferences:governance,value:r.value,provenance};observations.push(observation);
   if(r.question){const requiredEvidenceReferences=sorted(r.question.requiredEvidenceReferences);questions.push({questionId:identity("reasoning-question",d.identifier,d.version,p.identifier,p.version,r.reasonCode,candidateIds,requiredEvidenceReferences,r.question.requiredAuthorityReference??"",[provenance.contextId,provenance.intentSetId,provenance.constraintSetId,provenance.candidatePlanSetId,provenance.evaluatedCandidatePlanSetId,provenance.comparisonSetId]),definitionIdentifier:d.identifier,definitionVersion:d.version,policyIdentifier:p.identifier,policyVersion:p.version,reasonCode:r.reasonCode,candidatePlanIds:candidateIds,requiredEvidenceReferences,...(r.question.requiredAuthorityReference?{requiredAuthorityReference:r.question.requiredAuthorityReference}:{}),provenance})}
   if(r.boundary){boundaries.push({boundaryId:identity("reasoning-boundary",r.boundary.boundaryType,r.boundary.sourceCanonicalReference,candidateIds,r.status,p.identifier,p.version,r.reasonCode,[provenance.contextId,provenance.candidatePlanSetId,provenance.comparisonSetId]),boundaryType:r.boundary.boundaryType,sourceCanonicalReference:r.boundary.sourceCanonicalReference,candidatePlanIds:candidateIds,status:r.status,reasonCode:r.reasonCode,policyIdentifier:p.identifier,policyVersion:p.version,provenance})}
  }
  observations.sort((a,b)=>compareText(`${a.scope}|${a.observationType}|${a.candidatePlanIds[0]??""}|${a.definitionIdentifier}|${a.policyIdentifier}|${a.policyVersion}|${a.observationId}`,`${b.scope}|${b.observationType}|${b.candidatePlanIds[0]??""}|${b.definitionIdentifier}|${b.policyIdentifier}|${b.policyVersion}|${b.observationId}`));questions.sort((a,b)=>compareText(`${a.requiredAuthorityReference??a.requiredEvidenceReferences[0]??""}|${a.candidatePlanIds[0]??""}|${a.definitionIdentifier}|${a.policyIdentifier}|${a.questionId}`,`${b.requiredAuthorityReference??b.requiredEvidenceReferences[0]??""}|${b.candidatePlanIds[0]??""}|${b.definitionIdentifier}|${b.policyIdentifier}|${b.questionId}`));boundaries.sort((a,b)=>compareText(`${a.boundaryType}|${a.candidatePlanIds[0]??""}|${a.sourceCanonicalReference}|${a.policyIdentifier}|${a.boundaryId}`,`${b.boundaryType}|${b.candidatePlanIds[0]??""}|${b.sourceCanonicalReference}|${b.policyIdentifier}|${b.boundaryId}`));
  for(const [name,list] of [["observation",observations.map(x=>x.observationId)],["question",questions.map(x=>x.questionId)],["boundary",boundaries.map(x=>x.boundaryId)]] as const)if(new Set(list).size!==list.length)throw new Error(`duplicate ${name} identity`);
  const candidateRefs=sorted(observations.flatMap(x=>x.candidatePlanIds));const candidatesBy=(s:"unresolved"|"indeterminate")=>new Set(observations.filter(x=>x.status===s).flatMap(x=>x.candidatePlanIds)).size;
  const summary:ExecutiveReasoningSummary={totalObservations:observations.length,observationsByScope:count(observations.map(x=>x.scope)),observationsByType:count(observations.map(x=>x.observationType)),observationsByStatus:count(observations.map(x=>x.status)),observationsByPolicy:count(observations.map(x=>x.policyIdentifier)),totalUnresolvedQuestions:questions.length,questionsByReasonCode:count(questions.map(x=>x.reasonCode)),totalGovernanceBoundaries:boundaries.length,boundariesByType:count(boundaries.map(x=>x.boundaryType)),candidatesReferenced:candidateRefs.length,candidatesRemainingAvailableForConsideration:new Set(observations.filter(x=>x.reasonCode==="candidate-remains-available-for-consideration").flatMap(x=>x.candidatePlanIds)).size,candidatesBlockedByExplicitBoundaries:new Set(observations.filter(x=>x.reasonCode==="candidate-blocked-by-explicit-boundary").flatMap(x=>x.candidatePlanIds)).size,candidatesWithUnresolvedReasoning:candidatesBy("unresolved"),candidatesWithIndeterminateReasoning:candidatesBy("indeterminate"),planningSetObservations:observations.filter(x=>x.scope==="planning_set").length,evidenceStateObservations:observations.filter(x=>x.scope==="evidence_state").length};
  const activePolicies=policies.filter(x=>x.metadata.status==="active").map(x=>({identifier:x.identifier,version:x.version}));const definitionIdentities=definitions.sort((a,b)=>compareText(a.identifier,b.identifier)).map(x=>({identifier:x.identifier,version:x.version}));const sources=[input.context.contextId,input.intentSet.intentSetId,input.constraintSet.constraintSetId,input.candidatePlanSet.candidatePlanSetId,input.evaluatedCandidatePlanSet.evaluatedCandidatePlanSetId,input.candidatePlanComparisonSet.comparisonSetId] as const;const provenance={observationIds:observations.map(x=>x.observationId),questionIds:questions.map(x=>x.questionId),boundaryIds:boundaries.map(x=>x.boundaryId)};const record:ExecutiveReasoningRecord={reasoningRecordId:identity("executive-reasoning-record",sources,activePolicies,definitionIdentities,sorted(provenance.observationIds),sorted(provenance.questionIds),sorted(provenance.boundaryIds)),contextId:sources[0],intentSetId:sources[1],constraintSetId:sources[2],candidatePlanSetId:sources[3],evaluatedCandidatePlanSetId:sources[4],comparisonSetId:sources[5],observations,questions,boundaries,summary,activePolicies,definitions:definitionIdentities,provenance};jsonCompatible(record,"reasoning record");return deepFreeze(clone(record));
 }
}
