import type { CandidatePlanEvaluationFinding } from "../planning/evaluation";
import type { ExecutiveReasoningDefinition,ExecutiveReasoningInput,ExecutiveReasoningObservationType,ExecutiveReasoningPolicy,ExecutiveReasoningPolicyResult,ExecutiveReasoningScope } from "./types";

const findings=(input:ExecutiveReasoningInput,candidateId?:string):readonly CandidatePlanEvaluationFinding[]=>input.evaluatedCandidatePlanSet.evaluatedCandidates.filter(x=>!candidateId||x.candidatePlan.candidatePlanId===candidateId).flatMap(x=>[...x.evaluation.constraintFindings,...x.evaluation.dependencyFindings,...x.evaluation.approvalFindings,...x.evaluation.assumptionFindings,...x.evaluation.completionConditionFindings,...x.evaluation.evidenceFindings]);
const candidate=(d:ExecutiveReasoningDefinition)=>d.candidateScope?.[0]??d.applicability.candidateIdentifiers?.[0];
const refs=(d:ExecutiveReasoningDefinition)=>[...(d.requiredEvidenceReferences??[])].sort();
function policy(identifier:string,displayName:string,scope:ExecutiveReasoningScope|readonly ExecutiveReasoningScope[],type:ExecutiveReasoningObservationType|readonly ExecutiveReasoningObservationType[],reason:(i:ExecutiveReasoningInput,d:ExecutiveReasoningDefinition)=>ExecutiveReasoningPolicyResult):ExecutiveReasoningPolicy{const supportedScopes=Object.freeze(Array.isArray(scope)?[...scope]:[scope] as ExecutiveReasoningScope[]);const supportedObservationTypes=Object.freeze(Array.isArray(type)?[...type]:[type] as ExecutiveReasoningObservationType[]);return Object.freeze({identifier,version:"1",metadata:Object.freeze({identifier,version:"1",displayName,description:`Deterministic bounded ${displayName.toLowerCase()}.`,supportedScopes,supportedObservationTypes,origin:"sprint-3.22",status:"active" as const}),supportedScopes,supportedObservationTypes,applies:(_i:ExecutiveReasoningInput,d:ExecutiveReasoningDefinition)=>supportedScopes.includes(d.scope)&&supportedObservationTypes.includes(d.observationType),reason})}
const base=(d:ExecutiveReasoningDefinition,status:ExecutiveReasoningPolicyResult["status"],reasonCode:ExecutiveReasoningPolicyResult["reasonCode"],value:ExecutiveReasoningPolicyResult["value"],extra:Partial<ExecutiveReasoningPolicyResult>={}):ExecutiveReasoningPolicyResult=>({status,reasonCode,value,candidatePlanIds:candidate(d)?[candidate(d)!]:[],evidenceReferences:refs(d),...extra});

export const objectiveSupportReasoningPolicy=policy("reasoning.objective-support","Objective Support Reasoning","candidate","objective_alignment_state",(i,d)=>{const c=candidate(d);const plan=i.candidatePlanSet.candidates.find(x=>x.candidatePlanId===c);const required=d.selectors.filter(x=>x==="objectives");const missing=refs(d).filter(x=>!plan?.evidenceReferences.some(e=>`${e.type}:${e.identifier}`===x||e.identifier===x));if(missing.length)return base(d,"unresolved","evidence-insufficient-for-bounded-reasoning",{objectiveSupport:false},{question:{requiredEvidenceReferences:missing}});const fs=findings(i,c).filter(x=>x.findingType==="evidence");if(fs.some(x=>x.status==="indeterminate"))return base(d,"indeterminate","evidence-conflict-prevents-determinate-reasoning",{objectiveSupport:false});return base(d,plan&&plan.objectiveReferences.length&&required.length?"supported":"unsupported",plan&&plan.objectiveReferences.length?"objective-support-present":"objective-support-absent",{objectiveReferences:plan?.objectiveReferences??[]})});
export const constraintBoundaryReasoningPolicy=policy("reasoning.constraint-boundary","Constraint Boundary Reasoning","candidate","constraint_boundary_state",(i,d)=>{const fs=findings(i,candidate(d)).filter(x=>x.findingType==="constraint");const status=fs.some(x=>x.status==="violated")?"supported":fs.some(x=>x.status==="indeterminate")?"indeterminate":fs.some(x=>x.status==="unresolved")?"unresolved":fs.length&&fs.every(x=>x.status==="not_applicable")?"not_applicable":"supported";return base(d,status,status==="unresolved"?"hard-constraint-state-unresolved":status==="not_applicable"?"condition-not-applicable":fs.some(x=>x.status==="violated")?"hard-constraint-violation-present":"evidence-sufficient-for-bounded-reasoning",{findingStatuses:fs.map(x=>x.status).sort()})});
export const approvalAuthorityReasoningPolicy=policy("reasoning.approval-authority","Approval and Authority Reasoning","governance_boundary",["approval_boundary_state","proposal_readiness_boundary","execution_boundary_state"],(i,d)=>{const fs=findings(i,candidate(d)).filter(x=>x.findingType==="approval");const unresolved=fs.find(x=>x.status==="unresolved");if(unresolved)return base(d,"unresolved","approval-authority-unresolved",{authorityConfirmed:false},{question:{requiredEvidenceReferences:refs(d),requiredAuthorityReference:"approval-authority"},boundary:{boundaryType:"authority_unresolved",sourceCanonicalReference:unresolved.requirementIdentifier}});return base(d,fs.length?"supported":"not_applicable",fs.length?"approval-authority-confirmed":"condition-not-applicable",{approvalRequirements:fs.length})});
export const dependencyAssumptionReasoningPolicy=policy("reasoning.dependency-assumption","Dependency and Assumption Reasoning","candidate",["dependency_readiness_state","assumption_state","completion_condition_state"],(i,d)=>{const wanted=d.observationType==="assumption_state"?["assumption"]:d.observationType==="completion_condition_state"?["completion-condition"]:["dependency"];const fs=findings(i,candidate(d)).filter(x=>wanted.includes(x.findingType));const conflict=fs.some(x=>x.status==="indeterminate"||x.status==="violated");const unresolved=fs.some(x=>x.status==="unresolved");return base(d,conflict?"indeterminate":unresolved?"unresolved":fs.length?"supported":"not_applicable",conflict?"evidence-conflict-prevents-determinate-reasoning":unresolved?(d.observationType==="assumption_state"?"assumption-remains-unresolved":d.observationType==="completion_condition_state"?"completion-condition-missing":"dependency-evidence-missing"):(d.observationType==="completion_condition_state"?"completion-condition-present":fs.length?"dependency-evidence-present":"condition-not-applicable"),{findingStatuses:fs.map(x=>x.status).sort()},unresolved?{question:{requiredEvidenceReferences:refs(d)}}:{})});
export const evidenceSufficiencyReasoningPolicy=policy("reasoning.evidence-sufficiency","Evidence Sufficiency Reasoning","evidence_state",["evidence_sufficiency_state","evidence_conflict_state"],(i,d)=>{const present=new Set(findings(i,candidate(d)).flatMap(x=>x.evidenceReferences));const missing=refs(d).filter(x=>!present.has(x));const conflict=findings(i,candidate(d)).some(x=>x.status==="indeterminate");return base(d,conflict?"indeterminate":missing.length?"unresolved":"supported",conflict?"evidence-conflict-prevents-determinate-reasoning":missing.length?"evidence-insufficient-for-bounded-reasoning":"evidence-sufficient-for-bounded-reasoning",{required:refs(d),missing},missing.length?{question:{requiredEvidenceReferences:missing}}:{})});
export const comparisonInterpretationReasoningPolicy=policy("reasoning.comparison-boundary","Comparison Interpretation Boundary","cross_candidate",["comparison_support_state","comparison_limitation_state"],(i,d)=>{const pairs=i.candidatePlanComparisonSet.pairwiseComparisons.flatMap(x=>x.results);const indeterminate=pairs.some(x=>x.relation==="indeterminate"||x.relation==="not_comparable");const different=pairs.some(x=>x.relation==="different"||x.relation==="only_left"||x.relation==="only_right");return base(d,indeterminate?"indeterminate":pairs.length?"supported":"not_applicable",indeterminate?"comparison-not-determinable":different?"comparison-supports-structural-distinction":pairs.length?"comparison-supports-structural-equivalence":"condition-not-applicable",{differenceEstablishesPreference:false,relations:pairs.map(x=>x.relation).sort()},{candidatePlanIds:[...new Set(i.candidatePlanSet.candidates.map(x=>x.candidatePlanId))].sort(),comparisonIds:i.candidatePlanComparisonSet.pairwiseComparisons.map(x=>x.pairwiseComparisonId).sort()})});
export const candidateAvailabilityReasoningPolicy=policy("reasoning.candidate-availability","Candidate Availability for Consideration","candidate","candidate_viability_state",(i,d)=>{const fs=findings(i,candidate(d));const blocked=fs.some(x=>x.findingType==="constraint"&&x.status==="violated");const unresolved=fs.some(x=>x.status==="unresolved");return base(d,blocked?"unsupported":unresolved?"unresolved":"supported",blocked?"candidate-blocked-by-explicit-boundary":unresolved?"proposal-boundary-unresolved":"candidate-remains-available-for-consideration",{availableForFutureConsideration:!blocked})});
export const planningSetCompletenessReasoningPolicy=policy("reasoning.planning-set","Planning Set Completeness","planning_set","planning_set_completeness_state",(i,d)=>{const n=i.candidatePlanSet.candidates.length;return base(d,n?"supported":"unsupported",n>1?"multiple-candidates-remain-for-consideration":n?"candidate-remains-available-for-consideration":"no-candidate-satisfies-configured-condition",{candidateCount:n},{candidatePlanIds:i.candidatePlanSet.candidates.map(x=>x.candidatePlanId).sort()})});
export const productionReasoningPolicies=Object.freeze([approvalAuthorityReasoningPolicy,candidateAvailabilityReasoningPolicy,comparisonInterpretationReasoningPolicy,constraintBoundaryReasoningPolicy,dependencyAssumptionReasoningPolicy,evidenceSufficiencyReasoningPolicy,objectiveSupportReasoningPolicy,planningSetCompletenessReasoningPolicy]);
