import { describe,expect,it } from "vitest";
import { DeterministicExecutiveReasoningEngine,DeterministicExecutiveReasoningRegistry,planningSetCompletenessReasoningPolicy } from ".";
import type { ExecutiveReasoningDefinition,ExecutiveReasoningInput } from ".";

const emptyRecord={};
function input(definitions:readonly ExecutiveReasoningDefinition[]=[]):ExecutiveReasoningInput{
 const context={contextId:"ctx",snapshotId:"snap",assessmentSetId:"assess",sections:[],statistics:[],summary:{sectionCount:0,statisticCount:0,situationCount:0,assessmentCount:0,attentionRecordCount:0,observationCount:0},canonicalProvenance:{snapshotId:"snap",assessmentSetId:"assess",situationSetId:"situations",policies:[]}};
 const intentSet={intentSetId:"intents",contextId:"ctx",objectives:[],summary:{objectiveCount:0,activeCount:0,inactiveCount:0,byType:{operational:0,strategic:0,standing:0,session:0,mission:0}},provenance:{contextId:"ctx",policies:[]}};
 const constraintSet={constraintSetId:"constraints",contextId:"ctx",constraints:[],summary:{constraintCount:0,bindingCount:0,nonBindingCount:0,byType:{authority:0,temporal:0,resource:0,governance:0,behavioural:0,privacy:0,execution:0,approval:0}},provenance:{contextId:"ctx",policies:[]}};
 const candidatePlanSet={candidatePlanSetId:"plans",contextId:"ctx",intentSetId:"intents",constraintSetId:"constraints",candidates:[],summary:{definitionCount:0,policyCount:0,candidateCount:0,objectiveCount:0,constraintCount:0,stepCount:0,assumptionCount:0,dependencyCount:0,approvalRequirementCount:0,completionConditionCount:0,byCategory:{"operational-response":0,"information-gathering":0,"approval-seeking":0,"commitment-adjustment-proposal":0,"escalation-proposal":0,"monitoring-continuation":0,"no-action-observation":0,"configured-workflow":0},byPolicy:{}},provenance:{contextId:"ctx",intentSetId:"intents",constraintSetId:"constraints",policies:[]}};
 const evaluatedCandidatePlanSet={evaluatedCandidatePlanSetId:"evaluated",contextId:"ctx",intentSetId:"intents",constraintSetId:"constraints",candidatePlanSetId:"plans",evaluatedCandidates:[],summary:{candidatePlansEvaluated:0,evaluationPoliciesActive:0,totalFindings:0,byType:{constraint:0,dependency:0,approval:0,assumption:0,"completion-condition":0,evidence:0},byStatus:{satisfied:0,violated:0,unresolved:0,not_applicable:0,indeterminate:0},candidatePlansWithZeroFindings:0,candidatePlansWithViolatedFindings:0,candidatePlansWithUnresolvedFindings:0,candidatePlansWithIndeterminateFindings:0,candidatePlansWithAllEmittedFindingsSatisfied:0,constraintsReferenced:0,objectivesRepresented:0,assumptionsEvaluated:0,approvalsEvaluated:0,dependenciesEvaluated:0,completionConditionsEvaluated:0},provenance:{policies:[],definitionIdentifiers:[]}};
 const candidatePlanComparisonSet={comparisonSetId:"comparisons",sourceIdentities:{contextId:"ctx",intentSetId:"intents",constraintSetId:"constraints",candidatePlanSetId:"plans",evaluatedCandidatePlanSetId:"evaluated"},profiles:[],pairwiseComparisons:[],activePolicies:[],definitions:[],summary:{candidatesCompared:0,profilesCreated:0,pairwiseComparisonsCreated:0,comparisonPoliciesActive:0,comparisonDefinitionsActive:0,totalObservations:0,totalPairwiseDimensionResults:0,observationsByDimensionType:{},pairwiseResultsByRelation:{equivalent:0,different:0,only_left:0,only_right:0,not_comparable:0,indeterminate:0},pairwiseResultsByOutcome:{same_value:0,different_value:0,same_count:0,different_count:0,present_in_both:0,absent_in_both:0,present_only_left:0,present_only_right:0,unsupported:0,conflicting:0},candidatesWithZeroObservations:0,pairsWithZeroDimensionResults:0,unsupportedObservations:0,notComparableResults:0,indeterminateResults:0},provenance:{profileIdentifiers:[],pairwiseComparisonIdentifiers:[]}};
 return {context,intentSet,constraintSet,candidatePlanSet,evaluatedCandidatePlanSet,candidatePlanComparisonSet,definitions};
}
describe("bounded executive reasoning",()=>{
 it("clones, freezes, orders and rejects duplicate policy registrations",()=>{const registry=new DeterministicExecutiveReasoningRegistry();registry.register(planningSetCompletenessReasoningPolicy);expect(Object.isFrozen(registry.policies()[0].metadata)).toBe(true);expect(()=>registry.register(planningSetCompletenessReasoningPolicy)).toThrow(/duplicate/)});
 it("produces one immutable deterministic zero-observation record",()=>{const registry=new DeterministicExecutiveReasoningRegistry();registry.register(planningSetCompletenessReasoningPolicy);const engine=new DeterministicExecutiveReasoningEngine(registry);const a=engine.reason(input()),b=engine.reason(input());expect(a).toEqual(b);expect(a.observations).toEqual([]);expect(a.summary.totalObservations).toBe(0);expect(Object.isFrozen(a)).toBe(true);expect(a).not.toHaveProperty("recommendation");expect(emptyRecord).toEqual({})});
 it("supports an explicitly authorised empty planning-set observation",()=>{const registry=new DeterministicExecutiveReasoningRegistry();registry.register(planningSetCompletenessReasoningPolicy);const definition:ExecutiveReasoningDefinition={identifier:"empty",version:"1",scope:"planning_set",observationType:"planning_set_completeness_state",selectors:["planning_set"],applicability:{},supportedStatuses:["unsupported"],policyIdentifier:planningSetCompletenessReasoningPolicy.identifier,origin:"test"};const record=new DeterministicExecutiveReasoningEngine(registry).reason(input([definition]));expect(record.observations[0].reasonCode).toBe("no-candidate-satisfies-configured-condition");expect(record.reasoningRecordId).toMatch(/^executive-reasoning-record:/)});
 it("fails atomically for duplicate definitions and incoherent sources",()=>{const registry=new DeterministicExecutiveReasoningRegistry();registry.register(planningSetCompletenessReasoningPolicy);const engine=new DeterministicExecutiveReasoningEngine(registry);const d:ExecutiveReasoningDefinition={identifier:"x",version:"1",scope:"planning_set",observationType:"planning_set_completeness_state",selectors:["planning_set"],applicability:{},supportedStatuses:["unsupported"],policyIdentifier:planningSetCompletenessReasoningPolicy.identifier,origin:"test"};expect(()=>engine.reason(input([d,d]))).toThrow(/duplicate/);expect(()=>engine.reason({...input(),intentSet:{...input().intentSet,contextId:"other"}})).toThrow(/context identity mismatch/) });
});
