import type { ExecutiveContext } from "../context";
import type { CanonicalValue, ConstraintSet, IntentSet } from "../intent";
import type { CandidatePlanSet } from "../planning/candidates";
import type { CandidatePlanComparisonSet } from "../planning/comparison";
import type { EvaluatedCandidatePlanSet } from "../planning/evaluation";

export type ExecutiveReasoningStatus="supported"|"unsupported"|"unresolved"|"indeterminate"|"not_applicable";
export type ExecutiveReasoningScope="candidate"|"cross_candidate"|"planning_set"|"governance_boundary"|"evidence_state";
export type ExecutiveReasoningObservationType="objective_alignment_state"|"constraint_boundary_state"|"approval_boundary_state"|"dependency_readiness_state"|"assumption_state"|"completion_condition_state"|"evidence_sufficiency_state"|"evidence_conflict_state"|"comparison_support_state"|"comparison_limitation_state"|"candidate_viability_state"|"planning_set_completeness_state"|"proposal_readiness_boundary"|"execution_boundary_state";
export type ExecutiveReasoningReasonCode="objective-support-present"|"objective-support-absent"|"hard-constraint-violation-present"|"hard-constraint-state-unresolved"|"approval-authority-confirmed"|"approval-authority-unresolved"|"dependency-evidence-present"|"dependency-evidence-missing"|"assumption-remains-unresolved"|"completion-condition-present"|"completion-condition-missing"|"evidence-sufficient-for-bounded-reasoning"|"evidence-insufficient-for-bounded-reasoning"|"evidence-conflict-prevents-determinate-reasoning"|"comparison-supports-structural-distinction"|"comparison-supports-structural-equivalence"|"comparison-does-not-support-preference"|"comparison-not-determinable"|"candidate-remains-available-for-consideration"|"candidate-blocked-by-explicit-boundary"|"no-candidate-satisfies-configured-condition"|"multiple-candidates-remain-for-consideration"|"proposal-boundary-unresolved"|"execution-boundary-not-crossed"|"condition-not-applicable";
export type ExecutiveReasoningSelector="objectives"|"constraints"|"approvals"|"dependencies"|"assumptions"|"completion_conditions"|"evidence"|"comparisons"|"candidate_availability"|"planning_set"|"execution_boundary";
export interface ExecutiveReasoningPolicyMetadata{readonly identifier:string;readonly version:string;readonly displayName:string;readonly description:string;readonly supportedScopes:readonly ExecutiveReasoningScope[];readonly supportedObservationTypes:readonly ExecutiveReasoningObservationType[];readonly origin:string;readonly status:"active"|"inactive"}
export interface ExecutiveReasoningDefinition{readonly identifier:string;readonly version:string;readonly scope:ExecutiveReasoningScope;readonly observationType:ExecutiveReasoningObservationType;readonly selectors:readonly ExecutiveReasoningSelector[];readonly applicability:Readonly<{readonly candidateIdentifiers?:readonly string[];readonly findingStatuses?:readonly string[];readonly comparisonRelations?:readonly string[]}>;readonly supportedStatuses:readonly ExecutiveReasoningStatus[];readonly policyIdentifier:string;readonly origin:string;readonly candidateScope?:readonly string[];readonly requiredEvidenceReferences?:readonly string[];readonly requiredGovernanceBoundaryReferences?:readonly string[]}
export interface ExecutiveReasoningInput{readonly context:ExecutiveContext;readonly intentSet:IntentSet;readonly constraintSet:ConstraintSet;readonly candidatePlanSet:CandidatePlanSet;readonly evaluatedCandidatePlanSet:EvaluatedCandidatePlanSet;readonly candidatePlanComparisonSet:CandidatePlanComparisonSet;readonly definitions:readonly ExecutiveReasoningDefinition[]}
export interface ExecutiveReasoningProvenance{readonly contextId:string;readonly intentSetId:string;readonly constraintSetId:string;readonly candidatePlanSetId:string;readonly evaluatedCandidatePlanSetId:string;readonly comparisonSetId:string;readonly definitionIdentifier:string;readonly definitionVersion:string;readonly policyIdentifier:string;readonly policyVersion:string;readonly origin:string;readonly candidatePlanIds:readonly string[];readonly evaluationIds:readonly string[];readonly comparisonIds:readonly string[];readonly evidenceReferences:readonly string[];readonly governanceReferences:readonly string[];readonly status:ExecutiveReasoningStatus;readonly reasonCode:ExecutiveReasoningReasonCode}
export interface ExecutiveReasoningObservation{readonly observationId:string;readonly definitionIdentifier:string;readonly definitionVersion:string;readonly policyIdentifier:string;readonly policyVersion:string;readonly scope:ExecutiveReasoningScope;readonly observationType:ExecutiveReasoningObservationType;readonly status:ExecutiveReasoningStatus;readonly reasonCode:ExecutiveReasoningReasonCode;readonly candidatePlanIds:readonly string[];readonly evaluationIds:readonly string[];readonly comparisonIds:readonly string[];readonly evidenceReferences:readonly string[];readonly governanceBoundaryReferences:readonly string[];readonly value:CanonicalValue;readonly provenance:ExecutiveReasoningProvenance}
export interface ExecutiveReasoningQuestion{readonly questionId:string;readonly definitionIdentifier:string;readonly definitionVersion:string;readonly policyIdentifier:string;readonly policyVersion:string;readonly reasonCode:ExecutiveReasoningReasonCode;readonly candidatePlanIds:readonly string[];readonly requiredEvidenceReferences:readonly string[];readonly requiredAuthorityReference?:string;readonly provenance:ExecutiveReasoningProvenance}
export type ExecutiveReasoningBoundaryType="approval_required"|"execution_prohibited"|"evidence_required"|"authority_unresolved"|"dependency_unresolved"|"temporal_boundary"|"resource_boundary"|"privacy_boundary"|"governance_boundary";
export interface ExecutiveReasoningBoundary{readonly boundaryId:string;readonly boundaryType:ExecutiveReasoningBoundaryType;readonly sourceCanonicalReference:string;readonly candidatePlanIds:readonly string[];readonly status:ExecutiveReasoningStatus;readonly reasonCode:ExecutiveReasoningReasonCode;readonly policyIdentifier:string;readonly policyVersion:string;readonly provenance:ExecutiveReasoningProvenance}
export interface ExecutiveReasoningSummary{readonly totalObservations:number;readonly observationsByScope:Readonly<Record<string,number>>;readonly observationsByType:Readonly<Record<string,number>>;readonly observationsByStatus:Readonly<Record<string,number>>;readonly observationsByPolicy:Readonly<Record<string,number>>;readonly totalUnresolvedQuestions:number;readonly questionsByReasonCode:Readonly<Record<string,number>>;readonly totalGovernanceBoundaries:number;readonly boundariesByType:Readonly<Record<string,number>>;readonly candidatesReferenced:number;readonly candidatesRemainingAvailableForConsideration:number;readonly candidatesBlockedByExplicitBoundaries:number;readonly candidatesWithUnresolvedReasoning:number;readonly candidatesWithIndeterminateReasoning:number;readonly planningSetObservations:number;readonly evidenceStateObservations:number}
export interface ExecutiveReasoningRecord{readonly reasoningRecordId:string;readonly contextId:string;readonly intentSetId:string;readonly constraintSetId:string;readonly candidatePlanSetId:string;readonly evaluatedCandidatePlanSetId:string;readonly comparisonSetId:string;readonly observations:readonly ExecutiveReasoningObservation[];readonly questions:readonly ExecutiveReasoningQuestion[];readonly boundaries:readonly ExecutiveReasoningBoundary[];readonly summary:ExecutiveReasoningSummary;readonly activePolicies:readonly Readonly<{identifier:string;version:string}>[];readonly definitions:readonly Readonly<{identifier:string;version:string}>[];readonly provenance:Readonly<{observationIds:readonly string[];questionIds:readonly string[];boundaryIds:readonly string[]}>}
export interface ExecutiveReasoningPolicyResult{readonly status:ExecutiveReasoningStatus;readonly reasonCode:ExecutiveReasoningReasonCode;readonly candidatePlanIds?:readonly string[];readonly evaluationIds?:readonly string[];readonly comparisonIds?:readonly string[];readonly evidenceReferences?:readonly string[];readonly governanceReferences?:readonly string[];readonly value:CanonicalValue;readonly question?:Readonly<{requiredEvidenceReferences:readonly string[];requiredAuthorityReference?:string}>;readonly boundary?:Readonly<{boundaryType:ExecutiveReasoningBoundaryType;sourceCanonicalReference:string}>}
export interface ExecutiveReasoningPolicy{readonly identifier:string;readonly version:string;readonly metadata:ExecutiveReasoningPolicyMetadata;readonly supportedScopes:readonly ExecutiveReasoningScope[];readonly supportedObservationTypes:readonly ExecutiveReasoningObservationType[];applies(input:ExecutiveReasoningInput,definition:ExecutiveReasoningDefinition):boolean;reason(input:ExecutiveReasoningInput,definition:ExecutiveReasoningDefinition):ExecutiveReasoningPolicyResult}
export interface ExecutiveReasoningRegistry{register(policy:ExecutiveReasoningPolicy):void;policies():readonly ExecutiveReasoningPolicy[]}
export interface ExecutiveReasoningEngine{reason(input:ExecutiveReasoningInput):ExecutiveReasoningRecord}
