import type { ExecutiveReasoningDefinition,ExecutiveReasoningObservationType,ExecutiveReasoningPolicy,ExecutiveReasoningReasonCode,ExecutiveReasoningScope,ExecutiveReasoningStatus } from "./types";
export const compareText=(a:string,b:string)=>a<b?-1:a>b?1:0;
export const statuses:readonly ExecutiveReasoningStatus[]=["supported","unsupported","unresolved","indeterminate","not_applicable"];
export const scopes:readonly ExecutiveReasoningScope[]=["candidate","cross_candidate","planning_set","governance_boundary","evidence_state"];
export const observationTypes:readonly ExecutiveReasoningObservationType[]=["objective_alignment_state","constraint_boundary_state","approval_boundary_state","dependency_readiness_state","assumption_state","completion_condition_state","evidence_sufficiency_state","evidence_conflict_state","comparison_support_state","comparison_limitation_state","candidate_viability_state","planning_set_completeness_state","proposal_readiness_boundary","execution_boundary_state"];
export const reasonCodes:readonly ExecutiveReasoningReasonCode[]=["objective-support-present","objective-support-absent","hard-constraint-violation-present","hard-constraint-state-unresolved","approval-authority-confirmed","approval-authority-unresolved","dependency-evidence-present","dependency-evidence-missing","assumption-remains-unresolved","completion-condition-present","completion-condition-missing","evidence-sufficient-for-bounded-reasoning","evidence-insufficient-for-bounded-reasoning","evidence-conflict-prevents-determinate-reasoning","comparison-supports-structural-distinction","comparison-supports-structural-equivalence","comparison-does-not-support-preference","comparison-not-determinable","candidate-remains-available-for-consideration","candidate-blocked-by-explicit-boundary","no-candidate-satisfies-configured-condition","multiple-candidates-remain-for-consideration","proposal-boundary-unresolved","execution-boundary-not-crossed","condition-not-applicable"];
export function required(v:unknown,label:string):asserts v is string{if(typeof v!=="string"||!v.trim())throw new Error(`${label} must be a non-empty string`)}
export function clone<T>(v:T):T{if(Array.isArray(v))return v.map(clone) as T;if(v&&typeof v==="object")return Object.fromEntries(Object.entries(v).map(([k,x])=>[k,clone(x)])) as T;return v}
export function deepFreeze<T>(v:T):T{if(v&&typeof v==="object"&&!Object.isFrozen(v)){Object.values(v).forEach(deepFreeze);Object.freeze(v)}return v}
export function jsonCompatible(v:unknown,p="value",seen=new Set<object>()):void{if(v===null||typeof v==="string"||typeof v==="boolean"||(typeof v==="number"&&Number.isFinite(v)))return;if(!v||typeof v!=="object"||seen.has(v as object)||(!Array.isArray(v)&&Object.getPrototypeOf(v)!==Object.prototype))throw new Error(`${p} must contain only JSON-compatible values`);seen.add(v as object);Object.entries(v).forEach(([k,x])=>jsonCompatible(x,`${p}.${k}`,seen));seen.delete(v as object)}
export function canonical(v:unknown):string{if(Array.isArray(v))return `[${v.map(canonical).join(",")}]`;if(v&&typeof v==="object")return `{${Object.keys(v).sort(compareText).map(k=>`${JSON.stringify(k)}:${canonical((v as Record<string,unknown>)[k])}`).join(",")}}`;return JSON.stringify(v)}
export const identity=(kind:string,...parts:unknown[])=>`${kind}:${parts.map(x=>encodeURIComponent(typeof x==="string"?x:canonical(x))).join(":")}`;
export function validateDefinition(d:ExecutiveReasoningDefinition):void{jsonCompatible(d,"reasoning definition");required(d?.identifier,"definition identifier");required(d.version,"definition version");required(d.policyIdentifier,"definition policy identifier");required(d.origin,"definition origin");if(!scopes.includes(d.scope)||!observationTypes.includes(d.observationType))throw new Error("unsupported reasoning definition vocabulary");if(!Array.isArray(d.selectors)||!d.selectors.length||!d.applicability||!Array.isArray(d.supportedStatuses)||d.supportedStatuses.some(x=>!statuses.includes(x)))throw new Error("malformed reasoning definition");for(const key of ["weight","score","rank","preference","recommendation","prompt","approvalRule","executionInstruction"]){if(key in (d as unknown as Record<string,unknown>))throw new Error(`prohibited reasoning definition field: ${key}`)}}
export function validatePolicy(p:ExecutiveReasoningPolicy):void{if(!p||typeof p!=="object")throw new Error("reasoning policy must be an object");required(p.identifier,"policy identifier");required(p.version,"policy version");if(p.metadata?.identifier!==p.identifier||p.metadata?.version!==p.version)throw new Error("policy metadata identity is inconsistent");[p.metadata?.displayName,p.metadata?.description,p.metadata?.origin].forEach((x,i)=>required(x,`policy metadata field ${i}`));if(p.metadata.status!=="active"&&p.metadata.status!=="inactive")throw new Error("invalid policy status");if(!p.supportedScopes?.length||p.supportedScopes.some(x=>!scopes.includes(x))||!p.supportedObservationTypes?.length||p.supportedObservationTypes.some(x=>!observationTypes.includes(x)))throw new Error("invalid policy support");jsonCompatible(p.metadata,"policy metadata");if(typeof p.applies!=="function"||typeof p.reason!=="function")throw new Error("policy contract is incomplete")}
