import { createHash } from "node:crypto";
import { EXECUTIVE_CAPABILITY_INVOCATION_HANDOFF_VERSION } from "../invocation-handoff";
import type { CapabilityInvocationEnvelope,CapabilityInvocationEnvelopeInput } from "./types";
import { CapabilityInvocationEnvelopeError } from "./types";
const compare=(a:string,b:string)=>a<b?-1:a>b?1:0;
const canonical=(v:unknown):string=>Array.isArray(v)?`[${v.map(canonical)}]`:v&&typeof v==="object"?`{${Object.keys(v).sort(compare).map(k=>`${JSON.stringify(k)}:${canonical((v as Record<string,unknown>)[k])}`)}}`:JSON.stringify(v);
const identity=(v:unknown)=>`capability-invocation-envelope:${createHash("sha256").update(canonical(v)).digest("hex")}`;
const freeze=<T>(v:T):T=>{if(v&&typeof v==="object"&&!Object.isFrozen(v)){Object.values(v).forEach(freeze);Object.freeze(v)}return v};
const issued=new WeakSet<object>();
export const isIssuedInvocationEnvelope=(value:unknown):value is CapabilityInvocationEnvelope=>!!value&&typeof value==="object"&&issued.has(value as object);
export class CapabilityInvocationEnvelopePublisher{publish(input:CapabilityInvocationEnvelopeInput):CapabilityInvocationEnvelope{const handoff=input?.handoff,policy=input?.policy;if(!handoff)throw new CapabilityInvocationEnvelopeError("MISSING_HANDOFF","canonical handoff is required");if(!handoff.handoffId?.startsWith("executive-capability-invocation-handoff:")||handoff.handoffContractVersion!==EXECUTIVE_CAPABILITY_INVOCATION_HANDOFF_VERSION||handoff.handoffId!==`executive-capability-invocation-handoff:${createHash("sha256").update(canonical(Object.fromEntries(Object.entries(handoff).filter(([key])=>key!=="handoffId")))).digest("hex")}`)throw new CapabilityInvocationEnvelopeError("INVALID_HANDOFF_IDENTITY","handoff identity is invalid");if(!policy?.policyId?.trim()||!policy.policyVersion?.trim()||policy.schemaVersion!=="capability-invocation-envelope-v2")throw new CapabilityInvocationEnvelopeError("INVALID_ENVELOPE_POLICY","explicit envelope policy is invalid");const selected=handoff.items.find(x=>x.disposition==="prepared")??handoff.items[0];const blockers=handoff.items.flatMap(x=>x.unresolvedConditions).sort(compare);const body={envelopeSchemaVersion:policy.schemaVersion,handoffId:handoff.handoffId,handoffContractVersion:handoff.handoffContractVersion,proposalSetId:handoff.proposalSetId,reasoningRecordId:handoff.reasoningRecordId,deliberationContextId:handoff.deliberationContextId,policyId:policy.policyId,policyVersion:policy.policyVersion,requestClassification:"policy_enforcement_input" as const,requestItems:structuredClone(handoff.items),unresolvedBlockers:blockers,approvalGranted:false as const,invocationPerformed:false as const,executionPerformed:false as const,metadata:{owner:"CapabilityInvocationEnvelopePublisher",semantics:"immutable_request_only"} as const,routingPlanId:handoff.routingPlanId,routingContractVersion:"executive-capability-routing-v2",executiveContextId:handoff.executiveContextId,executiveStateSnapshotId:handoff.executiveStateSnapshotId,executiveContextContractVersion:"executive-context-v1",scenarioId:handoff.routingScenarioId,routingPolicyId:handoff.routingPolicyId,capabilityId:selected?.capabilityId??"no-invocation",capabilityVersion:selected?.capabilityVersion??"none",routingRuleIds:selected?.routingRuleIds??[],supportingConditionIds:selected?.conditions.map(x=>x.conditionId)??[],dependencyCapabilityIds:selected?.dependencyCapabilityIds??[],executionPolicyId:policy.policyId,executionPolicyVersion:policy.policyVersion,implementationRegistryId:"unresolved"};const envelope=freeze({envelopeId:identity(body),...body});issued.add(envelope);return envelope}}
