import { describe,expect,it,vi } from "vitest";
import type { ExecutiveContext } from "../../context";
import { CAPABILITY_INVOCATION_CONTRACT_VERSION,ExecutiveCapabilityImplementationRegistry,ExecutiveCapabilityInvoker,createExecutionPolicy } from ".";
import type { CapabilityInvocationRequest,CapabilityRoutingPlan,ExecutionPolicy,ExecutiveCapabilityImplementation } from ".";

const context={contextId:"context:1",snapshotId:"snapshot:1",assessmentSetId:"assessment:1",sections:[],statistics:[],summary:{sectionCount:0,statisticCount:0,situationCount:0,assessmentCount:0,attentionRecordCount:0,observationCount:0},canonicalProvenance:{snapshotId:"snapshot:1",assessmentSetId:"assessment:1",situationSetId:"situations:1",policies:[]}} as ExecutiveContext;
const plan:CapabilityRoutingPlan={routingPlanId:"routing:1",capabilityId:"test.echo",capabilityVersion:"1",routingStatus:"ROUTABLE",executiveContextId:context.contextId,executiveStateSnapshotId:context.snapshotId,routingContractVersion:"1.0",authority:{registered:true,eligible:true,permitted:true},dependencies:[]};
const policy:ExecutionPolicy={policyId:"execution:default",policyVersion:"1",executionEnabled:true,permittedExecutionClasses:["READ_ONLY"],permittedImplementationStatuses:["AVAILABLE"],timeoutMilliseconds:10,requiredInvocationContractVersion:CAPABILITY_INVOCATION_CONTRACT_VERSION,metadata:{origin:"test"}};
const implementation=(overrides:Partial<ExecutiveCapabilityImplementation>={}):ExecutiveCapabilityImplementation=>({implementationId:"test.echo.local",capabilityId:"test.echo",implementationVersion:"1.0",implementationStatus:"AVAILABLE",executionClass:"READ_ONLY",supportedCapabilityVersions:["1"],supportedContractVersions:[CAPABILITY_INVOCATION_CONTRACT_VERSION],precedence:1,provider:"neutral-test",invoke:ctx=>({resultId:`neutral-result:${ctx.invocationId}`,capabilityId:ctx.provenance.capabilityId,implementationId:ctx.provenance.implementationId,contractVersion:CAPABILITY_INVOCATION_CONTRACT_VERSION,elapsedMilliseconds:0,metadata:{kind:"neutral"}}),...overrides});
const request=(overrides:Partial<CapabilityInvocationRequest>={}):CapabilityInvocationRequest=>({routingPlan:plan,executiveContext:context,executionPolicy:policy,referenceTime:"2026-07-28T00:00:00.000Z",...overrides});

describe("governed executive capability invocation",()=>{
 it("validates, deterministically orders, closes, and freezes the implementation registry",()=>{const later=implementation({implementationId:"test.echo.z"}),earlier=implementation({implementationId:"test.echo.a"});const registry=new ExecutiveCapabilityImplementationRegistry([later,earlier]);expect(registry.implementations().map(x=>x.implementationId)).toEqual(["test.echo.a","test.echo.z"]);expect(Object.isFrozen(registry.implementations())).toBe(true);expect(()=>new ExecutiveCapabilityImplementationRegistry([earlier,earlier])).toThrow(/duplicate/);});
 it("publishes a deeply immutable deterministic invocation record and supports replay",()=>{const registry=new ExecutiveCapabilityImplementationRegistry([implementation()]),invoker=new ExecutiveCapabilityInvoker(registry);const first=invoker.invoke(request()),second=invoker.invoke(request());expect(first).toEqual(second);expect(first.ok).toBe(true);if(first.ok){expect(first.record.executionOutcome).toBe("SUCCESS");expect(first.record.executionEvidence.lifecycle.map(x=>x.state)).toEqual(["PENDING","VALIDATING","RESOLVING_IMPLEMENTATION","VALIDATING_AUTHORITY","INVOKING","VALIDATING_RESULT","COMPLETED"]);expect(Object.isFrozen(first.record.provenance)).toBe(true);expect(first.record.invocationId).not.toBe(first.record.recordId)}});
 it("passes only the canonical frozen context to a neutral stateless implementation",()=>{const invoke=vi.fn(implementation().invoke),registry=new ExecutiveCapabilityImplementationRegistry([implementation({invoke})]);const result=new ExecutiveCapabilityInvoker(registry).invoke(request());expect(result.ok).toBe(true);expect(invoke).toHaveBeenCalledOnce();expect(Object.isFrozen(invoke.mock.calls[0][0])).toBe(true);expect(invoke.mock.calls[0][0].routingPlan.capabilityId).toBe("test.echo")});
 it.each([
  ["invalid routing plan",request({routingPlan:{...plan,routingStatus:"BLOCKED" as "ROUTABLE"}}),[implementation()],"ROUTING_PLAN_FAILURE"],
  ["missing implementation",request(),[],"IMPLEMENTATION_RESOLUTION_FAILURE"],
  ["disabled implementation",request(),[implementation({implementationStatus:"DISABLED"})],"DISABLED_IMPLEMENTATION_FAILURE"],
  ["incompatible implementation",request(),[implementation({supportedCapabilityVersions:["2"]})],"COMPATIBILITY_FAILURE"],
  ["disabled policy",request({executionPolicy:{...policy,executionEnabled:false}}),[implementation()],"EXECUTION_POLICY_FAILURE"],
  ["unpermitted class",request(),[implementation({executionClass:"ANALYSIS"})],"EXECUTION_AUTHORITY_FAILURE"],
  ["invalid result",request(),[implementation({invoke:()=>({resultId:"bad",capabilityId:"wrong",implementationId:"test.echo.local",contractVersion:"1.0",elapsedMilliseconds:0,metadata:{}})})],"RESULT_VALIDATION_FAILURE"],
  ["timeout",request(),[implementation({invoke:ctx=>({resultId:"slow",capabilityId:ctx.provenance.capabilityId,implementationId:ctx.provenance.implementationId,contractVersion:"1.0",elapsedMilliseconds:11,metadata:{}})})],"TIMEOUT_FAILURE"]
 ] as const)("returns a deterministic failure for %s",(_name,input,implementations,category)=>{const invoker=new ExecutiveCapabilityInvoker(new ExecutiveCapabilityImplementationRegistry(implementations));const first=invoker.invoke(input),second=invoker.invoke(input);expect(first).toEqual(second);expect(first.ok).toBe(false);if(!first.ok){expect(first.failure.category).toBe(category);expect(Object.isFrozen(first.failure.evidence)).toBe(true)}});
 it("validates and freezes declarative execution policy",()=>{const value=createExecutionPolicy(policy);expect(value).toEqual(policy);expect(Object.isFrozen(value.metadata)).toBe(true);expect(()=>createExecutionPolicy({...policy,timeoutMilliseconds:-1})).toThrow(/timeout/)});
});
