import {createHash} from "node:crypto";
import {describe,expect,it,vi} from "vitest";
import {CapabilityInvocationEnvelopePublisher,ExecutiveCapabilityImplementationRegistry,ExecutiveCapabilityInvoker} from ".";
import type {ExecutiveCapabilityImplementation,InvocationPolicy} from ".";
import type {ExecutiveCapabilityInvocationHandoff,ExecutiveCapabilityInvocationHandoffItem} from "../invocation-handoff";
const canonical=(v:unknown):string=>Array.isArray(v)?`[${v.map(canonical)}]`:v&&typeof v==="object"?`{${Object.keys(v).sort().map(k=>`${JSON.stringify(k)}:${canonical((v as Record<string,unknown>)[k])}`)}}`:JSON.stringify(v);
const item:ExecutiveCapabilityInvocationHandoffItem={handoffItemId:"item:1",proposalId:"proposal:1",capabilityId:"capability:test",capabilityVersion:"1",routingRuleIds:["rule:1"],dependencyCapabilityIds:[],routingOutcomeIdentity:"outcome:1",routingReason:"eligible",actionClass:"consider_candidate",boundedRequest:{message:"bounded"},constraints:[],evidenceRequirements:[],conditions:[],authorityRequirements:[{authorityRequirementId:"authority:human",authorityType:"human_executive",sourceGovernanceReference:"policy:human",proposalId:"proposal:1",candidatePlanIds:[],requirementStatus:"ready_for_human_review",reasonCode:"approval-required-before-execution",provenance:{} as never}],approvalRequired:true,approvalGranted:false,boundaries:[],unresolvedConditions:[],disposition:"prepared",invocationPerformed:false,executionPerformed:false};
const makeHandoff=(items:readonly ExecutiveCapabilityInvocationHandoffItem[]=[item])=>{const body:Omit<ExecutiveCapabilityInvocationHandoff,"handoffId">={handoffContractVersion:"executive-capability-invocation-handoff-v1",routingPlanId:"executive-capability-routing:test",routingScenarioId:"scenario:1",routingPolicyId:"routing:1",routingPolicyVersion:"1",proposalSetId:"governed-action-proposal-set:test",executiveStateSnapshotId:"state:1",executiveContextId:"context:1",deliberationContextId:"deliberation:1",reasoningRecordId:"reasoning:1",selectionPolicyId:"selection:1",selectionPolicyVersion:"1",selectionMode:"lexical_first",items,metadata:{owner:"ExecutiveCapabilityInvocationHandoffBuilder",semantics:"request_preparation_only",approvalGranted:false,invocationPerformed:false,executionPerformed:false}};return {handoffId:`executive-capability-invocation-handoff:${createHash("sha256").update(canonical(body)).digest("hex")}`,...body} as ExecutiveCapabilityInvocationHandoff};
const envelope=(items?:readonly ExecutiveCapabilityInvocationHandoffItem[])=>new CapabilityInvocationEnvelopePublisher().publish({handoff:makeHandoff(items),policy:{policyId:"invocation:1",policyVersion:"1",schemaVersion:"capability-invocation-envelope-v2"}});
const policy:InvocationPolicy={policyId:"invoke:1",policyVersion:"1",enabled:true,approvalState:"granted",grantedAuthorityIds:["authority:human"],autonomousExecutionPermitted:true,permittedExecutionClasses:["READ_ONLY"],permittedSideEffectClasses:["NONE"],permittedImplementationStatuses:["AVAILABLE"],metadata:{}};
const implementation=(invoke:ExecutiveCapabilityImplementation["invoke"]):ExecutiveCapabilityImplementation=>({implementationId:"implementation:test",capabilityIds:["capability:test"],implementationVersion:"1",implementationStatus:"AVAILABLE",actionClasses:["consider_candidate"],executionClass:"READ_ONLY",authorityRequirements:["authority:human"],sideEffectClassification:"NONE",deterministicPriority:0,provider:"test",invoke});

describe("constitutional capability invocation",()=>{
 it("publishes a stable immutable envelope and rejects fabricated envelopes",()=>{const first=envelope([]),replay=envelope([]);expect(replay).toEqual(first);expect(Object.isFrozen(first)).toBe(true);const invoker=new ExecutiveCapabilityInvoker(new ExecutiveCapabilityImplementationRegistry([]));expect(()=>invoker.invoke({invocationEnvelope:{...first},invocationPolicy:policy,referenceTime:"2030-01-01T00:00:00Z"})).toThrow("INVALID_ENVELOPE_IDENTITY")});
 it("publishes one invocation record and no-execution result when approval is missing",()=>{const invoke=vi.fn(),invoker=new ExecutiveCapabilityInvoker(new ExecutiveCapabilityImplementationRegistry([implementation(invoke)]));const outcome=invoker.invoke({invocationEnvelope:envelope(),invocationPolicy:{...policy,approvalState:"missing"},referenceTime:"2030-01-01T00:00:00Z"});expect(outcome.invocationRecord).toMatchObject({invocationDisposition:"blocked",executionAttempted:false,approvalState:"missing",blockerClassification:["MISSING_APPROVAL_STATE"]});expect(outcome.capabilityExecutionResult).toMatchObject({executionStatus:"not_attempted",executionAttempted:false,sideEffectConfirmed:false});expect(invoke).not.toHaveBeenCalled();expect(Object.isFrozen(outcome.capabilityExecutionResult)).toBe(true)});
 it("resolves exactly one implementation and passes only the bounded request",()=>{const invoke=vi.fn<ExecutiveCapabilityImplementation["invoke"]>(()=>({status:"succeeded" as const,output:{accepted:true},sideEffectAttempted:false,sideEffectConfirmed:false,metadata:{adapter:"fake"}})),invoker=new ExecutiveCapabilityInvoker(new ExecutiveCapabilityImplementationRegistry([implementation(invoke)]));const first=invoker.invoke({invocationEnvelope:envelope(),invocationPolicy:policy,referenceTime:"2030-01-01T00:00:00Z"});expect(first.invocationRecord).toMatchObject({invocationDisposition:"invoked",implementationId:"implementation:test",executionAttempted:true});expect(first.capabilityExecutionResult).toMatchObject({executionStatus:"succeeded",boundedOutput:{accepted:true},sideEffectConfirmed:false});expect(invoke).toHaveBeenCalledTimes(1);expect(invoke.mock.calls[0][0]).toEqual(expect.objectContaining({boundedRequest:{message:"bounded"},capabilityId:"capability:test"}));expect(invoke.mock.calls[0][0]).not.toHaveProperty("reasoningRecord")});
 it("rejects duplicate and ambiguous implementations deterministically",()=>{const one=implementation(()=>({status:"succeeded",sideEffectAttempted:false,sideEffectConfirmed:false,metadata:{}}));expect(()=>new ExecutiveCapabilityImplementationRegistry([one,one])).toThrow("DUPLICATE_IMPLEMENTATION_IDENTITY");const two={...one,implementationId:"implementation:two"};const invoker=new ExecutiveCapabilityInvoker(new ExecutiveCapabilityImplementationRegistry([one,two]));expect(invoker.invoke({invocationEnvelope:envelope(),invocationPolicy:policy,referenceTime:"2030-01-01T00:00:00Z"}).invocationRecord).toMatchObject({invocationDisposition:"implementation_unresolved",blockerClassification:["AMBIGUOUS_IMPLEMENTATION"]})});
 it("records malformed and thrown implementation responses without fabricating success or retrying",()=>{for(const invoke of [vi.fn(()=>({status:"succeeded" as const,sideEffectAttempted:false,sideEffectConfirmed:true,metadata:{}})),vi.fn(()=>{throw new Error("boom")})]){const result=new ExecutiveCapabilityInvoker(new ExecutiveCapabilityImplementationRegistry([implementation(invoke)])).invoke({invocationEnvelope:envelope(),invocationPolicy:policy,referenceTime:"2030-01-01T00:00:00Z"});expect(result.capabilityExecutionResult).toMatchObject({executionStatus:"failed",executionAttempted:true,sideEffectConfirmed:false});expect(invoke).toHaveBeenCalledTimes(1)}});
});
