import { describe,expect,it,vi } from "vitest";
import type { ExecutiveContextSnapshot } from "../../../executive-context";
import type { ExecutiveCapabilityRoutingPlan } from "../types";
import { CAPABILITY_INVOCATION_CONTRACT_VERSION,ExecutiveCapabilityImplementationRegistry,ExecutiveCapabilityInvocationHandoff,ExecutiveCapabilityInvoker,createExecutionPolicy } from ".";
import type { CapabilityInvocationRequest,ExecutionPolicy,ExecutiveCapabilityImplementation } from ".";

const context={contextId:"context:1",sourceStateIdentity:{snapshotId:"snapshot:1"},derivationMetadata:{contractVersion:"executive-context-v1"}} as ExecutiveContextSnapshot;
const plan={routingPlanId:"routing:1",routingContractVersion:"executive-capability-routing-v1",executiveContextId:context.contextId,executiveStateSnapshotId:context.sourceStateIdentity.snapshotId,executiveContextContractVersion:"executive-context-v1",scenarioId:"scenario:1",policyId:"routing-policy:1",routedCapabilities:[{capabilityId:"test.echo",capabilityVersion:"1",routingRuleIds:["rule:1"],supportingConditionIds:["condition:1"],dependencyCapabilityIds:[]}],unresolvedCapabilities:[]} as ExecutiveCapabilityRoutingPlan;
const policy:ExecutionPolicy={policyId:"execution:default",policyVersion:"1",executionEnabled:true,permittedExecutionClasses:["READ_ONLY"],permittedImplementationStatuses:["AVAILABLE"],timeoutMilliseconds:10,requiredInvocationContractVersion:CAPABILITY_INVOCATION_CONTRACT_VERSION,metadata:{origin:"test"}};
const implementation=(overrides:Partial<ExecutiveCapabilityImplementation>={}):ExecutiveCapabilityImplementation=>({implementationId:"test.echo.local",capabilityId:"test.echo",implementationVersion:"1.0",implementationStatus:"AVAILABLE",executionClass:"READ_ONLY",supportedCapabilityVersions:["1"],supportedContractVersions:[CAPABILITY_INVOCATION_CONTRACT_VERSION],precedence:1,provider:"neutral-test",invoke:ctx=>({resultId:`neutral-result:${ctx.invocationId}`,capabilityId:ctx.provenance.capabilityId,implementationId:ctx.provenance.implementationId,contractVersion:CAPABILITY_INVOCATION_CONTRACT_VERSION,elapsedMilliseconds:0,metadata:{kind:"neutral"}}),...overrides});
const invoke=(implementations:readonly ExecutiveCapabilityImplementation[],overrides:Partial<Parameters<ExecutiveCapabilityInvocationHandoff["invoke"]>[0]>={})=>{const invoker=new ExecutiveCapabilityInvoker(new ExecutiveCapabilityImplementationRegistry(implementations));return new ExecutiveCapabilityInvocationHandoff(invoker).invoke({routingPlan:plan,executiveContext:context,capabilityId:"test.echo",executionPolicy:policy,referenceTime:"2026-07-28T00:00:00.000Z",...overrides})};

describe("governed executive capability invocation",()=>{
 it("validates, deterministically orders, closes, and freezes the implementation registry",()=>{const later=implementation({implementationId:"test.echo.z"}),earlier=implementation({implementationId:"test.echo.a"});const registry=new ExecutiveCapabilityImplementationRegistry([later,earlier]);expect(registry.implementations().map(x=>x.implementationId)).toEqual(["test.echo.a","test.echo.z"]);expect(Object.isFrozen(registry.implementations())).toBe(true);expect(()=>new ExecutiveCapabilityImplementationRegistry([earlier,earlier])).toThrow(/duplicate/)});
 it("publishes immutable replay-identical records with complete routing evidence",()=>{const first=invoke([implementation()]),second=invoke([implementation()]);expect(first).toEqual(second);expect(first.ok).toBe(true);if(first.ok){expect(first.record.provenance).toMatchObject({scenarioId:"scenario:1",routingPolicyId:"routing-policy:1",routingRuleIds:["rule:1"],supportingConditionIds:["condition:1"],dependencyCapabilityIds:[]});expect(Object.isFrozen(first.record.provenance)).toBe(true)}});
 it("passes only the canonical frozen context and envelope",()=>{const call=vi.fn(implementation().invoke);expect(invoke([implementation({invoke:call})]).ok).toBe(true);expect(call).toHaveBeenCalledOnce();expect(Object.isFrozen(call.mock.calls[0][0])).toBe(true);expect(call.mock.calls[0][0].invocationEnvelope.capabilityId).toBe("test.echo")});
 it("rejects fabricated caller authority before governed invocation",()=>{const invoker=new ExecutiveCapabilityInvoker(new ExecutiveCapabilityImplementationRegistry([implementation()]));const result=invoker.invoke({invocationEnvelope:{routingPlanId:"fake",capabilityId:"test.echo"},executiveContext:context,executionPolicy:policy,referenceTime:"2026-07-28T00:00:00.000Z"} as CapabilityInvocationRequest);expect(result).toMatchObject({ok:false,failure:{category:"ROUTING_PLAN_FAILURE",evidence:{reasonCode:"unaudited-routing-authority"}}})});
 it.each([
  ["missing implementation",[],{},"IMPLEMENTATION_RESOLUTION_FAILURE"],
  ["disabled implementation",[implementation({implementationStatus:"DISABLED"})],{},"DISABLED_IMPLEMENTATION_FAILURE"],
  ["incompatible implementation",[implementation({supportedCapabilityVersions:["2"]})],{},"COMPATIBILITY_FAILURE"],
  ["disabled policy",[implementation()],{executionPolicy:{...policy,executionEnabled:false}},"EXECUTION_POLICY_FAILURE"],
  ["unpermitted class",[implementation({executionClass:"ANALYSIS"})],{},"EXECUTION_AUTHORITY_FAILURE"],
  ["invalid result",[implementation({invoke:()=>({resultId:"bad",capabilityId:"wrong",implementationId:"test.echo.local",contractVersion:"1.0",elapsedMilliseconds:0,metadata:{}})})],{},"RESULT_VALIDATION_FAILURE"],
  ["timeout",[implementation({invoke:ctx=>({resultId:"slow",capabilityId:ctx.provenance.capabilityId,implementationId:ctx.provenance.implementationId,contractVersion:"1.0",elapsedMilliseconds:11,metadata:{}})})],{},"TIMEOUT_FAILURE"]
 ] as const)("preserves invocation-owned %s behaviour",(_name,implementations,overrides,category)=>expect(invoke(implementations,overrides)).toMatchObject({ok:false,failure:{category}}));
 it("rejects unresolved, absent, dependency-unsatisfied and mismatched publications",()=>{const member=plan.routedCapabilities[0];const cases=[{...plan,routedCapabilities:[],unresolvedCapabilities:[{capabilityId:"test.echo",reason:"conditions_not_met" as const}]},{...plan,routedCapabilities:[]},{...plan,routedCapabilities:[{...member,dependencyCapabilityIds:["missing"]}]},{...plan,executiveContextId:"wrong"},{...plan,executiveStateSnapshotId:"wrong"}];for(const routingPlan of cases)expect(invoke([implementation()],{routingPlan})).toMatchObject({ok:false,failure:{category:"ROUTING_PLAN_FAILURE"}})});
 it("validates and freezes declarative execution policy",()=>{const value=createExecutionPolicy(policy);expect(Object.isFrozen(value.metadata)).toBe(true);expect(()=>createExecutionPolicy({...policy,timeoutMilliseconds:-1})).toThrow(/timeout/)})
});
