import { CAPABILITY_INVOCATION_CONTRACT_VERSION } from "./types";
import type { CapabilityInvocationContext,CapabilityInvocationFailure,CapabilityInvocationRecord,CapabilityInvocationRequest,CapabilityInvocationResult,ExecutiveCapabilityImplementation,ExecutionPolicy,InvocationFailureCategory,InvocationLifecycleState,InvocationStage } from "./types";
import { ExecutiveCapabilityImplementationRegistry } from "./registry";
import { isIssuedInvocationEnvelope } from "./envelope";
import { canonical,clone,compareText,deepFreeze,validatePolicy,validateRecord,validateResult,validateRoutingPlan } from "./validation";

class InvocationAbort extends Error { constructor(readonly category:InvocationFailureCategory,readonly stage:InvocationStage,readonly reasonCode:string,message:string,readonly implementationId?:string){super(message)} }
const lifecycleStates:readonly InvocationLifecycleState[]=["PENDING","VALIDATING","RESOLVING_IMPLEMENTATION","VALIDATING_AUTHORITY","INVOKING","VALIDATING_RESULT","COMPLETED"];
function resolve(registry:ExecutiveCapabilityImplementationRegistry,request:CapabilityInvocationRequest):ExecutiveCapabilityImplementation{
 const {invocationEnvelope:plan,executionPolicy:policy}=request,candidates=registry.forCapability(plan.capabilityId);
 if(candidates.length===0)throw new InvocationAbort("IMPLEMENTATION_RESOLUTION_FAILURE","RESOLVING_IMPLEMENTATION","no-registered-implementation","No registered implementation satisfies the routed capability.");
 const compatible=candidates.filter(x=>x.supportedCapabilityVersions.includes(plan.capabilityVersion)&&x.supportedContractVersions.includes(policy.requiredInvocationContractVersion));
 if(compatible.length===0)throw new InvocationAbort("COMPATIBILITY_FAILURE","RESOLVING_IMPLEMENTATION","no-compatible-implementation","No registered implementation declares the required compatibility.");
 const enabled=compatible.filter(x=>x.implementationStatus!=="DISABLED");
 if(enabled.length===0)throw new InvocationAbort("DISABLED_IMPLEMENTATION_FAILURE","VALIDATING_AUTHORITY","implementation-disabled","All compatible implementations are disabled.",compatible[0].implementationId);
 const permitted=enabled.filter(x=>policy.permittedExecutionClasses.includes(x.executionClass)&&policy.permittedImplementationStatuses.includes(x.implementationStatus));
 if(permitted.length===0)throw new InvocationAbort("EXECUTION_AUTHORITY_FAILURE","VALIDATING_AUTHORITY","implementation-not-permitted","Execution policy grants no compatible implementation authority.");
 const preference=(id:string)=>policy.preferredImplementationIds?.indexOf(id)??-1;
 return [...permitted].sort((a,b)=>{const ai=preference(a.implementationId),bi=preference(b.implementationId);if(ai>=0||bi>=0)return (ai<0?Number.MAX_SAFE_INTEGER:ai)-(bi<0?Number.MAX_SAFE_INTEGER:bi);return a.precedence-b.precedence||compareText(b.implementationVersion,a.implementationVersion)||compareText(a.implementationId,b.implementationId)})[0];
}
function invocationId(request:CapabilityInvocationRequest,implementation:ExecutiveCapabilityImplementation):string{return `capability-invocation:${canonical([request.invocationEnvelope.envelopeId,implementation.implementationId,implementation.implementationVersion,CAPABILITY_INVOCATION_CONTRACT_VERSION,request.referenceTime])}`}
function failure(request:Partial<CapabilityInvocationRequest>,error:InvocationAbort):CapabilityInvocationResult{const plan=request.invocationEnvelope;return deepFreeze({ok:false as const,failure:{failureId:`capability-invocation-failure:${canonical([plan?.routingPlanId??"unknown",plan?.capabilityId??"unknown",request.executionPolicy?.policyId??"unknown",error.category,error.reasonCode,request.referenceTime??"unknown"])}`,category:error.category,capabilityId:plan?.capabilityId??"unknown",...(error.implementationId?{implementationId:error.implementationId}:{}),executionPolicyId:request.executionPolicy?.policyId??"unknown",stage:error.stage,message:error.message,evidence:{routingPlanId:plan?.routingPlanId??"unknown",referenceTime:request.referenceTime??"unknown",reasonCode:error.reasonCode}} satisfies CapabilityInvocationFailure})}
export class ExecutiveCapabilityInvoker {
 constructor(private readonly registry:ExecutiveCapabilityImplementationRegistry){if(!(registry instanceof ExecutiveCapabilityImplementationRegistry))throw new Error("implementation registry is required")}
 get registryId():string{return this.registry.registryId}
 rejectHandoff(input:{routingPlanId:string;capabilityId:string;executionPolicyId:string;referenceTime:string}):CapabilityInvocationResult{return failure({invocationEnvelope:{routingPlanId:input.routingPlanId,capabilityId:input.capabilityId} as never,executionPolicy:{policyId:input.executionPolicyId} as never,referenceTime:input.referenceTime},new InvocationAbort("ROUTING_PLAN_FAILURE","VALIDATING","canonical-handoff-rejected","Canonical routing publication did not authorize the requested capability."))}
 invoke(raw:CapabilityInvocationRequest):CapabilityInvocationResult{
  if(!isIssuedInvocationEnvelope(raw?.invocationEnvelope))return failure(raw??{},new InvocationAbort("ROUTING_PLAN_FAILURE","VALIDATING","unaudited-routing-authority","Governed invocation requires an envelope issued by the canonical handoff."));
  let request:CapabilityInvocationRequest;
  try{request=deepFreeze(clone(raw));if(!request||typeof request!=="object")throw new Error("invocation request is required")}catch(error){const safe=(raw??{}) as CapabilityInvocationRequest;return failure(safe,new InvocationAbort("INVOCATION_VALIDATION_FAILURE","VALIDATING","invalid-invocation-input",error instanceof Error?error.message:"Invalid invocation input."))}
  const plan=request.invocationEnvelope;
  try{validateRoutingPlan(plan);validatePolicy(request.executionPolicy);if(!request.executiveContext||request.executiveContext.contextId!==plan.executiveContextId||request.executiveContext.sourceStateIdentity.snapshotId!==plan.executiveStateSnapshotId||request.executionPolicy.policyId!==plan.executionPolicyId||request.executionPolicy.policyVersion!==plan.executionPolicyVersion||this.registry.registryId!==plan.implementationRegistryId)throw new Error("invocation identities do not match handoff provenance");if(typeof request.referenceTime!=="string"||!Number.isFinite(Date.parse(request.referenceTime)))throw new Error("referenceTime must be an explicit ISO timestamp")}catch(error){return failure(request,new InvocationAbort("INVOCATION_VALIDATION_FAILURE","VALIDATING","invalid-invocation-input",error instanceof Error?error.message:"Invalid invocation input."))}
  try{
   if(!request.executionPolicy.executionEnabled)throw new InvocationAbort("EXECUTION_POLICY_FAILURE","VALIDATING_AUTHORITY","execution-disabled","Execution is disabled by policy.");
   if(request.executionPolicy.requiredInvocationContractVersion!==CAPABILITY_INVOCATION_CONTRACT_VERSION)throw new InvocationAbort("COMPATIBILITY_FAILURE","RESOLVING_IMPLEMENTATION","unsupported-invocation-contract","Execution policy requires an unsupported invocation contract.");
   const implementation=resolve(this.registry,request),id=invocationId(request,implementation);
   const provenance={invocationEnvelopeId:plan.envelopeId,routingPlanId:plan.routingPlanId,executiveContextId:plan.executiveContextId,executiveStateSnapshotId:plan.executiveStateSnapshotId,executiveContextContractVersion:plan.executiveContextContractVersion,scenarioId:plan.scenarioId,routingPolicyId:plan.routingPolicyId,capabilityId:plan.capabilityId,capabilityVersion:plan.capabilityVersion,routingRuleIds:plan.routingRuleIds,supportingConditionIds:plan.supportingConditionIds,dependencyCapabilityIds:plan.dependencyCapabilityIds,executionPolicyId:request.executionPolicy.policyId,registryId:this.registry.registryId,implementationId:implementation.implementationId,implementationVersion:implementation.implementationVersion,routingContractVersion:plan.routingContractVersion,invocationContractVersion:CAPABILITY_INVOCATION_CONTRACT_VERSION};
   const context:CapabilityInvocationContext=deepFreeze({invocationId:id,invocationEnvelope:plan,executiveContext:request.executiveContext,executionPolicy:request.executionPolicy,referenceTime:request.referenceTime,provenance});
   let result;try{result=implementation.invoke(context)}catch{throw new InvocationAbort("RESULT_VALIDATION_FAILURE","INVOKING","implementation-invocation-failed","Implementation invocation failed without a publishable result.",implementation.implementationId)}
   try{validateResult(result,plan.capabilityId,implementation.implementationId,CAPABILITY_INVOCATION_CONTRACT_VERSION)}catch(error){throw new InvocationAbort("RESULT_VALIDATION_FAILURE","VALIDATING_RESULT","invalid-implementation-result",error instanceof Error?error.message:"Implementation result is invalid.",implementation.implementationId)}
   if(result.elapsedMilliseconds>request.executionPolicy.timeoutMilliseconds)throw new InvocationAbort("TIMEOUT_FAILURE","VALIDATING_RESULT","execution-timeout","Implementation exceeded the explicit deterministic timeout policy.",implementation.implementationId);
   const lifecycle=lifecycleStates.map((state,sequence)=>deepFreeze({state,sequence:sequence+1,referenceTime:request.referenceTime}));
   const record:CapabilityInvocationRecord={recordId:`capability-invocation-record:${canonical([id,result.resultId])}`,invocationId:id,capabilityId:plan.capabilityId,implementationId:implementation.implementationId,routingPlanId:plan.routingPlanId,executionPolicyId:request.executionPolicy.policyId,lifecycleState:"COMPLETED",executionOutcome:"SUCCESS",resultId:result.resultId,executionEvidence:{referenceTime:request.referenceTime,lifecycle},provenance,executionMetadata:{executionClass:implementation.executionClass,implementationStatus:implementation.implementationStatus,elapsedMilliseconds:result.elapsedMilliseconds},contractVersions:{invocation:CAPABILITY_INVOCATION_CONTRACT_VERSION,routing:plan.routingContractVersion,result:result.contractVersion}};
   try{validateRecord(record)}catch(error){throw new InvocationAbort("INVOCATION_RECORD_FAILURE","CONSTRUCTING_RECORD","invalid-invocation-record",error instanceof Error?error.message:"Invocation record is invalid.",implementation.implementationId)}
   return deepFreeze({ok:true as const,record:clone(record)});
  }catch(error){return failure(request,error instanceof InvocationAbort?error:new InvocationAbort("INVOCATION_RECORD_FAILURE","CONSTRUCTING_RECORD","unexpected-invocation-failure","Invocation could not be deterministically published."))}
 }
}
export function createExecutionPolicy(policy:ExecutionPolicy):ExecutionPolicy{validatePolicy(policy);return deepFreeze(clone(policy))}
