import type { ExecutiveCapabilityInvocationHandoffItem } from "../invocation-handoff";

export const CAPABILITY_INVOCATION_CONTRACT_VERSION = "capability-invocation-v2" as const;
export const CAPABILITY_EXECUTION_RESULT_VERSION = "capability-execution-result-v1" as const;
export const IMPLEMENTATION_RESOLUTION_POLICY_ID = "strict-single-eligible-v1" as const;
export type JsonValue = null | boolean | number | string | readonly JsonValue[] | { readonly [key:string]:JsonValue };
export type ImplementationStatus = "AVAILABLE" | "DISABLED" | "EXPERIMENTAL" | "DEPRECATED";
export type ExecutionClass = "READ_ONLY" | "ANALYSIS" | "ADVISORY" | "PROPOSAL" | "ACTION_CAPABLE";
export type SideEffectClassification = "NONE" | "REVERSIBLE" | "IRREVERSIBLE" | "EXTERNAL";
export type ApprovalState = "not_required" | "granted" | "missing" | "denied";
export type AuthorityValidationOutcome = "satisfied" | "insufficient" | "not_evaluated";
export type InvocationDisposition = "not_invoked" | "blocked" | "refused" | "unsupported" | "implementation_unresolved" | "invoked" | "invocation_failed";
export type ExecutionStatus = "not_attempted" | "succeeded" | "failed" | "refused" | "partial" | "unsupported" | "implementation_unavailable";
export type InvocationFailureCode = "MISSING_INVOCATION_ENVELOPE" | "INVALID_ENVELOPE_IDENTITY" | "INVALID_HANDOFF_LINEAGE" | "INVALID_CAPABILITY_IDENTITY" | "MISSING_INVOCATION_POLICY" | "INVALID_INVOCATION_POLICY" | "MISSING_APPROVAL_STATE" | "INSUFFICIENT_AUTHORITY" | "PROHIBITED_AUTONOMOUS_ACTION" | "UNRESOLVED_BLOCKER" | "INVALID_IMPLEMENTATION_REGISTRY" | "DUPLICATE_IMPLEMENTATION_IDENTITY" | "NO_IMPLEMENTATION" | "AMBIGUOUS_IMPLEMENTATION" | "UNSUPPORTED_ACTION_CLASS" | "IMPLEMENTATION_DISABLED" | "MALFORMED_IMPLEMENTATION_RESULT" | "IMPLEMENTATION_REFUSED" | "IMPLEMENTATION_EXCEPTION";

export interface CapabilityInvocationEnvelope {
 readonly envelopeId:string; readonly envelopeSchemaVersion:"capability-invocation-envelope-v2"; readonly handoffId:string; readonly handoffContractVersion:string; readonly proposalSetId:string; readonly reasoningRecordId:string; readonly deliberationContextId:string; readonly policyId:string; readonly policyVersion:string; readonly requestClassification:"policy_enforcement_input"; readonly requestItems:readonly ExecutiveCapabilityInvocationHandoffItem[]; readonly unresolvedBlockers:readonly string[]; readonly approvalGranted:false; readonly invocationPerformed:false; readonly executionPerformed:false; readonly metadata:Readonly<{owner:"CapabilityInvocationEnvelopePublisher";semantics:"immutable_request_only"}>; readonly routingPlanId:string; readonly routingContractVersion:string; readonly executiveContextId:string; readonly executiveStateSnapshotId:string; readonly executiveContextContractVersion:string; readonly scenarioId:string; readonly routingPolicyId:string; readonly capabilityId:string; readonly capabilityVersion:string; readonly routingRuleIds:readonly string[]; readonly supportingConditionIds:readonly string[]; readonly dependencyCapabilityIds:readonly string[]; readonly executionPolicyId:string; readonly executionPolicyVersion:string; readonly implementationRegistryId:string;
}
export interface CapabilityInvocationEnvelopePolicy {readonly policyId:string;readonly policyVersion:string;readonly schemaVersion:"capability-invocation-envelope-v2"}
export interface CapabilityInvocationEnvelopeInput {readonly handoff:import("../invocation-handoff").ExecutiveCapabilityInvocationHandoff;readonly policy:CapabilityInvocationEnvelopePolicy}
export type CapabilityInvocationEnvelopeFailureCode="MISSING_HANDOFF"|"INVALID_HANDOFF_IDENTITY"|"INVALID_ENVELOPE_POLICY"|"ENVELOPE_HANDOFF_LINEAGE_MISMATCH"|"INVALID_ENVELOPE_IDENTITY";
export class CapabilityInvocationEnvelopeError extends Error{constructor(readonly code:CapabilityInvocationEnvelopeFailureCode,message:string){super(message);this.name="CapabilityInvocationEnvelopeError"}}

export interface InvocationPolicy { readonly policyId:string; readonly policyVersion:string; readonly enabled:boolean; readonly approvalState:ApprovalState; readonly grantedAuthorityIds:readonly string[]; readonly autonomousExecutionPermitted:boolean; readonly permittedExecutionClasses:readonly ExecutionClass[]; readonly permittedSideEffectClasses:readonly SideEffectClassification[]; readonly permittedImplementationStatuses:readonly ImplementationStatus[]; readonly explicitImplementationId?:string; readonly metadata:Readonly<Record<string,JsonValue>> }
export interface BoundedCapabilityImplementationRequest { readonly invocationId:string; readonly envelopeId:string; readonly proposalId:string; readonly capabilityId:string; readonly actionClass:string; readonly boundedRequest:JsonValue; readonly constraints:readonly string[]; readonly referenceTime:string }
export interface ImplementationReturn { readonly status:"succeeded"|"failed"|"refused"|"partial"; readonly output?:JsonValue; readonly errorCode?:string; readonly sideEffectAttempted:boolean; readonly sideEffectConfirmed:boolean; readonly metadata:Readonly<Record<string,JsonValue>> }
export interface ExecutiveCapabilityImplementationDescriptor { readonly implementationId:string; readonly capabilityIds:readonly string[]; readonly implementationVersion:string; readonly implementationStatus:ImplementationStatus; readonly actionClasses:readonly string[]; readonly executionClass:ExecutionClass; readonly authorityRequirements:readonly string[]; readonly sideEffectClassification:SideEffectClassification; readonly deterministicPriority:number; readonly provider:string }
export interface ExecutiveCapabilityImplementation extends ExecutiveCapabilityImplementationDescriptor { invoke(request:BoundedCapabilityImplementationRequest):ImplementationReturn }
export interface CapabilityInvocationRecord { readonly invocationRecordId:string; readonly envelopeId:string; readonly handoffId:string; readonly routingPlanId:string; readonly proposalId?:string; readonly proposalSetId:string; readonly capabilityId:string; readonly implementationId?:string; readonly invocationPolicyId:string; readonly implementationResolutionPolicyId:typeof IMPLEMENTATION_RESOLUTION_POLICY_ID; readonly approvalRequired:boolean; readonly approvalState:ApprovalState; readonly authorityRequirements:readonly string[]; readonly authorityValidationOutcome:AuthorityValidationOutcome; readonly blockerClassification:readonly InvocationFailureCode[]; readonly invocationDisposition:InvocationDisposition; readonly executionAttempted:boolean; readonly lineage:Readonly<{executiveStateSnapshotId:string;executiveContextId:string;deliberationContextId:string;reasoningRecordId:string}>; readonly metadata:Readonly<{owner:"ExecutiveCapabilityInvoker";contractVersion:typeof CAPABILITY_INVOCATION_CONTRACT_VERSION;referenceTime:string}> }
export interface CapabilityExecutionResult { readonly executionResultId:string; readonly invocationRecordId:string; readonly envelopeId:string; readonly proposalId?:string; readonly capabilityId:string; readonly implementationId?:string; readonly executionStatus:ExecutionStatus; readonly executionAttempted:boolean; readonly sideEffectAttempted:boolean; readonly sideEffectConfirmed:boolean; readonly boundedOutput?:JsonValue; readonly errorCode?:string; readonly implementationMetadata:Readonly<Record<string,JsonValue>>; readonly lineage:CapabilityInvocationRecord["lineage"]; readonly completionMetadata:Readonly<{owner:"ExecutiveCapabilityInvoker";contractVersion:typeof CAPABILITY_EXECUTION_RESULT_VERSION;referenceTime:string}>; readonly redactionMetadata:Readonly<{redacted:boolean}>; readonly grantsApproval:false }
export interface CapabilityInvocationOutcome {readonly invocationRecord:CapabilityInvocationRecord;readonly capabilityExecutionResult:CapabilityExecutionResult}
export interface CapabilityInvocationRequest {readonly invocationEnvelope:CapabilityInvocationEnvelope;readonly invocationPolicy:InvocationPolicy;readonly referenceTime:string}
