import { createHash } from "node:crypto";
import type { CapabilityInvocationEnvelope,ExecutiveCapabilityImplementation,ImplementationReturn,InvocationPolicy,JsonValue } from "./types";
export const compareText=(a:string,b:string)=>a<b?-1:a>b?1:0;
export const stable=(v:unknown):string=>Array.isArray(v)?`[${v.map(stable)}]`:v&&typeof v==="object"?`{${Object.keys(v).sort(compareText).map(k=>`${JSON.stringify(k)}:${stable((v as Record<string,unknown>)[k])}`)}}`:JSON.stringify(v);
export const identity=(prefix:string,body:unknown)=>`${prefix}:${createHash("sha256").update(stable(body)).digest("hex")}`;
export function canonical(parts:readonly string[]):string{return createHash("sha256").update(stable(parts)).digest("hex")}
export function deepFreeze<T>(v:T):T{if(v&&typeof v==="object"&&!Object.isFrozen(v)){Object.values(v).forEach(deepFreeze);Object.freeze(v)}return v}
export function jsonCompatible(v:unknown,path="value",seen=new Set<object>()):void{if(v===null||typeof v==="string"||typeof v==="boolean"||(typeof v==="number"&&Number.isFinite(v)))return;if(!v||typeof v!=="object"||seen.has(v as object)||(!Array.isArray(v)&&Object.getPrototypeOf(v)!==Object.prototype))throw new Error(`${path} must be JSON-compatible`);seen.add(v as object);for(const x of Object.values(v))jsonCompatible(x,path,seen);seen.delete(v as object)}
const strings=(v:unknown)=>Array.isArray(v)&&v.every(x=>typeof x==="string"&&x.length>0)&&new Set(v).size===v.length;
export function validateImplementation(x:ExecutiveCapabilityImplementation){if(!x||typeof x!=="object"||!x.implementationId||!x.implementationVersion||!x.provider||!strings(x.capabilityIds)||!strings(x.actionClasses)||!Array.isArray(x.authorityRequirements)||typeof x.invoke!=="function"||!Number.isSafeInteger(x.deterministicPriority)||x.deterministicPriority<0)throw new Error("MALFORMED_IMPLEMENTATION_CONTRACT");if(!["AVAILABLE","DISABLED","EXPERIMENTAL","DEPRECATED"].includes(x.implementationStatus)||!["READ_ONLY","ANALYSIS","ADVISORY","PROPOSAL","ACTION_CAPABLE"].includes(x.executionClass)||!["NONE","REVERSIBLE","IRREVERSIBLE","EXTERNAL"].includes(x.sideEffectClassification))throw new Error("MALFORMED_IMPLEMENTATION_CONTRACT")}
export function validatePolicy(x:InvocationPolicy){if(!x||!x.policyId||!x.policyVersion||typeof x.enabled!=="boolean"||!["not_required","granted","missing","denied"].includes(x.approvalState)||!strings(x.permittedExecutionClasses)||!strings(x.permittedSideEffectClasses)||!strings(x.permittedImplementationStatuses)||!Array.isArray(x.grantedAuthorityIds))throw new Error("INVALID_INVOCATION_POLICY");jsonCompatible(x.metadata)}
export function validateEnvelope(x:CapabilityInvocationEnvelope){if(!x||!x.envelopeId||!x.handoffId||!x.routingPlanId||!x.proposalSetId||!x.capabilityId||!Array.isArray(x.requestItems)||!Array.isArray(x.unresolvedBlockers))throw new Error("INVALID_ENVELOPE_IDENTITY")}
export function validateImplementationReturn(x:ImplementationReturn){if(!x||!["succeeded","failed","refused","partial"].includes(x.status)||typeof x.sideEffectAttempted!=="boolean"||typeof x.sideEffectConfirmed!=="boolean"||x.sideEffectConfirmed&&!x.sideEffectAttempted)throw new Error("MALFORMED_IMPLEMENTATION_RESULT");if(x.status==="succeeded"&&x.errorCode)throw new Error("MALFORMED_IMPLEMENTATION_RESULT");if(x.output!==undefined)jsonCompatible(x.output);jsonCompatible(x.metadata)}
export type FrozenMetadata=Readonly<Record<string,JsonValue>>;
