import type { CapabilityExecutionResult,CapabilityInvocationRecord,CapabilityRoutingPlan,ExecutionPolicy,ExecutiveCapabilityImplementation,JsonValue } from "./types";
export const compareText=(a:string,b:string)=>a<b?-1:a>b?1:0;
export function required(v:unknown,path:string):asserts v is string{if(typeof v!=="string"||v.trim()==="")throw new Error(`${path} must be a non-empty string`)}
export function clone<T>(v:T):T{if(Array.isArray(v))return v.map(clone) as T;if(v&&typeof v==="object")return Object.fromEntries(Object.entries(v).map(([k,x])=>[k,clone(x)])) as T;return v}
export function deepFreeze<T>(v:T):T{if(v&&typeof v==="object"&&!Object.isFrozen(v)){Object.values(v).forEach(deepFreeze);Object.freeze(v)}return v}
export function jsonCompatible(v:unknown,path="value",seen=new Set<object>()):void{if(v===null||typeof v==="string"||typeof v==="boolean"||(typeof v==="number"&&Number.isFinite(v)))return;if(!v||typeof v!=="object"||seen.has(v as object)||(!Array.isArray(v)&&Object.getPrototypeOf(v)!==Object.prototype))throw new Error(`${path} must contain only JSON-compatible values`);seen.add(v as object);for(const [k,x] of Object.entries(v))jsonCompatible(x,`${path}.${k}`,seen);seen.delete(v as object)}
const uniq=(xs:readonly string[],path:string)=>{if(!Array.isArray(xs)||xs.some(x=>typeof x!=="string"||!x)||new Set(xs).size!==xs.length)throw new Error(`${path} must contain unique non-empty values`)};
export function validateImplementation(x:ExecutiveCapabilityImplementation):void{if(!x||typeof x!=="object")throw new Error("implementation must be an object");required(x.implementationId,"implementation id");required(x.capabilityId,"capability id");required(x.implementationVersion,"implementation version");required(x.provider,"implementation provider");if(!["AVAILABLE","DISABLED","EXPERIMENTAL","DEPRECATED"].includes(x.implementationStatus))throw new Error("invalid implementation status");if(!["READ_ONLY","ANALYSIS","ADVISORY","PROPOSAL","ACTION_CAPABLE"].includes(x.executionClass))throw new Error("invalid execution class");uniq(x.supportedCapabilityVersions,"supported capability versions");uniq(x.supportedContractVersions,"supported contract versions");if(!Number.isSafeInteger(x.precedence)||x.precedence<0)throw new Error("implementation precedence must be a non-negative integer");if(typeof x.invoke!=="function")throw new Error("implementation must implement invoke()")}
export function validatePolicy(x:ExecutionPolicy):void{if(!x||typeof x!=="object")throw new Error("execution policy is required");required(x.policyId,"policy id");required(x.policyVersion,"policy version");required(x.requiredInvocationContractVersion,"required invocation contract version");if(typeof x.executionEnabled!=="boolean")throw new Error("executionEnabled must be boolean");uniq(x.permittedExecutionClasses,"permitted execution classes");uniq(x.permittedImplementationStatuses,"permitted implementation statuses");if(x.preferredImplementationIds)uniq(x.preferredImplementationIds,"preferred implementation ids");if(!Number.isSafeInteger(x.timeoutMilliseconds)||x.timeoutMilliseconds<0)throw new Error("timeout must be a non-negative integer");jsonCompatible(x.metadata,"execution policy metadata")}
export function validateRoutingPlan(x:CapabilityRoutingPlan):void{if(!x||typeof x!=="object")throw new Error("routing plan is required");for(const [p,v] of [["routing plan id",x.routingPlanId],["capability id",x.capabilityId],["capability version",x.capabilityVersion],["executive context id",x.executiveContextId],["executive state snapshot id",x.executiveStateSnapshotId],["routing contract version",x.routingContractVersion]] as const)required(v,p);if(x.routingStatus!=="ROUTABLE")throw new Error("routing plan is not routable");if(!x.authority||!x.authority.registered||!x.authority.eligible||!x.authority.permitted)throw new Error("routing authority is incomplete");if(!Array.isArray(x.dependencies)||x.dependencies.some(d=>!d||!d.dependencyId||d.status!=="SATISFIED"))throw new Error("routing dependencies are not satisfied");jsonCompatible(x,"routing plan")}
export function validateResult(x:CapabilityExecutionResult,capabilityId:string,implementationId:string,contract:string):void{if(!x||typeof x!=="object")throw new Error("implementation result is required");required(x.resultId,"result id");if(x.capabilityId!==capabilityId||x.implementationId!==implementationId||x.contractVersion!==contract)throw new Error("implementation result identity or contract mismatch");if(!Number.isSafeInteger(x.elapsedMilliseconds)||x.elapsedMilliseconds<0)throw new Error("implementation result elapsedMilliseconds is invalid");jsonCompatible(x,"implementation result")}
export function validateRecord(x:CapabilityInvocationRecord):void{jsonCompatible(x,"invocation record");if(x.lifecycleState!=="COMPLETED"||x.executionOutcome!=="SUCCESS"||x.executionEvidence.lifecycle.at(-1)?.state!=="COMPLETED")throw new Error("invocation record lifecycle is invalid")}
export function canonical(parts:readonly string[]):string{return parts.map(encodeURIComponent).join(":")}
export type FrozenMetadata=Readonly<Record<string,JsonValue>>;
