import { describe, expect, it } from "vitest";
import { compareSituationalAwarenessSnapshots, createSituationalAwarenessSnapshot } from "../situational-awareness/lifecycle";
import { createSituationalAwareness } from "../situational-awareness/model";
import { AttentionPolicyRegistry, INITIAL_ATTENTION_POLICIES, constructExecutiveAttentionQueue, createExecutiveAttentionQueue } from ".";

const state = (status: "scheduled" | "cancelled", startsAt: string, sourceStatus: "available" | "unavailable" = "available") => createSituationalAwareness({ identity: { userId: "u", displayName: "User" }, commitments: [{ id: "calendar:event:1", title: "Review", kind: "meeting", status, roleIds: [], projectIds: [], startsAt }], sources: [{ id: "google-calendar", kind: "calendar", status: sourceStatus, observedAt: "2026-07-27T09:00:00Z" }] });
const changes = () => compareSituationalAwarenessSnapshots(createSituationalAwarenessSnapshot({ snapshotId: "before", observedAt: "2026-07-27T09:00:00Z", state: state("scheduled", "2026-07-28T10:00:00Z") }), createSituationalAwarenessSnapshot({ snapshotId: "after", observedAt: "2026-07-27T10:00:00Z", state: state("cancelled", "2026-07-28T11:00:00Z", "unavailable") }));

describe("Executive Attention Layer", () => {
  it("preserves separate deterministic matches and summary counts", () => { const queue = constructExecutiveAttentionQueue(changes(), new AttentionPolicyRegistry([...INITIAL_ATTENTION_POLICIES].reverse())); expect(queue.records.map(r => r.reason.code)).toEqual(["commitment.status.changed-to-cancelled", "commitment.start-time.changed", "source.availability.changed-to-unavailable"]); expect(queue.summary).toMatchObject({ evaluatedChanges: 2, elevatedChanges: 2, attentionRecords: 3, matchedPolicies: 3 }); expect(Object.isFrozen(queue.records[0].reason.evidence)).toBe(true); });
  it("is replay safe and independent of policy registration order", () => { const a = constructExecutiveAttentionQueue(changes(), new AttentionPolicyRegistry(INITIAL_ATTENTION_POLICIES)); const b = constructExecutiveAttentionQueue(changes(), new AttentionPolicyRegistry([...INITIAL_ATTENTION_POLICIES].reverse())); expect(a).toEqual(b); expect(createExecutiveAttentionQueue(JSON.parse(JSON.stringify(a)))).toEqual(a); });
  it("returns a canonical empty queue", () => { const same = compareSituationalAwarenessSnapshots(createSituationalAwarenessSnapshot({ snapshotId: "a", observedAt: "2026-07-27T09:00:00Z", state: state("scheduled", "2026-07-28T10:00:00Z") }), createSituationalAwarenessSnapshot({ snapshotId: "b", observedAt: "2026-07-27T09:00:00Z", state: state("scheduled", "2026-07-28T10:00:00Z") })); const q = constructExecutiveAttentionQueue(same, new AttentionPolicyRegistry()); expect(q.records).toEqual([]); expect(q.summary.evaluatedChanges).toBe(0); });
  it("rejects duplicate policy identifiers", () => expect(() => new AttentionPolicyRegistry([INITIAL_ATTENTION_POLICIES[0], INITIAL_ATTENTION_POLICIES[0]])).toThrow("duplicate attention policy identifier"));
  it("uses bounded absence semantics for removal", () => { const before = createSituationalAwarenessSnapshot({ snapshotId: "a", observedAt: "2026-07-27T09:00:00Z", state: state("scheduled", "2026-07-28T10:00:00Z") }); const after = createSituationalAwarenessSnapshot({ snapshotId: "b", observedAt: "2026-07-27T10:00:00Z", state: createSituationalAwareness({ identity: { userId: "u", displayName: "User" } }) }); const q = constructExecutiveAttentionQueue(compareSituationalAwarenessSnapshots(before, after), new AttentionPolicyRegistry(INITIAL_ATTENTION_POLICIES)); expect(q.records[0].reason.code).toBe("commitment.absent-from-current-snapshot"); expect(q.records[0].reason.message).not.toMatch(/deleted|cancelled/); });
});
