import type { GovernedActionProposalDefinition,GovernedActionProposalInput,GovernedActionProposalKind,GovernedActionProposalPolicy,GovernedActionProposalPolicyResult,GovernedActionProposalScope } from "./types";
const candidates=(i:GovernedActionProposalInput,d:GovernedActionProposalDefinition)=>{const requested=d.candidateSelectors.length?d.candidateSelectors:i.executiveReasoningRecord.observations.filter(x=>x.reasonCode==="candidate-remains-available-for-consideration").flatMap(x=>x.candidatePlanIds);return [...new Set(requested)].sort()};
const refs=(i:GovernedActionProposalInput,d:GovernedActionProposalDefinition)=>{const ids=new Set(candidates(i,d));return {candidatePlanIds:[...ids],observationIds:i.executiveReasoningRecord.observations.filter(x=>x.candidatePlanIds.some(id=>ids.has(id))||!x.candidatePlanIds.length).map(x=>x.observationId),reasoningQuestionIds:i.executiveReasoningRecord.questions.filter(x=>x.candidatePlanIds.some(id=>ids.has(id))||!x.candidatePlanIds.length).map(x=>x.questionId),reasoningBoundaryIds:i.executiveReasoningRecord.boundaries.filter(x=>x.candidatePlanIds.some(id=>ids.has(id))||!x.candidatePlanIds.length).map(x=>x.boundaryId)}};
function create(identifier:string,name:string,kind:GovernedActionProposalKind,scope:GovernedActionProposalScope,build:(i:GovernedActionProposalInput,d:GovernedActionProposalDefinition)=>GovernedActionProposalPolicyResult):GovernedActionProposalPolicy{return Object.freeze({identifier,version:"1",metadata:Object.freeze({identifier,version:"1",displayName:name,description:`Deterministic bounded ${name.toLowerCase()} for authorised human consideration.`,supportedProposalKinds:Object.freeze([kind]),supportedProposalScopes:Object.freeze([scope]),origin:"sprint-3.23",status:"active" as const}),supportedProposalKinds:Object.freeze([kind]),supportedProposalScopes:Object.freeze([scope]),applies:(i:GovernedActionProposalInput,d:GovernedActionProposalDefinition)=>{const n=candidates(i,d).length,min=d.applicability.minimumCandidateCount??0,max=d.applicability.maximumCandidateCount??Number.MAX_SAFE_INTEGER;return d.proposalKind===kind&&d.proposalScope===scope&&n>=min&&n<=max},propose:build})}
const ready=(i:GovernedActionProposalInput,d:GovernedActionProposalDefinition,reasonCode:GovernedActionProposalPolicyResult["reasonCode"]):GovernedActionProposalPolicyResult=>({status:"ready_for_human_review",reasonCode,payload:{humanReviewRequired:true},...refs(i,d)});
export const singleCandidateConsiderationPolicy=create("proposal.single-candidate-consideration","Single Candidate Consideration","consider_candidate","single_candidate",(i,d)=>ready(i,d,"candidate-available-for-human-consideration"));
export const multipleCandidateConsiderationPolicy=create("proposal.multiple-candidate-consideration","Multiple Candidate Consideration","consider_multiple_candidates","multiple_candidates",(i,d)=>ready(i,d,"multiple-candidates-available-without-preference"));
export const conditionalConsiderationPolicy=create("proposal.conditional-consideration","Conditional Consideration","propose_conditional_consideration","planning_set",(i,d)=>({...ready(i,d,"proposal-conditions-present"),status:"draft"}));
export const evidenceResolutionPolicy=create("proposal.evidence-resolution","Evidence Resolution","defer_pending_evidence","evidence_resolution",(i,d)=>({status:"unresolved",reasonCode:"defer-until-evidence-resolved",payload:{humanReviewRequired:true},...refs(i,d),evidenceReferences:d.requiredEvidenceReferences??[],conditions:(d.requiredEvidenceReferences??[]).map(x=>({conditionType:"evidence_required",conditionStatus:"unresolved",sourceCanonicalReference:x,requiredEvidenceReferences:[x],reasonCode:"evidence-required-before-review"})),questions:[{reasonCode:"proposal-unresolved-evidence",requiredEvidenceReferences:d.requiredEvidenceReferences??[]}]}));
export const authorityConfirmationPolicy=create("proposal.authority-confirmation","Authority Confirmation","request_authority_confirmation","authority_resolution",(i,d)=>({status:"unresolved",reasonCode:"authority-confirmation-required",payload:{humanReviewRequired:true},...refs(i,d),authorities:(d.requiredAuthorityReferences??[]).map(x=>({authorityType:"human_executive",sourceGovernanceReference:x,requirementStatus:"unresolved",reasonCode:"proposal-unresolved-authority"})),questions:[{reasonCode:"proposal-unresolved-authority",requiredAuthorityType:"human_executive",...(d.requiredAuthorityReferences?.[0]?{requiredAuthorityReference:d.requiredAuthorityReferences[0]}:{})}]}));
export const humanArbitrationPolicy=create("proposal.human-arbitration","Human Arbitration","request_human_arbitration","governance_escalation",(i,d)=>({status:"unresolved",reasonCode:"human-arbitration-required",payload:{conflictResolved:false,humanReviewRequired:true},...refs(i,d),boundaries:[{boundaryType:"governance_escalation_required",boundaryStatus:"unresolved",sourceReasoningReference:refs(i,d).reasoningBoundaryIds[0]??i.executiveReasoningRecord.reasoningRecordId,reasonCode:"human-arbitration-required"}]}));
export const preserveOptionsPolicy=create("proposal.preserve-options","Preserve Options","preserve_options","multiple_candidates",(i,d)=>ready(i,d,"preserve-options-without-selection"));
export const explicitCombinationConsiderationPolicy=create("proposal.explicit-combination-consideration","Explicit Combination Consideration","consider_explicit_combination","multiple_candidates",(i,d)=>ready(i,d,"explicit-combination-authorised"));
export const productionProposalPolicies=Object.freeze([authorityConfirmationPolicy,conditionalConsiderationPolicy,evidenceResolutionPolicy,explicitCombinationConsiderationPolicy,humanArbitrationPolicy,multipleCandidateConsiderationPolicy,preserveOptionsPolicy,singleCandidateConsiderationPolicy]);
