import type { ExecutiveDeliberationContext } from "../deliberation";
import type { CanonicalValue, ConstraintSet, IntentSet } from "../intent";
import type { CandidatePlanSet } from "../planning/candidates";
import type { CandidatePlanComparisonSet } from "../planning/comparison";
import type { EvaluatedCandidatePlanSet } from "../planning/evaluation";
import type { ExecutiveReasoningRecord } from "../reasoning";

export type GovernedActionProposalStatus="draft"|"ready_for_human_review"|"blocked"|"unresolved"|"not_applicable";
export type GovernedActionProposalKind="consider_candidate"|"consider_multiple_candidates"|"defer_pending_evidence"|"request_authority_confirmation"|"request_human_arbitration"|"propose_conditional_consideration"|"preserve_options"|"no_action_pending_resolution"|"consider_explicit_combination";
export type GovernedActionProposalScope="single_candidate"|"multiple_candidates"|"planning_set"|"evidence_resolution"|"authority_resolution"|"governance_escalation";
export type GovernedActionProposalReasonCode="candidate-available-for-human-consideration"|"multiple-candidates-available-without-preference"|"proposal-conditions-present"|"proposal-blocked-by-explicit-boundary"|"proposal-unresolved-evidence"|"proposal-unresolved-authority"|"proposal-ready-for-human-review"|"human-arbitration-required"|"evidence-required-before-review"|"approval-required-before-execution"|"authority-confirmation-required"|"comparison-does-not-establish-preference"|"preserve-options-without-selection"|"defer-until-evidence-resolved"|"no-action-until-boundary-resolved"|"explicit-combination-authorised"|"explicit-combination-not-authorised"|"execution-boundary-not-crossed";
export type GovernedActionProposalConditionType="evidence_required"|"approval_required"|"dependency_resolution_required"|"assumption_resolution_required"|"temporal_prerequisite"|"resource_prerequisite"|"governance_prerequisite"|"privacy_prerequisite"|"human_arbitration_required"|"comparison_limitation_acknowledged";
export type GovernedActionProposalAuthorityType="human_executive"|"delegated_approver"|"governance_body"|"policy_owner"|"risk_owner"|"privacy_authority"|"financial_authority"|"operational_authority";
export type GovernedActionProposalBoundaryType="human_review_required"|"approval_required"|"evidence_unresolved"|"authority_unresolved"|"governance_escalation_required"|"execution_prohibited"|"temporal_boundary"|"resource_boundary"|"privacy_boundary"|"legal_boundary";
export type GovernedActionProposalSelector="observations"|"questions"|"boundaries"|"candidate_availability"|"evidence"|"authority"|"comparisons"|"planning_set";
export interface GovernedActionProposalPolicyMetadata{readonly identifier:string;readonly version:string;readonly displayName:string;readonly description:string;readonly supportedProposalKinds:readonly GovernedActionProposalKind[];readonly supportedProposalScopes:readonly GovernedActionProposalScope[];readonly origin:string;readonly status:"active"|"inactive"}
export interface GovernedActionProposalConditionDefinition{readonly conditionType:GovernedActionProposalConditionType;readonly conditionStatus:GovernedActionProposalStatus;readonly sourceCanonicalReference:string;readonly candidatePlanIds?:readonly string[];readonly requiredEvidenceReferences?:readonly string[];readonly requiredAuthorityReferences?:readonly string[];readonly reasonCode:GovernedActionProposalReasonCode}
export interface GovernedActionProposalDefinition{readonly identifier:string;readonly version:string;readonly proposalKind:GovernedActionProposalKind;readonly proposalScope:GovernedActionProposalScope;readonly sourceReasoningSelectors:readonly GovernedActionProposalSelector[];readonly candidateSelectors:readonly string[];readonly applicability:Readonly<{readonly reasoningStatuses?:readonly string[];readonly reasonCodes?:readonly string[];readonly minimumCandidateCount?:number;readonly maximumCandidateCount?:number}>;readonly supportedStatuses:readonly GovernedActionProposalStatus[];readonly policyIdentifier:string;readonly origin:string;readonly requiredEvidenceReferences?:readonly string[];readonly requiredAuthorityReferences?:readonly string[];readonly requiredConditions?:readonly GovernedActionProposalConditionDefinition[];readonly explicitCandidateCombinationIdentifier?:string}
export interface GovernedActionProposalInput{readonly context:ExecutiveDeliberationContext;readonly intentSet:IntentSet;readonly constraintSet:ConstraintSet;readonly candidatePlanSet:CandidatePlanSet;readonly evaluatedCandidatePlanSet:EvaluatedCandidatePlanSet;readonly candidatePlanComparisonSet:CandidatePlanComparisonSet;readonly executiveReasoningRecord:ExecutiveReasoningRecord;readonly definitions:readonly GovernedActionProposalDefinition[]}
export interface GovernedActionProposalProvenance{readonly contextId:string;readonly intentSetId:string;readonly constraintSetId:string;readonly candidatePlanSetId:string;readonly evaluatedCandidatePlanSetId:string;readonly comparisonSetId:string;readonly reasoningRecordId:string;readonly definitionIdentifier:string;readonly definitionVersion:string;readonly policyIdentifier:string;readonly policyVersion:string;readonly origin:string;readonly candidatePlanIds:readonly string[];readonly evaluationIds:readonly string[];readonly comparisonIds:readonly string[];readonly observationIds:readonly string[];readonly reasoningQuestionIds:readonly string[];readonly reasoningBoundaryIds:readonly string[];readonly evidenceReferences:readonly string[];readonly governanceReferences:readonly string[];readonly status:GovernedActionProposalStatus;readonly reasonCode:GovernedActionProposalReasonCode}
export interface GovernedActionProposalCondition{readonly conditionId:string;readonly conditionType:GovernedActionProposalConditionType;readonly conditionStatus:GovernedActionProposalStatus;readonly sourceCanonicalReference:string;readonly candidatePlanIds:readonly string[];readonly requiredEvidenceReferences:readonly string[];readonly requiredAuthorityReferences:readonly string[];readonly reasonCode:GovernedActionProposalReasonCode;readonly policyIdentifier:string;readonly policyVersion:string;readonly provenance:GovernedActionProposalProvenance}
export interface GovernedActionProposalAuthorityRequirement{readonly authorityRequirementId:string;readonly authorityType:GovernedActionProposalAuthorityType;readonly sourceGovernanceReference:string;readonly proposalId:string;readonly candidatePlanIds:readonly string[];readonly requirementStatus:GovernedActionProposalStatus;readonly reasonCode:GovernedActionProposalReasonCode;readonly provenance:GovernedActionProposalProvenance}
export interface GovernedActionProposalQuestion{readonly questionId:string;readonly definitionIdentifier:string;readonly definitionVersion:string;readonly policyIdentifier:string;readonly policyVersion:string;readonly reasonCode:GovernedActionProposalReasonCode;readonly proposalId:string;readonly candidatePlanIds:readonly string[];readonly requiredEvidenceReferences:readonly string[];readonly requiredAuthorityType?:GovernedActionProposalAuthorityType;readonly requiredAuthorityReference?:string;readonly provenance:GovernedActionProposalProvenance}
export interface GovernedActionProposalBoundary{readonly boundaryId:string;readonly boundaryType:GovernedActionProposalBoundaryType;readonly boundaryStatus:GovernedActionProposalStatus;readonly sourceReasoningReference:string;readonly proposalId:string;readonly candidatePlanIds:readonly string[];readonly reasonCode:GovernedActionProposalReasonCode;readonly provenance:GovernedActionProposalProvenance}
export interface GovernedActionProposal{readonly proposalId:string;readonly definitionIdentifier:string;readonly definitionVersion:string;readonly policyIdentifier:string;readonly policyVersion:string;readonly proposalKind:GovernedActionProposalKind;readonly proposalScope:GovernedActionProposalScope;readonly proposalStatus:GovernedActionProposalStatus;readonly reasonCode:GovernedActionProposalReasonCode;readonly candidatePlanIds:readonly string[];readonly reasoningObservationIds:readonly string[];readonly reasoningQuestionIds:readonly string[];readonly reasoningBoundaryIds:readonly string[];readonly conditions:readonly GovernedActionProposalCondition[];readonly authorityRequirements:readonly GovernedActionProposalAuthorityRequirement[];readonly evidenceRequirements:readonly string[];readonly unresolvedQuestions:readonly GovernedActionProposalQuestion[];readonly boundaries:readonly GovernedActionProposalBoundary[];readonly payload:CanonicalValue;readonly provenance:GovernedActionProposalProvenance}
export interface GovernedActionProposalSummary{readonly totalProposals:number;readonly proposalsByKind:Readonly<Record<string,number>>;readonly proposalsByScope:Readonly<Record<string,number>>;readonly proposalsByStatus:Readonly<Record<string,number>>;readonly proposalsByPolicy:Readonly<Record<string,number>>;readonly totalConditions:number;readonly conditionsByType:Readonly<Record<string,number>>;readonly totalAuthorityRequirements:number;readonly authorityRequirementsByType:Readonly<Record<string,number>>;readonly totalProposalQuestions:number;readonly questionsByReasonCode:Readonly<Record<string,number>>;readonly totalProposalBoundaries:number;readonly boundariesByType:Readonly<Record<string,number>>;readonly candidatesReferenced:number;readonly proposalsReadyForHumanReview:number;readonly proposalsBlocked:number;readonly proposalsUnresolved:number;readonly proposalsPreservingMultipleOptions:number;readonly proposalsRequiringEvidence:number;readonly proposalsRequiringAuthorityConfirmation:number;readonly proposalsRequiringHumanArbitration:number}
export interface GovernedActionProposalSet{readonly proposalSetId:string;readonly contextId:string;readonly intentSetId:string;readonly constraintSetId:string;readonly candidatePlanSetId:string;readonly evaluatedCandidatePlanSetId:string;readonly comparisonSetId:string;readonly reasoningRecordId:string;readonly proposals:readonly GovernedActionProposal[];readonly summary:GovernedActionProposalSummary;readonly activePolicies:readonly Readonly<{identifier:string;version:string}>[];readonly definitions:readonly Readonly<{identifier:string;version:string}>[];readonly provenance:Readonly<{proposalIds:readonly string[]}>}
export interface GovernedActionProposalPolicyResult{readonly status:GovernedActionProposalStatus;readonly reasonCode:GovernedActionProposalReasonCode;readonly candidatePlanIds?:readonly string[];readonly observationIds?:readonly string[];readonly reasoningQuestionIds?:readonly string[];readonly reasoningBoundaryIds?:readonly string[];readonly evidenceReferences?:readonly string[];readonly payload:CanonicalValue;readonly conditions?:readonly GovernedActionProposalConditionDefinition[];readonly authorities?:readonly Readonly<{authorityType:GovernedActionProposalAuthorityType;sourceGovernanceReference:string;candidatePlanIds?:readonly string[];requirementStatus:GovernedActionProposalStatus;reasonCode:GovernedActionProposalReasonCode}>[];readonly questions?:readonly Readonly<{reasonCode:GovernedActionProposalReasonCode;candidatePlanIds?:readonly string[];requiredEvidenceReferences?:readonly string[];requiredAuthorityType?:GovernedActionProposalAuthorityType;requiredAuthorityReference?:string}>[];readonly boundaries?:readonly Readonly<{boundaryType:GovernedActionProposalBoundaryType;boundaryStatus:GovernedActionProposalStatus;sourceReasoningReference:string;candidatePlanIds?:readonly string[];reasonCode:GovernedActionProposalReasonCode}>[]}
export interface GovernedActionProposalPolicy{readonly identifier:string;readonly version:string;readonly metadata:GovernedActionProposalPolicyMetadata;readonly supportedProposalKinds:readonly GovernedActionProposalKind[];readonly supportedProposalScopes:readonly GovernedActionProposalScope[];applies(input:GovernedActionProposalInput,definition:GovernedActionProposalDefinition):boolean;propose(input:GovernedActionProposalInput,definition:GovernedActionProposalDefinition):GovernedActionProposalPolicyResult}
export interface GovernedActionProposalRegistry{register(policy:GovernedActionProposalPolicy):void;policies():readonly GovernedActionProposalPolicy[]}
export interface GovernedActionProposalEngine{propose(input:GovernedActionProposalInput):GovernedActionProposalSet}
