import type { GovernedActionProposalDefinition,GovernedActionProposalPolicy } from "./types";
export const compareText=(a:string,b:string)=>a<b?-1:a>b?1:0;
export const statuses=["draft","ready_for_human_review","blocked","unresolved","not_applicable"] as const;
export const kinds=["consider_candidate","consider_multiple_candidates","defer_pending_evidence","request_authority_confirmation","request_human_arbitration","propose_conditional_consideration","preserve_options","no_action_pending_resolution","consider_explicit_combination"] as const;
export const scopes=["single_candidate","multiple_candidates","planning_set","evidence_resolution","authority_resolution","governance_escalation"] as const;
export const conditionTypes=["evidence_required","approval_required","dependency_resolution_required","assumption_resolution_required","temporal_prerequisite","resource_prerequisite","governance_prerequisite","privacy_prerequisite","human_arbitration_required","comparison_limitation_acknowledged"] as const;
export const authorityTypes=["human_executive","delegated_approver","governance_body","policy_owner","risk_owner","privacy_authority","financial_authority","operational_authority"] as const;
export const reasonCodes=["candidate-available-for-human-consideration","multiple-candidates-available-without-preference","proposal-conditions-present","proposal-blocked-by-explicit-boundary","proposal-unresolved-evidence","proposal-unresolved-authority","proposal-ready-for-human-review","human-arbitration-required","evidence-required-before-review","approval-required-before-execution","authority-confirmation-required","comparison-does-not-establish-preference","preserve-options-without-selection","defer-until-evidence-resolved","no-action-until-boundary-resolved","explicit-combination-authorised","explicit-combination-not-authorised","execution-boundary-not-crossed"] as const;
export const selectors=["observations","questions","boundaries","candidate_availability","evidence","authority","comparisons","planning_set"] as const;
export function required(v:unknown,label:string):asserts v is string{if(typeof v!=="string"||!v.trim())throw new Error(`${label} must be a non-empty string`)}
export function clone<T>(v:T):T{if(Array.isArray(v))return v.map(clone) as T;if(v&&typeof v==="object")return Object.fromEntries(Object.entries(v).map(([k,x])=>[k,clone(x)])) as T;return v}
export function deepFreeze<T>(v:T):T{if(v&&typeof v==="object"&&!Object.isFrozen(v)){Object.values(v).forEach(deepFreeze);Object.freeze(v)}return v}
export function jsonCompatible(v:unknown,p="value",seen=new Set<object>()):void{if(v===null||typeof v==="string"||typeof v==="boolean"||(typeof v==="number"&&Number.isFinite(v)))return;if(!v||typeof v!=="object"||seen.has(v as object)||(!Array.isArray(v)&&Object.getPrototypeOf(v)!==Object.prototype))throw new Error(`${p} must contain only JSON-compatible values`);seen.add(v as object);Object.entries(v).forEach(([k,x])=>jsonCompatible(x,`${p}.${k}`,seen));seen.delete(v as object)}
export function canonical(v:unknown):string{if(Array.isArray(v))return `[${v.map(canonical).join(",")}]`;if(v&&typeof v==="object")return `{${Object.keys(v).sort(compareText).map(k=>`${JSON.stringify(k)}:${canonical((v as Record<string,unknown>)[k])}`).join(",")}}`;return JSON.stringify(v)}
export const identity=(kind:string,...parts:unknown[])=>`${kind}:${parts.map(x=>encodeURIComponent(typeof x==="string"?x:canonical(x))).join(":")}`;
export function validateDefinition(d:GovernedActionProposalDefinition):void{jsonCompatible(d,"proposal definition");required(d?.identifier,"definition identifier");required(d.version,"definition version");required(d.policyIdentifier,"definition policy identifier");required(d.origin,"definition origin");if(!kinds.includes(d.proposalKind)||!scopes.includes(d.proposalScope)||!Array.isArray(d.sourceReasoningSelectors)||d.sourceReasoningSelectors.some(x=>!selectors.includes(x))||!Array.isArray(d.candidateSelectors)||!d.applicability||!Array.isArray(d.supportedStatuses)||d.supportedStatuses.some(x=>!statuses.includes(x)))throw new Error("malformed proposal definition");if(d.proposalKind==="consider_explicit_combination"&&!d.explicitCandidateCombinationIdentifier)throw new Error("explicit combination is not authorised");for(const key of ["weight","score","rank","preference","recommendation","prompt","approvalDecision","executionInstruction"]){if(key in (d as unknown as Record<string,unknown>))throw new Error(`prohibited proposal definition field: ${key}`)}}
export function validatePolicy(p:GovernedActionProposalPolicy):void{if(!p||typeof p!=="object")throw new Error("proposal policy must be an object");required(p.identifier,"policy identifier");required(p.version,"policy version");if(p.metadata?.identifier!==p.identifier||p.metadata?.version!==p.version)throw new Error("policy metadata identity is inconsistent");[p.metadata?.displayName,p.metadata?.description,p.metadata?.origin].forEach((x,i)=>required(x,`policy metadata field ${i}`));if(!["active","inactive"].includes(p.metadata.status)||!p.supportedProposalKinds?.length||p.supportedProposalKinds.some(x=>!kinds.includes(x))||!p.supportedProposalScopes?.length||p.supportedProposalScopes.some(x=>!scopes.includes(x)))throw new Error("invalid proposal policy metadata");jsonCompatible(p.metadata,"policy metadata");if(typeof p.applies!=="function"||typeof p.propose!=="function")throw new Error("proposal policy contract is incomplete")}
