import {createHash} from "node:crypto";
import type {ExecutiveOperatingSystemInput,ExecutiveOperatingSystemExecutionTrace,ExecutiveOperatingSystemResult,ExecutiveOperatingSystemStageTrace,ExecutiveRunPublicationReference,ExecutiveRunRecord,ExecutiveOperatingSystemRuntimeError} from "./types";
import {EXECUTIVE_RUN_RECORD_CONTRACT_VERSION} from "./types";
import {deepFreeze} from "./validation";

const stable=(value:unknown):string=>JSON.stringify(value,(_key,item)=>item&&typeof item==="object"&&!Array.isArray(item)?Object.fromEntries(Object.entries(item).sort(([a],[b])=>a.localeCompare(b))):item);
const id=(prefix:string,value:unknown)=>`${prefix}:${createHash("sha256").update(stable(value)).digest("hex")}`;
export const EXECUTIVE_RUNTIME_VERSION="canonical-eos-runtime-v1";
const TYPES=["ProjectionArtifactSet","ExecutiveStateSnapshot","ExecutiveContextSnapshot","SnapshotChangeSet","ExecutiveAttentionQueue","ExecutiveSituationSet","SituationAssessmentSet","ExecutiveDeliberationContext","IntentSet","ConstraintSet","CandidatePlanSet","PlanEvaluationSet","PlanComparisonSet","ExecutiveReasoningRecord","GovernedActionProposalSet","ExecutiveCapabilityRoutingPlan","ExecutiveCapabilityInvocationHandoff","CapabilityInvocationEnvelope","CapabilityInvocationRecord","CapabilityExecutionResult"] as const;

export function publicationReferences(result:Omit<ExecutiveOperatingSystemResult,"executiveRunRecord"|"trace">):readonly ExecutiveRunPublicationReference[]{
 const values:readonly (readonly string[])[]=[result.executiveState.artifacts.map(x=>x.artifactId),[result.executiveState.snapshotId],[result.executiveContextSnapshot.contextId],[`${result.changes.previousSnapshotId}->${result.changes.currentSnapshotId}`],[result.attention.queueId],[`${result.situations.currentSnapshotId}|${result.situations.queueId}`],[result.assessment.situationSetId],[result.executiveDeliberationContext.deliberationContextId!],[result.intent.intentSetId],[result.constraints.constraintSetId],[result.candidatePlans.candidatePlanSetId],[result.evaluation.evaluatedCandidatePlanSetId],[result.comparison.comparisonSetId],[result.reasoning.reasoningRecordId],[result.proposals.proposalSetId],[result.capabilityRoutingPlan.routingPlanId],[result.executiveCapabilityInvocationHandoff.handoffId],[result.capabilityInvocationEnvelope.envelopeId],[result.capabilityInvocationRecord.invocationRecordId],[result.capabilityExecutionResult.executionResultId]];
 return TYPES.map((publicationType,index)=>({publicationType,publicationIds:[...values[index]],status:"published" as const}));
}

export function publishExecutiveRunRecord(input:ExecutiveOperatingSystemInput,result:Omit<ExecutiveOperatingSystemResult,"executiveRunRecord"|"trace">,orderedStageTrace:ExecutiveOperatingSystemExecutionTrace):ExecutiveRunRecord{
 const refs=publicationReferences(result);
 const replayIdentity={projectionArtifactIds:input.projectionArtifacts.artifacts.map(x=>x.provenance.sourceId).sort(),previousLifecycleSnapshotId:input.projectionArtifacts.previousSnapshot.snapshotId,observedAt:input.projectionArtifacts.observedAt,referenceTime:input.referenceTime,runtimeVersion:EXECUTIVE_RUNTIME_VERSION,configurationIdentity:id("runtime-configuration",input.configuration)};
 const traceIdentity=id("executive-runtime-trace",orderedStageTrace);
 const policies=[...new Set(orderedStageTrace.stages.flatMap(x=>x.policyId?[x.policyId]:[]))].sort();
 const recordBody={contractVersion:EXECUTIVE_RUN_RECORD_CONTRACT_VERSION,runMode:"governed_execution" as const,outcome:"completed" as const,replayIdentity,runtimeIdentity:{coordinator:"DeterministicExecutiveOperatingSystemRuntime" as const,runtimeVersion:EXECUTIVE_RUNTIME_VERSION,traceIdentity},policyIdentities:policies,publicationReferences:refs,authorityEvidence:{approvalState:result.capabilityInvocationRecord.approvalState,authorityValidationOutcome:result.capabilityInvocationRecord.authorityValidationOutcome,authorityRequirementIds:[...result.capabilityInvocationRecord.authorityRequirements],grantsApproval:false as const},executionEvidence:{invocationDisposition:result.capabilityInvocationRecord.invocationDisposition,executionStatus:result.capabilityExecutionResult.executionStatus,executionAttempted:result.capabilityExecutionResult.executionAttempted,sideEffectAttempted:result.capabilityExecutionResult.sideEffectAttempted,sideEffectConfirmed:result.capabilityExecutionResult.sideEffectConfirmed},validationEvidence:{status:"valid" as const,validatedStageIds:orderedStageTrace.stages.map(x=>x.stageId)},orderedStageTrace,immutableFailures:[],auditMetadata:{owner:"DeterministicExecutiveOperatingSystemRuntime" as const,publishedAt:input.referenceTime}};
 return deepFreeze({executiveRunRecordId:id("executive-run-record",recordBody),...recordBody});
}

const stageTypes:Readonly<Record<string,readonly string[]>>={state_assembly:["ExecutiveStateSnapshot"],executive_context_derivation:["ExecutiveContextSnapshot"],snapshot_lifecycle:["SnapshotChangeSet"],executive_attention:["ExecutiveAttentionQueue"],situation_formation:["ExecutiveSituationSet"],situation_assessment:["SituationAssessmentSet"],executive_deliberation_context:["ExecutiveDeliberationContext"],intent_and_constraints:["IntentSet","ConstraintSet"],candidate_plan_construction:["CandidatePlanSet"],candidate_plan_evaluation:["PlanEvaluationSet"],candidate_plan_comparison:["PlanComparisonSet"],executive_reasoning:["ExecutiveReasoningRecord"],governed_action_proposal:["GovernedActionProposalSet"],capability_routing:["ExecutiveCapabilityRoutingPlan"],capability_invocation_handoff:["ExecutiveCapabilityInvocationHandoff"],capability_invocation_envelope:["CapabilityInvocationEnvelope"],capability_invocation:["CapabilityInvocationRecord"],capability_execution:["CapabilityExecutionResult"]};
export function publishFailedExecutiveRunRecord(input:ExecutiveOperatingSystemInput,traces:readonly ExecutiveOperatingSystemStageTrace[],failure:ExecutiveOperatingSystemRuntimeError):ExecutiveRunRecord{
 const byType=new Map<string,readonly string[]>();
 byType.set("ProjectionArtifactSet",input.projectionArtifacts.artifacts.map(x=>id("projection-artifact",x)).sort());
 for(const trace of traces){const types=stageTypes[trace.stageId]??[];types.forEach((type,index)=>byType.set(type,types.length===1?trace.outputArtifactIds:trace.outputArtifactIds.slice(index,index+1)))}
 const refs=TYPES.map(publicationType=>{const publicationIds=byType.get(publicationType)??[];return {publicationType,publicationIds,status:publicationIds.length?"published" as const:"absent" as const}});
 const orderedStageTrace=deepFreeze({stages:[...traces]});
 const replayIdentity={projectionArtifactIds:input.projectionArtifacts.artifacts.map(x=>x.provenance.sourceId).sort(),previousLifecycleSnapshotId:input.projectionArtifacts.previousSnapshot.snapshotId,observedAt:input.projectionArtifacts.observedAt,referenceTime:input.referenceTime,runtimeVersion:EXECUTIVE_RUNTIME_VERSION,configurationIdentity:id("runtime-configuration",input.configuration)};
 const traceIdentity=id("executive-runtime-trace",orderedStageTrace),policies=[...new Set(traces.flatMap(x=>x.policyId?[x.policyId]:[]))].sort();
 const body={contractVersion:EXECUTIVE_RUN_RECORD_CONTRACT_VERSION,runMode:"governed_execution" as const,outcome:"failed" as const,replayIdentity,runtimeIdentity:{coordinator:"DeterministicExecutiveOperatingSystemRuntime" as const,runtimeVersion:EXECUTIVE_RUNTIME_VERSION,traceIdentity},policyIdentities:policies,publicationReferences:refs,authorityEvidence:{approvalState:"not_available",authorityValidationOutcome:"not_evaluated",authorityRequirementIds:[],grantsApproval:false as const},executionEvidence:{invocationDisposition:"not_available",executionStatus:"not_available",executionAttempted:false,sideEffectAttempted:false,sideEffectConfirmed:false},validationEvidence:{status:"valid" as const,validatedStageIds:traces.map(x=>x.stageId)},orderedStageTrace,immutableFailures:[{stage:failure.stage,category:failure.category,reasonCode:failure.reasonCode,inputArtifactIds:[...failure.inputArtifactIds]}],auditMetadata:{owner:"DeterministicExecutiveOperatingSystemRuntime" as const,publishedAt:input.referenceTime}};
 return deepFreeze({executiveRunRecordId:id("executive-run-record",body),...body});
}
