import { mkdtemp, readFile } from "node:fs/promises";
import { tmpdir } from "node:os";
import path from "node:path";
import { describe, expect, it } from "vitest";
import { assembleMigrationRecommendationEvidence, createAnonymisedValidationSummary, deriveEngineeringSummary, determineMigrationRecommendation, evaluateMigrationGate, LEGACY_COMPARISON_STATUSES, recordOperationalValidation, renderValidationDashboard, validateProvenance } from ".";
import type { LegacyComparisonStatus, OperationalScenarioRecord, ValidationProvenance } from ".";
const generatedAt="2026-07-29T12:00:00.000Z";
const provenance=(executionSource:ValidationProvenance["executionSource"]):ValidationProvenance=>{
 const base={
  synthetic:{executionSource:"synthetic",connectorSource:"fixture",validationLevel:"framework",oauthSession:"not_applicable"},
  manual_observation:{executionSource:"manual_observation",connectorSource:"manual_ui_observation",validationLevel:"exploratory",oauthSession:"not_applicable"},
  recorded_replay:{executionSource:"recorded_replay",connectorSource:"recorded_connector_output",validationLevel:"replay",oauthSession:"not_applicable"},
  authenticated_deployment:{executionSource:"authenticated_deployment",connectorSource:"live_google_calendar",validationLevel:"operational",oauthSession:"present"},
  mixed:{executionSource:"mixed",connectorSource:"mixed",validationLevel:"exploratory",oauthSession:"not_applicable"},
 }[executionSource];
 return {...base,generatedBy:"test",generatedAt,runnerVersion:"runner-v1"} as ValidationProvenance;
};
const scenario=():OperationalScenarioRecord=>({scenarioId:"OV-1",scenarioCategory:"CURRENT_WORKING_DAY",validationDate:"2026-07-29",connectorEvidence:{title:"secret"},canonicalProjection:{},situationalAwareness:{},availabilityComputation:{},executiveRepresentation:{},comparisonClassification:"Equivalent",outcomeReason:"EXPECTED_MATCH",matchedClaims:1,comparedClaims:1});
const attestation={reportWritten:true as const,challengeCompleted:true as const,attestedAt:generatedAt,confirmedAt:generatedAt,confirmingOperator:"operator",challengeId:"random",reportHash:"a".repeat(64),runnerVersion:"runner-v1"};
describe("provenance and evidence gating",()=>{
 it("accepts all five exact combinations and rejects inconsistencies",()=>{for(const source of ["synthetic","manual_observation","recorded_replay","authenticated_deployment","mixed"] as const) expect(()=>validateProvenance(provenance(source))).not.toThrow();expect(()=>validateProvenance({...provenance("authenticated_deployment"),oauthSession:"absent"})).toThrow("inconsistent");});
 it("creates one evidence-backed recommendation and derives the gate and reviewer summary from it",()=>{const scenarios=Array.from({length:10},(_,i)=>({...scenario(),scenarioId:`OV-${i}`,scenarioCategory:["CURRENT_WORKING_DAY","TOMORROW","OVERLAPPING_COMMITMENTS","NO_COMMITMENTS","BUSY_AFTERNOON","RECURRING_COMMITMENT","CANCELLED_COMMITMENT","DECLINED_VISIBLE_INVITATION","ALL_DAY_COMMITMENT","MIXED_MEETING_DURATIONS"][i] as OperationalScenarioRecord["scenarioCategory"]}));const summary=createAnonymisedValidationSummary({runId:"run",provenance:provenance("authenticated_deployment"),operatorConfirmation:"confirmed",attestation,scenarios,deterministicValidationCompleted:true,legacyComparisonStatus:"EXECUTED"});expect(summary.migrationRecommendation.value).toBe("PROCEED");expect(evaluateMigrationGate(summary.migrationRecommendation)).toEqual({mayProceed:true,unmetConditions:[]});expect(deriveEngineeringSummary(summary.migrationRecommendation)).toEqual({implementationQuality:"PASS",evidenceSufficiency:"SUFFICIENT",migrationEvidence:"MIGRATION EVIDENCE SUFFICIENT"});expect(renderValidationDashboard(summary)).toContain("Operational Coverage\n100%\n\nLegacy Comparison Status\nEXECUTED");});
 it("derives compatibility booleans from every canonical status",()=>{expect(LEGACY_COMPARISON_STATUSES).toHaveLength(5);for(const status of LEGACY_COMPARISON_STATUSES){const evidence=assembleMigrationRecommendationEvidence({provenance:provenance("authenticated_deployment"),operatorConfirmation:"confirmed",attestation,scenarios:[scenario()],deterministicValidationCompleted:true,legacyComparisonStatus:status});expect(evidence.legacyComparisonEnabled).toBe(status!=="NOT_ENABLED");expect(evidence.legacyComparisonExecuted).toBe(status==="EXECUTED");}});
 it("requires an executed comparison in the current run before proceeding",()=>{const scenarios=Array.from({length:10},(_,i)=>({...scenario(),scenarioId:`OV-${i}`,scenarioCategory:["CURRENT_WORKING_DAY","TOMORROW","OVERLAPPING_COMMITMENTS","NO_COMMITMENTS","BUSY_AFTERNOON","RECURRING_COMMITMENT","CANCELLED_COMMITMENT","DECLINED_VISIBLE_INVITATION","ALL_DAY_COMMITMENT","MIXED_MEETING_DURATIONS"][i] as OperationalScenarioRecord["scenarioCategory"]}));for(const status of LEGACY_COMPARISON_STATUSES.filter(status=>status!=="EXECUTED")){const recommendation=determineMigrationRecommendation({provenance:provenance("authenticated_deployment"),operatorConfirmation:"confirmed",attestation,scenarios,deterministicValidationCompleted:true,legacyComparisonStatus:status});expect(recommendation).toMatchObject({value:"REFINE",basis:"LEGACY_COMPARISON_REQUIRED"});}});
 it("assembles deterministic evidence separately and freezes every recommendation layer",()=>{const input={provenance:provenance("authenticated_deployment"),operatorConfirmation:"confirmed" as const,attestation,scenarios:[scenario()],deterministicValidationCompleted:true,legacyComparisonStatus:"NOT_ENABLED" as LegacyComparisonStatus};const evidence=assembleMigrationRecommendationEvidence(input);expect(evidence).toEqual(assembleMigrationRecommendationEvidence(structuredClone(input)));const first=determineMigrationRecommendation(input),second=determineMigrationRecommendation(structuredClone(input));expect(first).toEqual(second);expect(Object.isFrozen(first)).toBe(true);expect(Object.isFrozen(first.evidence)).toBe(true);expect(Object.isFrozen(first.evidence.scenarioCoverage)).toBe(true);expect(()=>{(first.evidence.scenarioCoverage as {present:number}).present=99}).toThrow();});
 it("does not allow the reviewer dashboard to modify the authoritative recommendation",()=>{const summary=createAnonymisedValidationSummary({runId:"run",provenance:provenance("authenticated_deployment"),operatorConfirmation:"confirmed",attestation,scenarios:[scenario()],deterministicValidationCompleted:true,legacyComparisonStatus:"INCOMPLETE"});const before=JSON.stringify(summary.migrationRecommendation);deriveEngineeringSummary(summary.migrationRecommendation);evaluateMigrationGate(summary.migrationRecommendation);renderValidationDashboard(summary);expect(JSON.stringify(summary.migrationRecommendation)).toBe(before);expect(()=>{(summary.migrationRecommendation.evidence.scenarioCoverage as {present:number}).present=2}).toThrow();});
 it("creates a closed summary without evidence or challenge material",()=>{const summary=createAnonymisedValidationSummary({runId:"run",provenance:provenance("synthetic"),operatorConfirmation:"pending",scenarios:[scenario()],legacyComparisonStatus:"NOT_ENABLED"});expect(summary.migrationRecommendation.value).toBe("NOT_ASSESSED");const encoded=JSON.stringify(summary);expect(encoded).not.toContain("secret");expect(encoded).not.toContain("challengeId");});
 it("writes only protected, non-overwriting local reports",async()=>{const root=await mkdtemp(path.join(tmpdir(),"ov-"));const input={runId:"safe",provenance:provenance("synthetic"),operatorConfirmation:"pending" as const,scenarios:[scenario()],legacyComparisonStatus:"NOT_ENABLED" as const};const result=await recordOperationalValidation(input,{repositoryRoot:root});expect(await readFile(result.reportPath,"utf8")).toContain("connectorEvidence");await expect(recordOperationalValidation(input,{repositoryRoot:root})).rejects.toThrow();await expect(recordOperationalValidation({...input,runId:"../bad"},{repositoryRoot:root})).rejects.toThrow("unsafe");});
 it("prints the canonical comparison status from the CLI",async()=>{const cli=await readFile(path.resolve("scripts/run-operational-validation.ts"),"utf8");expect(cli).toContain("legacyComparisonStatus:");expect(cli).toContain("evidence.legacyComparisonStatus");expect(cli).not.toContain("legacyComparisonExecuted:");});
});
