import type { AttentionRecord } from "../attention";
import type { SituationFormationGroup, SituationFormationPolicy } from "./types";
import { compareText, deepFreeze } from "./validation";

type LinkedValue = { readonly parentId?: string; readonly parentCommitmentId?: string; readonly recurringSeriesId?: string; readonly projectIds?: readonly string[]; readonly roleIds?: readonly string[] };
const value = (record: AttentionRecord): LinkedValue => (record.current ?? record.previous ?? {}) as LinkedValue;
const build = (id: string, displayName: string, description: string, keys: (record: AttentionRecord) => readonly string[]): SituationFormationPolicy => deepFreeze({ id, version: "1.0.0", displayName, description, form(records) { const groups = new Map<string, AttentionRecord[]>(); for (const record of records) for (const key of [...new Set(keys(record))].sort(compareText)) groups.set(key, [...(groups.get(key) ?? []), record]); return [...groups.entries()].filter(([, members]) => members.length > 1).sort(([a], [b]) => compareText(a, b)).map(([key, members]): SituationFormationGroup => ({ key, reasonCode: `${id}.matched`, evidence: { groupingKey: key }, records: [...members].sort((a, b) => compareText(a.attentionId, b.attentionId)) })); } });

export const sameCanonicalEntityPolicy = build("situation.same-canonical-entity", "Same canonical entity", "Groups records with the same canonical domain and stable entity identifier in the current snapshot.", record => record.entityId ? [`${record.domain}:${record.entityId}:${record.currentSnapshotId}`] : []);
export const explicitParentRelationshipPolicy = build("situation.explicit-parent-relationship", "Explicit parent relationship", "Groups records sharing an explicitly represented parent or recurring-series reference.", record => { const v = value(record); return [v.parentId, v.parentCommitmentId, v.recurringSeriesId].filter((id): id is string => typeof id === "string" && id.length > 0).map(id => `parent:${id}`); });
export const explicitProjectRoleReferencePolicy = build("situation.explicit-project-role-reference", "Explicit project or role reference", "Groups records sharing canonical project or role identifiers.", record => { const v = value(record); return [...(Array.isArray(v.projectIds) ? v.projectIds.map(id => `project:${id}`) : []), ...(Array.isArray(v.roleIds) ? v.roleIds.map(id => `role:${id}`) : [])]; });
export const singletonFormationPolicy = build("situation.singleton", "Singleton formation", "Forms exactly one situation for each record unmatched by another formation policy.", () => []);
export const INITIAL_SITUATION_FORMATION_POLICIES = Object.freeze([explicitParentRelationshipPolicy, explicitProjectRoleReferencePolicy, sameCanonicalEntityPolicy, singletonFormationPolicy]);
