import { describe, expect, it } from "vitest";
import { createExecutiveAttentionQueue } from "../attention";
import type { AttentionRecord, ExecutiveAttentionQueue } from "../attention";
import { ExecutiveSituationEngine, INITIAL_SITUATION_FORMATION_POLICIES, SituationFormationRegistry, createExecutiveSituationSet, sameCanonicalEntityPolicy, singletonFormationPolicy } from ".";
import type { SituationFormationPolicy } from ".";

const record = (id: string, entityId: string, links: { projectIds?: string[]; roleIds?: string[] } = {}): AttentionRecord => ({ attentionId: id, domain: "commitments", changeType: "modified", entityId, previousSnapshotId: "before", currentSnapshotId: "after", previous: { id: entityId, title: entityId, kind: "meeting", status: "scheduled", roleIds: links.roleIds ?? [], projectIds: links.projectIds ?? [] }, current: { id: entityId, title: entityId, kind: "meeting", status: "cancelled", roleIds: links.roleIds ?? [], projectIds: links.projectIds ?? [] }, policy: { id: "attention.test", version: "1.0.0" }, reason: { code: "test", message: "Test attention record.", evidence: [] } });
const queue = (...records: AttentionRecord[]): ExecutiveAttentionQueue => { const elevatedChanges = new Set(records.map(r => `${r.domain}:${r.entityId}:${r.changeType}`)).size; return createExecutiveAttentionQueue({ queueId: "queue", previousSnapshotId: "before", currentSnapshotId: "after", policySet: [{ id: "attention.test", version: "1.0.0" }], records, summary: { evaluatedChanges: elevatedChanges, elevatedChanges, attentionRecords: records.length, matchedPolicies: records.length ? 1 : 0, byDomain: { identity: 0, context: 0, roles: 0, projects: 0, commitments: records.length, waitingItems: 0, priorities: 0, activeWork: 0, sources: 0 }, byChangeType: { added: 0, modified: records.length, removed: 0 } } }); };
const engine = (policies = INITIAL_SITUATION_FORMATION_POLICIES) => new ExecutiveSituationEngine(new SituationFormationRegistry(policies));

describe("Executive Situation Formation", () => {
  it("groups records for the same canonical entity and separates distinct entities", () => { const result = engine().form(queue(record("attention:a", "a"), record("attention:b", "a"), record("attention:c", "b"))); expect(result.situations.map(s => s.memberships.length)).toEqual([2, 1]); expect(result.situations[0].formationPolicy.id).toBe("situation.same-canonical-entity"); expect(result.summary).toEqual({ attentionRecords: 3, executiveSituations: 2, singletonCount: 1, multiRecordCount: 1, recordsByPolicy: { "situation.same-canonical-entity": 2, "situation.singleton": 1 } }); });
  it("forms exactly one singleton for every unmatched record", () => { const result = engine().form(queue(record("attention:a", "a"), record("attention:b", "b"))); expect(result.situations).toHaveLength(2); expect(result.situations.every(s => s.formationPolicy.id === "situation.singleton")).toBe(true); });
  it("groups only explicit shared project or role references", () => { const result = engine().form(queue(record("attention:a", "a", { projectIds: ["project:one"] }), record("attention:b", "b", { projectIds: ["project:one"] }), record("attention:c", "c", { roleIds: ["role:other"] }))); expect(result.situations.map(s => [s.formationPolicy.id, s.memberships.length])).toEqual([["situation.explicit-project-role-reference", 2], ["situation.singleton", 1]]); });
  it("is independent of policy registration order and replay safe", () => { const input = queue(record("attention:z", "a"), record("attention:a", "a")); const a = engine().form(input); const b = engine([...INITIAL_SITUATION_FORMATION_POLICIES].reverse()).form(input); expect(a).toEqual(b); expect(createExecutiveSituationSet(JSON.parse(JSON.stringify(a)))).toEqual(a); expect(a.situations[0].situationId).toBe("situation:after:situation.same-canonical-entity:attention%3Aa,attention%3Az"); });
  it("deep freezes the complete canonical result", () => { const result = engine().form(queue(record("attention:a", "a"))); expect(Object.isFrozen(result)).toBe(true); expect(Object.isFrozen(result.situations)).toBe(true); expect(Object.isFrozen(result.situations[0].memberships[0].attentionRecord.reason.evidence)).toBe(true); });
  it("validates registry metadata and rejects duplicate identifiers", () => { expect(() => new SituationFormationRegistry([{ id: "", version: "1", displayName: "x", description: "x", form: () => [] }])).toThrow("non-empty string"); expect(() => new SituationFormationRegistry([singletonFormationPolicy, singletonFormationPolicy])).toThrow("duplicate situation formation policy identifier"); expect(new SituationFormationRegistry([sameCanonicalEntityPolicy]).metadata()).toEqual([{ id: sameCanonicalEntityPolicy.id, version: "1.0.0", displayName: "Same canonical entity", description: sameCanonicalEntityPolicy.description }]); });
  it("fails atomically when policies claim overlapping membership", () => { const duplicate: SituationFormationPolicy = { id: "situation.test-overlap", version: "1", displayName: "Overlap", description: "Produces an explicit overlapping group for validation.", form: records => [{ key: "overlap", reasonCode: "overlap", evidence: {}, records }] }; expect(() => engine([sameCanonicalEntityPolicy, singletonFormationPolicy, duplicate]).form(queue(record("attention:a", "a"), record("attention:b", "a")))).toThrow("ambiguous situation membership"); });
  it("rejects duplicate membership and malformed summaries during canonical validation", () => { const valid = engine().form(queue(record("attention:a", "a"))); const duplicate = { ...valid, situations: [valid.situations[0], valid.situations[0]] }; expect(() => createExecutiveSituationSet(duplicate)).toThrow(/duplicate situation identifier|duplicate situation membership/); expect(() => createExecutiveSituationSet({ ...valid, summary: { ...valid.summary, attentionRecords: 2 } })).toThrow("summary is inconsistent"); });
});
