import type { ExecutiveAttentionQueue } from "../attention";
import type { ExecutiveSituationSet, SituationFormationGroup, SituationFormationPolicy, SituationFormationPolicyMetadata } from "./types";

export const compareText = (a: string, b: string): number => a < b ? -1 : a > b ? 1 : 0;
export function required(value: unknown, path: string): asserts value is string { if (typeof value !== "string" || value.trim() === "") throw new Error(`${path} must be a non-empty string`); }
export function clone<T>(value: T): T { if (Array.isArray(value)) return value.map(clone) as T; if (value && typeof value === "object") return Object.fromEntries(Object.entries(value).map(([k, v]) => [k, clone(v)])) as T; return value; }
export function deepFreeze<T>(value: T): T { if (value && typeof value === "object" && !Object.isFrozen(value)) { Object.values(value).forEach(deepFreeze); Object.freeze(value); } return value; }
export function jsonCompatible(value: unknown, path = "value", ancestors = new Set<object>()): void { if (value === null || typeof value === "string" || typeof value === "boolean" || (typeof value === "number" && Number.isFinite(value))) return; if (!value || typeof value !== "object" || ancestors.has(value as object) || (!Array.isArray(value) && Object.getPrototypeOf(value) !== Object.prototype)) throw new Error(`${path} must contain only JSON-compatible values`); ancestors.add(value as object); for (const [key, child] of Object.entries(value)) jsonCompatible(child, `${path}.${key}`, ancestors); ancestors.delete(value as object); }
export function validatePolicy(policy: SituationFormationPolicy): void { if (!policy || typeof policy !== "object") throw new Error("situation formation policy must be an object"); required(policy.id, "situation formation policy id"); required(policy.version, "situation formation policy version"); required(policy.displayName, "situation formation policy displayName"); required(policy.description, "situation formation policy description"); if (typeof policy.form !== "function") throw new Error("situation formation policy must implement form()"); }
export function validateGroup(group: SituationFormationGroup, policy: SituationFormationPolicy, queue: ExecutiveAttentionQueue): void { if (!group || typeof group !== "object") throw new Error(`situation formation policy ${policy.id} returned an invalid group`); required(group.key, "situation formation group key"); required(group.reasonCode, "situation membership reason code"); if (!Array.isArray(group.records) || group.records.length === 0) throw new Error("situation formation group records must be non-empty"); jsonCompatible(group.evidence, "situation membership evidence"); const queueRecords = new Set(queue.records.map(r => r.attentionId)); const seen = new Set<string>(); for (const record of group.records) { if (!record || !queueRecords.has(record.attentionId)) throw new Error(`situation formation policy ${policy.id} returned a record outside the queue`); if (seen.has(record.attentionId)) throw new Error(`duplicate membership in policy group: ${record.attentionId}`); seen.add(record.attentionId); } }
export function createExecutiveSituationSet(candidate: ExecutiveSituationSet): ExecutiveSituationSet {
  jsonCompatible(candidate, "executive situation set"); required(candidate.currentSnapshotId, "situation set currentSnapshotId"); required(candidate.queueId, "situation set queueId");
  if (!Array.isArray(candidate.situations) || !candidate.summary) throw new Error("executive situation set has invalid structure");
  const memberships = new Set<string>(); const situationIds = new Set<string>(); let previous: ExecutiveSituationSet["situations"][number] | undefined;
  for (const situation of candidate.situations) { required(situation.situationId, "situation id"); if (situationIds.has(situation.situationId)) throw new Error(`duplicate situation identifier: ${situation.situationId}`); situationIds.add(situation.situationId); if (situation.currentSnapshotId !== candidate.currentSnapshotId || !situation.memberships.length) throw new Error("situation snapshot or membership is invalid"); const sortedIds: string[] = situation.memberships.map((m: typeof situation.memberships[number]) => m.attentionRecord.attentionId); if (sortedIds.some((id: string, i: number) => i > 0 && compareText(sortedIds[i - 1], id) >= 0)) throw new Error("situation memberships are not deterministically ordered"); const expected = situationIdentity(candidate.currentSnapshotId, sortedIds, situation.formationPolicy.id); if (situation.situationId !== expected) throw new Error("invalid situation identity"); for (const membership of situation.memberships) { if (membership.formationPolicyId !== situation.formationPolicy.id || membership.formationPolicyVersion !== situation.formationPolicy.version) throw new Error("malformed situation membership policy reference"); required(membership.reason.code, "membership reason code"); jsonCompatible(membership.reason.evidence, "membership reason evidence"); const id = membership.attentionRecord.attentionId; if (memberships.has(id)) throw new Error(`duplicate situation membership: ${id}`); memberships.add(id); if (membership.attentionRecord.currentSnapshotId !== candidate.currentSnapshotId) throw new Error("membership snapshot is inconsistent"); } if (previous && compareSituation(previous, situation) >= 0) throw new Error("situations are not deterministically ordered"); previous = situation; }
  const counts: Record<string, number> = {}; for (const s of candidate.situations) counts[s.formationPolicy.id] = (counts[s.formationPolicy.id] ?? 0) + s.memberships.length; const canonicalCounts = Object.fromEntries(Object.entries(counts).sort(([a], [b]) => compareText(a, b))); const summary = candidate.summary;
  if (summary.attentionRecords !== memberships.size || summary.executiveSituations !== candidate.situations.length || summary.singletonCount !== candidate.situations.filter(s => s.memberships.length === 1).length || summary.multiRecordCount !== candidate.situations.filter(s => s.memberships.length > 1).length || JSON.stringify(summary.recordsByPolicy) !== JSON.stringify(canonicalCounts)) throw new Error("executive situation summary is inconsistent");
  return deepFreeze(clone(candidate));
}
const encode = (value: string): string => encodeURIComponent(value);
export const situationIdentity = (snapshotId: string, attentionIds: readonly string[], policyId: string): string => `situation:${encode(snapshotId)}:${encode(policyId)}:${[...attentionIds].sort(compareText).map(encode).join(",")}`;
export const compareSituation = (a: ExecutiveSituationSet["situations"][number], b: ExecutiveSituationSet["situations"][number]): number => compareText(a.memberships[0].attentionRecord.attentionId, b.memberships[0].attentionRecord.attentionId) || compareText(a.formationPolicy.id, b.formationPolicy.id) || compareText(a.situationId, b.situationId);
export const metadataOf = (policy: SituationFormationPolicy): SituationFormationPolicyMetadata => ({ id: policy.id, version: policy.version, displayName: policy.displayName, description: policy.description });
